import assert from 'node:assert/strict';
import {TranslationMemory} from '../web/translation-memory.js';
import {nonSpeechReason} from '../web/speech-filter.js';
import {createServerRecognition,isIncompleteJapanese} from '../web/caption-server.js';
const storage={getItem(){return this.value||null;},setItem(k,v){this.value=v;}};
const memory=new TranslationMemory(storage);
assert.equal(memory.lookup('ja','15時です',['en'],'数学'),null);
memory.remember('ja','15時です',{en:'It is 15:00.',pt:'São 15:00.'},'数学');
assert.equal(memory.lookup('ja','15時です',['en','pt'],'数学').source,'reviewed');
assert.equal(memory.lookup('ja','16時です',['en'],'数学'),null);
assert.equal(memory.lookup('ja','15時ではありません',['en'],'数学'),null);
assert.equal(memory.lookup('ja','15時です',['es'],'数学'),null);
assert.equal(memory.lookup('ja','15時です',['en'],'国語'),null);
assert.equal(new TranslationMemory(storage).lookup('ja','15時です',['en'],'数学').translations.en,'It is 15:00.');
memory.correct('鳥の3を解きます','問の3を解きます','数学');
assert.equal(memory.corrected('鳥の3を解きます','数学'),'問の3を解きます');
assert.equal(memory.corrected('鳥の4を解きます','数学'),'鳥の4を解きます');
assert.equal(memory.corrected('鳥の3を解きます','生物'),'鳥の3を解きます');
assert.equal(memory.lookup('ja','持参',['en'],'',{glossary:[{ja:'持参',en:'bring',status:'pending'}]}),null);
assert.equal(memory.lookup('ja','持参',['en'],'',{glossary:[{ja:'持参',en:'bring',status:'approved'}]}).translations.en,'bring');
for(const text of ['ん','はっくしょん','ハックション！','くしゅん'])assert.equal(nonSpeechReason({text},'ja'),'nonverbal');
for(const text of ['はい','いいえ','うん','ん？','弁当が必要です'])assert.equal(nonSpeechReason({text},'ja'),null);
assert.equal(nonSpeechReason({text:'Hello',segments:[{no_speech_prob:.9}]},'en'),'model_no_speech');
assert.equal(isIncompleteJapanese('来週の木曜日'),true);
assert.equal(isIncompleteJapanese('午後3時40分'),true);
const R=createServerRecognition({endpoint:'https://example.test/transcribe?language=ja',getStream:()=>null,getToken:async()=>'',Context:class{},Worklet:class{},fetcher:async()=>({ok:true,status:200,json:async()=>({text:'ハックション'})})});
const recognition=new R();recognition.active=true;let translated=0;recognition.onresult=()=>translated++;recognition.queue.push({samples:new Int16Array(16000),at:Date.now()});await recognition.drain();assert.equal(translated,0);recognition.abort();
const progressive=new R(),events=[];progressive.active=true;progressive.onresult=e=>events.push(e);for(const text of ['10月9日','金曜日の','終業式について','お知らせです'])progressive.acceptText(text,{boundary:'limit'});assert.equal(new Set(events.map(e=>e.resultIndex)).size,1);assert.equal(events.at(-1).continuing,false);assert.equal(progressive.fragment,null);progressive.abort();
console.log('Reviewed memory and non-speech checks passed');
