import './reviewed-memory.mjs';
import './reuse-quality.mjs';
import {protectUncertainSpeech,restoreUncertainSpeech} from '../server/quality.js';
import {speechScore} from '../tools/speech-score.js';
import {recognitionHints,safeRecognitionHints} from '../web/recognition-hints.js';
import {runInNewContext} from 'node:vm';
import {storedTranslations,correctionHints} from '../server/dictionary.js';
import {acquireMicrophone} from '../web/microphone.js';
import assert from 'node:assert/strict';
import {PcmSegmenter} from '../web/caption-pcm.js';
import {readdir,readFile} from 'node:fs/promises';
import {SourceTextModule} from 'node:vm';
import {fileURLToPath} from 'node:url';
import {protectMath,parseTranslation,glossaryFor,csv,validateCaption} from '../web/core.js';
import {catalog} from '../server/catalog.js';
import workerApi,{TranslationRoom,translateText,recognizeAudio,aiFailure,runAi,translationBudget,requestExecutionValid} from '../server/worker.js';
import {ConnectionDiary,connectionFailure,requestJson,probeNetwork,explainConnection,summarizeSessions} from '../web/network.js';
import {verifyToken} from '../server/auth.js';
import {validWav,hasSpeechEnergy,cleanRecognition} from '../server/audio.js';
import {createServerRecognition,encodeWav,isIncompleteJapanese} from '../web/caption-server.js';
import {UsageLedger,costOf,analysisReport,percentile} from '../web/usage.js';
import {SpeechPlayer} from '../web/speech-player.js';
import {firstVoicedAt,lastVoicedAt,latencyFromTiming,retryDelay} from '../web/diagnostics.js';
import {speakerInfo,speakerCaption} from '../web/face-mode.js';
import {captionParticipant,spokenLanguage,translationOf,withEasyJapanese} from '../web/core.js';
import {LessonCodes,ROOM_TTL,normalizeRoomCode} from '../server/lesson-codes.js';
import {historyExpired} from '../web/history.js';
import {callCaptionLanguages,isDisplayableCaption} from '../web/call-mode.js';
let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name);}
await test('数式・否定・数字を壊さない',()=>assert.equal(protectMath('x² + ３x − ２ = ０ ではありません。'),'x² + 3x − 2 = 0 ではありません。'));
await test('全言語の結果がそろわなければ翻訳失敗にする',()=>{assert.deepEqual(parseTranslation('```json\n{"ja":"日本語","en":"English"}\n```',['ja','en']),{ja:'日本語',en:'English'});assert.throws(()=>parseTranslation('{"en":""}',['en']));assert.throws(()=>parseTranslation('{"en":"English"}',['en','pt']));});
await test('数学辞書は24語・ID重複なし',()=>{assert.equal(catalog.glossary.length,24);assert.equal(new Set(catalog.glossary.map(r=>r.id)).size,24);assert.ok(glossaryFor('正の平方根と平方根を区別する',catalog.glossary).some(t=>t.en==='positive square root'));assert.equal(catalog.phrases.length,20);assert.equal(catalog.terms.length,584);});
await test('CSVの数式注入を防ぎ、改行・引用符を保持',()=>assert.equal(csv([['=1+1','a"b','a\nb']]),'\uFEFF"\'=1+1","a""b","a\nb"'));
await test('字幕の上限と識別子を検査',()=>{assert.throws(()=>validateCaption({id:'ok',text:'a'.repeat(1201)}));assert.throws(()=>validateCaption({id:'../x',text:'a'}));assert.equal(validateCaption({id:'test_1',text:'  数学  ',final:true}).text,'数学');});
await test('無音をAIへ送らない',()=>{const bytes=new Uint8Array(encodeWav(new Int16Array(16000)));assert.ok(validWav(bytes));assert.equal(hasSpeechEnergy(bytes),false);bytes[0]=0;assert.equal(validWav(bytes),false);});
await test('文例の完全一致は既存翻訳を即時利用',async()=>{const r=await translateText({AI:{run(){throw Error('AIを呼ばない');}}},catalog.phrases[0].jaText,'ja',['ja','en','pt']);assert.equal(r.en,catalog.phrases[0].enText);});
await test('AIへ原文・用語・前後の文脈を渡し直接多言語翻訳',async()=>{let request;const env={AI:{async run(model,p){request=p;return {response:'{"en":"coefficient 3","pt":"coeficiente 3"}'};}}};const r=await translateText(env,'係数は3です','ja',['en','pt'],['式を見ましょう'],'一次方程式');assert.equal(r.en,'coefficient 3');const payload=JSON.parse(request.messages[1].content);assert.equal(payload.speech,'係数は3です');assert.equal(payload.glossary[0].en,'coefficient');assert.deepEqual(payload.targets,['en','pt']);});
const b64=data=>Buffer.from(typeof data==='string'?data:JSON.stringify(data)).toString('base64url');
await test('Firebase JWTは署名・発行元・期限を検証',async()=>{const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk=await crypto.subtle.exportKey('jwk',pair.publicKey);jwk.kid='test-key';const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({keys:[jwk]}));try{const now=Math.floor(Date.now()/1000);const create=async changes=>{const payload={aud:'test-project',iss:'https://securetoken.google.com/test-project',sub:'teacher',exp:now+3600,iat:now,firebase:{sign_in_provider:'google.com'},...changes};const data=b64({alg:'RS256',kid:'test-key'})+'.'+b64(payload);const signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(data));return data+'.'+Buffer.from(signature).toString('base64url');};assert.equal((await verifyToken(await create({}),'test-project')).uid,'teacher');const env={ALLOWED_ORIGIN:'https://example.test',FIREBASE_PROJECT:'test-project',ROOMS:{get(){throw Error('No DO allowed');}},AI:{run(){throw Error('No AI for a registered phrase');}}};const translated=await workerApi.fetch(new Request('https://api.test/translate',{method:'POST',headers:{Origin:'https://example.test',Authorization:'Bearer '+await create({}),'Content-Type':'application/json'},body:JSON.stringify({text:catalog.phrases[0].jaText,source:'ja',targets:['en','pt']})}),env);assert.equal(translated.status,200);assert.equal((await translated.json()).translations.en,catalog.phrases[0].enText);await assert.rejects(async()=>verifyToken(await create({exp:now-1}),'test-project'));await assert.rejects(async()=>verifyToken(await create({aud:'other'}),'test-project'));await assert.rejects(()=>verifyToken('fake','test-project'));}finally{globalThis.fetch=original;}});
function fixture(mode='lesson',role='guest'){const db=new Map([['room',{mode,owner:'owner',key:'secret',expires:Date.now()+ROOM_TTL,unit:'数学'}]]),messages=[];const a={uid:role==='teacher'?'owner':'guest',id:'a'.repeat(32),name:'テスト',role,language:'ja',viewLanguage:'pt',expires:Date.now()+3600000,window:Date.now(),count:0};const ws={deserializeAttachment:()=>a,serializeAttachment:x=>Object.assign(a,x),send:s=>messages.push(JSON.parse(s)),close(){}};const sockets=[ws];const jobs=[];const ctx={storage:{get:async k=>db.get(k),put:async(k,v)=>db.set(k,v),getAlarm:async()=>0,setAlarm:async()=>{},list:async({prefix})=>new Map([...db].filter(([k])=>k.startsWith(prefix))),deleteAll:async()=>db.clear()},getWebSockets:()=>sockets,waitUntil:p=>jobs.push(p)};const env={FIREBASE_PROJECT:'test-project',AI:{async run(){return {response:'{"en":"x is 3","pt":"x é 3"}'};}}};return {room:new TranslationRoom(ctx,env),ws,db,messages,jobs,sockets};}

function addStudent(f){const attachment={...f.ws.deserializeAttachment(),uid:'student',id:'b'.repeat(32),role:'guest',language:'pt',viewLanguage:'pt'},messages=[];const ws={deserializeAttachment:()=>attachment,serializeAttachment:value=>Object.assign(attachment,value),send:text=>messages.push(JSON.parse(text)),close(){}};f.sockets.push(ws);return {ws,attachment,messages};}
await test('先生の言語変更は本人へ通知し参加者一覧にも反映・AI呼び出しなし',async()=>{const f=fixture('lesson','teacher'),student=addStudent(f);await f.room.webSocketMessage(f.ws,JSON.stringify({type:'participant_language',to:student.attachment.id,language:'en'}));assert.equal(student.attachment.language,'en');assert.equal(student.attachment.viewLanguage,'en');assert.ok(student.messages.some(m=>m.type==='language_changed'&&m.language==='en'));assert.equal(student.messages.find(m=>m.type==='participants').participants.find(p=>p.id===student.attachment.id).viewLanguage,'en');assert.equal(f.jobs.length,0);});
await test('生徒は本人の言語だけ変更可能・先生と他の生徒は変更不可',async()=>{const f=fixture('lesson','teacher'),student=addStudent(f);for(const to of [f.ws.deserializeAttachment().id,'c'.repeat(32)])await f.room.webSocketMessage(student.ws,JSON.stringify({type:'participant_language',to,language:'en'}));assert.equal(f.ws.deserializeAttachment().language,'ja');assert.equal(student.attachment.language,'pt');assert.equal(student.messages.filter(m=>m.error).length,2);await f.room.webSocketMessage(student.ws,JSON.stringify({type:'participant_language',to:student.attachment.id,language:'en'}));assert.equal(student.attachment.viewLanguage,'en');});
await test('不正言語・終了済み授業は言語変更を拒否',async()=>{const f=fixture('lesson','teacher'),student=addStudent(f);await f.room.webSocketMessage(f.ws,JSON.stringify({type:'participant_language',to:student.attachment.id,language:'invalid'}));f.db.get('room').ended=true;await f.room.webSocketMessage(f.ws,JSON.stringify({type:'participant_language',to:student.attachment.id,language:'en'}));assert.equal(student.attachment.viewLanguage,'pt');assert.equal(f.messages.filter(m=>m.error).length,2);});
await test('生徒は字幕送信・授業終了を実行できない',async()=>{const f=fixture();await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'one',text:'x=3',final:true}));assert.ok(f.messages[0].error);assert.equal(f.db.has('caption:'+f.ws.deserializeAttachment().id+'_one'),false);await f.room.webSocketMessage(f.ws,JSON.stringify({type:'end'}));assert.equal(f.db.get('room').ended,undefined);});
await test('途中字幕は即配信し、保存・翻訳を待たない',async()=>{const f=fixture('lesson','teacher');await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'one',text:'xは',final:false}));assert.equal(f.messages[0].type,'caption');assert.equal(f.db.size,1);assert.equal(f.jobs.length,0);});
await test('確定字幕を3言語で配信し、重複送信を統合',async()=>{const f=fixture('lesson','teacher');const data=JSON.stringify({type:'caption',id:'one',text:'xは3です',final:true});await f.room.webSocketMessage(f.ws,data);await Promise.all(f.jobs);const result=f.messages.find(x=>x.type==='translation');assert.equal(result.translations.pt,'x é 3');assert.equal(result.translations.ja,'xは3です');const count=f.jobs.length;await f.room.webSocketMessage(f.ws,data);assert.equal(f.jobs.length,count);});
await test('翻訳失敗は再試行可能・成功を偽装しない',async()=>{const f=fixture('lesson','teacher');f.room.env.AI.run=async()=>({response:'bad response'});const data=JSON.stringify({type:'caption',id:'one',text:'x=3',final:true});await f.room.webSocketMessage(f.ws,data);await Promise.all(f.jobs);assert.equal(f.messages.find(x=>x.type==='translation').status,'failed');f.room.env.AI.run=async()=>({response:'{"en":"x=3","pt":"x=3"}'});await f.room.webSocketMessage(f.ws,JSON.stringify({...JSON.parse(data),revision:1}));await Promise.all(f.jobs);assert.equal(f.messages.filter(x=>x.type==='translation').at(-1).status,'ready');});
await test('終了後は新しい字幕を受け付けず作成時の期限で削除',async()=>{const f=fixture('lesson','teacher');await f.room.webSocketMessage(f.ws,JSON.stringify({type:'end'}));assert.ok(f.db.get('room').ended);assert.ok(Math.abs(f.db.get('room').expires-Date.now()-ROOM_TTL)<1000);await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'one',text:'x=3',final:true}));assert.equal(f.jobs.length,0);f.db.get('room').expires=Date.now()-1;await f.room.alarm();assert.equal(f.db.size,0);});
await test('料金は入力・出力・音声・中継を別々に集計',()=>{const c=costOf({inputTokens:1e6,outputTokens:1e6,streamSeconds:60,whisperSeconds:60,relayBytes:1e9});assert.ok(Math.abs(c.total-(.1+.3+.0092+.000513+.05))<1e-10);assert.equal(percentile([100,1000,200],.95),1000);});
await test('再送は二重課金せず、失敗後の再試行を計上',()=>{const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};let now=1000;const ledger=new UsageLedger(storage,()=>now);ledger.begin('lesson',['ja','pt','en']);const failed={id:'caption',at:1,final:true,status:'failed',usage:{inputTokens:100,outputTokens:10,estimated:true}};ledger.caption(failed);ledger.caption(failed);ledger.caption({...failed,at:2,status:'ready',latencyMs:1200});ledger.audio(60,'stream');ledger.microphone(true);now+=5000;ledger.end();const s=ledger.list()[0];assert.equal(s.attemptCount,2);assert.equal(s.inputTokens,200);assert.equal(s.failedCaptions,0);assert.equal(s.failedAttempts,1);assert.equal(s.micSeconds,5);assert.equal(s.ended,true);assert.ok(costOf(s).total>0);});
await test('分析の標準出力は本文・接続秘密・利用者名を含めない',()=>{const data=new Map(),ledger=new UsageLedger({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)});ledger.begin('interpreter',['ja','en']);ledger.caption({id:'secret-caption-id',at:1,final:true,status:'ready',text:'private speech',speaker:'private name',latencyMs:300,usage:{inputTokens:10,outputTokens:10}});const report=analysisReport(ledger.list());assert.ok(!report.includes('private speech'));assert.ok(!report.includes('private name'));assert.ok(!report.includes('secret-caption-id'));assert.equal(JSON.parse(report).summary.captions,1);});
await test('中継の累積統計は差分だけ記録する',()=>{const data=new Map(),ledger=new UsageLedger({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)});ledger.begin('interpreter',['ja']);ledger.rtc('connection',{bytes:100,lost:1,relay:true,jitterMs:10,rttMs:20});ledger.rtc('connection',{bytes:150,lost:2,relay:true,jitterMs:5,rttMs:30});const s=ledger.list()[0];assert.equal(s.relayBytes,150);assert.equal(s.packetsLost,2);assert.equal(s.maxJitterMs,10);});
await test('参加中のマイク時間を出力し、停止後も二重加算しない',()=>{const data=new Map();let now=0;const ledger=new UsageLedger({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},()=>now);ledger.begin('interpreter',['ja']);ledger.microphone(true);now=2000;ledger.save();assert.equal(ledger.list()[0].micSeconds,2);now=4000;ledger.save();assert.equal(ledger.list()[0].micSeconds,4);now=5000;ledger.microphone(false);now=9000;ledger.end();assert.equal(ledger.list()[0].micSeconds,5);});
await test('切断分析には数値と状態だけを残し、自由文を保存しない',()=>{const data=new Map(),ledger=new UsageLedger({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)});ledger.begin('interpreter',['ja']);ledger.event('reconnect',{code:1006,wasClean:false,attempt:2,visibility:'hidden',reason:'private user room key',token:'secret'});const report=JSON.parse(analysisReport(ledger.list()));assert.equal(report.summary.reconnectCount,1);assert.equal(report.sessions[0].events[0].code,1006);assert.ok(!JSON.stringify(report).includes('private'));assert.ok(!JSON.stringify(report).includes('secret'));});
await test('発話末尾は無音を除き推定し、文字入力と未計測を区別',()=>{const pcm=new Int16Array(16000);pcm.fill(1000,0,8000);assert.equal(lastVoicedAt(pcm,10000),9500);assert.equal(lastVoicedAt(new Int16Array(16000),10000),null);const m=latencyFromTiming({kind:'speech',speechEndedAt:9500,recognitionReadyAt:10000,sentAt:10010},11000);assert.equal(m.totalMs,1500);assert.equal(m.recognitionMs,500);assert.equal(m.pipelineMs,990);assert.equal(latencyFromTiming({kind:'text',sentAt:10000},11000).totalMs,undefined);assert.equal(latencyFromTiming({kind:'text',sentAt:12000},11000),null);});
await test('字幕の再送を総待ち時間に重複計上しない',()=>{const data=new Map(),ledger=new UsageLedger({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)});ledger.begin('interpreter',['ja']);ledger.timing('one',{totalMs:2000,recognitionMs:500,pipelineMs:1500});ledger.timing('one',{totalMs:9000});const r=JSON.parse(analysisReport(ledger.list()));assert.equal(r.summary.p95SpeechToDisplayMs,2000);assert.equal(r.summary.speechTimingSamples,1);assert.equal(r.summary.p95RecognitionMs,500);});
await test('再接続は間隔を広げ、上限を設ける',()=>{assert.equal(retryDelay(1,()=>0),1000);assert.equal(retryDelay(3,()=>0),4000);assert.equal(retryDelay(30,()=>0),15000);});
await test('読み上げの一時停止・再開・停止と古い完了イベントを扱う',()=>{const calls=[],spoken=[];const engine={cancel:()=>calls.push('cancel'),pause:()=>calls.push('pause'),resume:()=>calls.push('resume'),speak:u=>spoken.push(u)};class Utterance{constructor(text){this.text=text;}}const player=new SpeechPlayer({engine,Utterance});player.toggle('ja','文','ja-JP');assert.equal(player.key,'ja');player.toggle('ja','文','ja-JP');assert.equal(player.paused,true);player.toggle('ja','文','ja-JP');assert.equal(player.paused,false);assert.ok(calls.includes('pause'));assert.ok(calls.includes('resume'));player.toggle('en','sentence','en-US');spoken[0].onend();assert.equal(player.key,'en');player.stop();assert.equal(player.key,null);assert.equal(player.paused,false);spoken[1].onend();assert.equal(player.key,null);});
await test('画面用の全JavaScriptが構文検証を通る',async()=>{for(const file of await readdir(new URL('../web/',import.meta.url))){if(!file.endsWith('.js'))continue;const p=fileURLToPath(new URL('../web/'+file,import.meta.url));new SourceTextModule(await readFile(p,'utf8'),{identifier:p});}});
await test('対面の話し手切替は自分と相手の言語を保持する',()=>{assert.deepEqual(speakerCaption('self','ja','pt'),{source:'ja',speakerSide:'self'});assert.equal(speakerInfo('other','ja','pt').language,'pt');assert.throws(()=>speakerInfo('unknown','ja','pt'));});
await test('対面の字幕言語は選んだ2言語だけを受け付ける',()=>{const a={language:'ja',viewLanguage:'pt',name:'user'};assert.equal(captionParticipant({mode:'face'},a,{source:'pt',speakerSide:'other'}).name,'相手');assert.throws(()=>captionParticipant({mode:'face'},a,{source:'en',speakerSide:'other'}));assert.equal(captionParticipant({mode:'interpreter'},a,{source:'pt'}),a);});
await test('対面の相手の発言は相手言語から翻訳して記録する',async()=>{const f=fixture('face','teacher');f.room.env.AI.run=async()=>({response:'{"ja":"こんにちは。","en":"Hello."}'});await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'face_one',text:'Olá.',source:'pt',speakerSide:'other',final:true}));await Promise.all(f.jobs);const r=f.db.get('caption:'+f.ws.deserializeAttachment().id+'_face_one');assert.equal(r.source,'pt');assert.equal(r.speaker,'相手');assert.equal(r.status,'ready');assert.equal(r.translations.pt,'Olá.');assert.equal(r.translations.ja,'こんにちは。');});
function codeStorage(){const db=new Map();let alarm=0,tail=Promise.resolve();const storage={get:async k=>db.get(k),put:async(k,v)=>db.set(k,v),delete:async k=>db.delete(k),list:async({prefix})=>new Map([...db].filter(([k])=>k.startsWith(prefix))),getAlarm:async()=>alarm,setAlarm:async t=>{alarm=t;}};storage.transaction=fn=>{const result=tail.then(()=>fn(storage));tail=result.catch(()=>{});return result;};return {db,storage};}
await test('4桁IDは同時作成と乱数衝突でも重複しない',async()=>{const f=codeStorage(),codes=new LessonCodes(f.storage,()=>1000,()=>0);const rooms=await Promise.all(Array.from({length:50},(_,i)=>codes.allocate({id:'room'+i,key:'key'+i})));assert.equal(rooms[0].code,'0000');assert.equal(new Set(rooms.map(r=>r.code)).size,50);assert.equal(rooms[0].expires,1000+ROOM_TTL);assert.equal((await codes.lookup('００００')).id,'room0');});
await test('24時間後のIDは再利用でき、古い履歴へ接続しない',async()=>{const f=codeStorage();let now=1000;const codes=new LessonCodes(f.storage,()=>now,()=>0),old=await codes.allocate({id:'old',key:'old-key'});now+=ROOM_TTL;await assert.rejects(()=>codes.lookup(old.code));const next=await codes.allocate({id:'new',key:'new-key'});assert.equal(next.code,old.code);assert.equal((await codes.lookup(next.code)).key,'new-key');await codes.release(old.code,'old');assert.equal((await codes.lookup(next.code)).id,'new');now+=ROOM_TTL;await codes.cleanup();assert.equal(f.db.has('code:0000'),false);});
await test('4桁がすべて使用中なら既存授業を上書きしない',async()=>{const f=codeStorage();for(let i=0;i<10000;i++)f.db.set('code:'+String(i).padStart(4,'0'),{id:'live'+i,expires:ROOM_TTL});await assert.rejects(()=>new LessonCodes(f.storage,()=>1,()=>0).allocate({id:'extra',key:'extra'}));assert.equal(f.db.get('code:0000').id,'live0');});
await test('4桁以外と期限切れの履歴を区別する',()=>{assert.equal(normalizeRoomCode(' ０００７ '),'0007');assert.equal(historyExpired({at:1000},1000+ROOM_TTL),true);assert.equal(historyExpired({at:1000,expires:9000},8999),false);assert.equal(historyExpired({at:1000,expires:9000},9000),true);});
await test('先生の終了操作で履歴の24時間期限を延長しない',async()=>{const f=fixture('lesson','teacher'),expires=f.db.get('room').expires;await f.room.webSocketMessage(f.ws,JSON.stringify({type:'end'}));assert.equal(f.db.get('room').expires,expires);});
await test('全画面の見出しとログイン入口を除き、アイコンはFont Awesomeを使う',async()=>{const h=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(!h.includes('section-heading'));assert.ok(!h.includes('teacher-login'));assert.ok(!h.includes('id="help"'));assert.ok(!h.includes('id="settings"'));assert.ok(h.includes('font-awesome/6.5.2'));assert.ok(!h.includes('tab-student'));assert.ok(h.includes('lesson-role-student'));assert.ok(h.includes('teacher-entry'));for(const id of ['name','view-language','listen','export'])assert.ok(!h.includes('id="'+id+'"'));assert.ok(!h.includes('live-heading'));assert.ok(!h.includes('live-title'));assert.ok(!/[▶Ⅱ■⇄◇◎☎▤▣▧→×]/.test(h));});
await test('削除後に遅れて始まった翻訳は字幕履歴を作り直さない',async()=>{const f=fixture('lesson','teacher'),room=f.db.get('room');f.db.clear();await f.room.translate(f.ws,f.ws.deserializeAttachment(),room,'late','遅れた字幕');assert.equal(f.db.size,0);});
await test('未登録の数学用語は原語と定義から指定言語へ訳し、使用量を返す',async()=>{let input,usage;const env={AI:{async run(model,data){input=JSON.parse(data.messages[1].content);return {response:'{"pt":"Coeficiente: o número que multiplica uma variável."}',usage:{prompt_tokens:123,completion_tokens:17}};}}};const result=await translateText(env,'係数\n文字にかけられている数。','ja',['pt'],[],'数学',catalog,u=>usage=u);assert.equal(input.speech,'係数\n文字にかけられている数。');assert.deepEqual(input.targets,['pt']);assert.equal(input.unit,'数学');assert.match(result.pt,/Coeficiente/);assert.equal(usage.inputTokens,123);assert.equal(usage.outputTokens,17);assert.equal(usage.unknown,false);});
await test('通話の表示は自分の言語と英語、英語を選んだときは1行',()=>{assert.deepEqual(callCaptionLanguages('pt'),['pt','en']);assert.deepEqual(callCaptionLanguages('ja'),['ja','en']);assert.deepEqual(callCaptionLanguages('en'),['en']);});
await test('途中字幕・未翻訳・失敗は一覧に追加せず、確定した翻訳だけを表示',()=>{const base={text:'こんにちは',final:true,status:'ready',translations:{ja:'こんにちは',en:'Hello'}};assert.equal(isDisplayableCaption(base),true);for(const change of [{final:false},{status:'translating'},{status:'failed'},{translations:undefined},{translations:{}},{text:' '}])assert.equal(isDisplayableCaption({...base,...change}),false);});
await test('退室通知の直後に参加者から削除し、Close再通知でも二重通知しない',async()=>{const f=fixture('interpreter','teacher'),received=[],a={uid:'other',id:'b'.repeat(32),language:'pt',viewLanguage:'pt',name:'相手',role:'guest'},other={readyState:1,deserializeAttachment:()=>a,send:s=>received.push(JSON.parse(s))};f.room.ctx.getWebSockets=()=>[f.ws,other];await f.room.webSocketMessage(f.ws,JSON.stringify({type:'leave'}));assert.equal(f.room.participants().length,1);assert.equal(received.at(-1).type,'participants');assert.deepEqual(received.at(-1).participants.map(p=>p.id),[a.id]);const notices=received.length;await f.room.webSocketClose(f.ws);assert.equal(received.length,notices);other.readyState=2;assert.equal(f.room.participants().length,0);});
await test('通話の共通言語変更は話す言語と表示言語を合わせる',async()=>{const f=fixture('interpreter','teacher');await f.room.webSocketMessage(f.ws,JSON.stringify({type:'language',language:'es'}));assert.equal(f.ws.deserializeAttachment().language,'es');assert.equal(f.ws.deserializeAttachment().viewLanguage,'es');await f.room.webSocketMessage(f.ws,JSON.stringify({type:'language',language:'unknown'}));assert.equal(f.ws.deserializeAttachment().language,'es');assert.ok(f.messages.at(-1).error);});
await test('通話は参加者それぞれの言語へ訳し、不要な日本語訳を要求しない',async()=>{const f=fixture('interpreter','teacher'),a={uid:'other',id:'b'.repeat(32),language:'es',viewLanguage:'ja',role:'guest',name:'相手'},other={deserializeAttachment:()=>a,send:()=>{}};f.ws.deserializeAttachment().language='pt';f.room.ctx.getWebSockets=()=>[f.ws,other];let requested;f.room.env.AI.run=async(model,data)=>{requested=JSON.parse(data.messages[1].content).targets;return {response:'{"es":"Hola.","en":"Hello."}'};};await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'languages',text:'Olá.',final:true}));await Promise.all(f.jobs);assert.deepEqual(requested,['es','en']);const result=f.messages.find(x=>x.type==='translation');assert.equal(result.status,'ready');assert.equal(result.translations.pt,'Olá.');assert.equal(result.translations.es,'Hola.');assert.equal(result.translations.ja,undefined);});
await test('ルーム作成の通信失敗を再送せず、開始前にも安全な記録を残す',async()=>{const values=new Map(),diary=new ConnectionDiary({getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)});let calls=0;await assert.rejects(()=>requestJson('https://api.example/rooms?key=secret',{method:'POST',headers:{Authorization:'Bearer secret'},body:'private speech'},{fetcher:async()=>{calls++;throw new TypeError('Failed to fetch secret');},operation:'room_create',onFailure:value=>diary.add(value)}),error=>error.connectionIssue&&error.connection.code==='network_or_cors');assert.equal(calls,1);assert.equal(diary.list()[0].operation,'room_create');const stored=JSON.stringify(diary.list());assert.ok(!stored.includes('secret'));assert.ok(!stored.includes('private speech'));assert.equal(diary.list()[0].endpoint,'https://api.example');});
await test('通信の時間切れ・非JSON応答・API側のエラーを区別する',async()=>{assert.equal(connectionFailure({name:'TimeoutError'}).connection.code,'timeout');await assert.rejects(()=>requestJson('https://api.example/rooms',{}, {fetcher:async()=>new Response('<html>filter</html>',{status:200})}),error=>error.connection.code==='invalid_response');await assert.rejects(()=>requestJson('https://api.example/rooms',{}, {fetcher:async()=>new Response(JSON.stringify({error:'満員です。'}),{status:429})}),error=>!error.connectionIssue&&error.httpStatus===429&&error.message==='満員です。');});
await test('接続診断は読み取りと安全なヘッダー検査だけを行いルームを作成しない',async()=>{const requests=[];const checks=await probeNetwork('https://api.example',{fetcher:async(url,options)=>{requests.push({url,options});if(options.method==='POST')throw new TypeError('blocked');return new Response(JSON.stringify({ok:true,app:'通訳君'}));}});assert.equal(checks[0].code,'ok');assert.equal(checks[1].code,'network_or_cors');assert.ok(requests.every(request=>request.url==='https://api.example/health'));assert.equal(requests[1].options.headers.Authorization,'Bearer connectivity-check');assert.equal(requests[1].options.body,'{}');});
await test('通信履歴は50件に制限し秘密・本文・任意の文字列を除く',()=>{const values=new Map(),diary=new ConnectionDiary({getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)});for(let i=0;i<60;i++)diary.add({stage:'api',operation:'unknown room key',endpoint:'https://name:password@api.example/secret#key',code:'network_or_cors',token:'secret',text:'private',at:i});assert.equal(diary.list().length,50);assert.equal(diary.list()[0].at,10);assert.equal(diary.list()[0].operation,'other');assert.ok(!JSON.stringify(diary.list()).includes('password'));assert.ok(!JSON.stringify(diary.list()).includes('secret'));assert.ok(!JSON.stringify(diary.list()).includes('private'));});
await test('診断APIとルーム用CORSヘッダーは指定の接続元だけを許可する',async()=>{const origin='https://hiroakiaa.github.io',env={ALLOWED_ORIGIN:origin};const preflight=await workerApi.fetch(new Request('https://api.example/health',{method:'OPTIONS',headers:{Origin:origin,'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'authorization,content-type'}}),env);assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),origin);assert.match(preflight.headers.get('Access-Control-Allow-Headers'),/Authorization/);const response=await workerApi.fetch(new Request('https://api.example/health',{method:'POST',headers:{Origin:origin,Authorization:'Bearer connectivity-check','Content-Type':'application/json'},body:'{}'}),env);assert.equal((await response.json()).ok,true);const rejected=await workerApi.fetch(new Request('https://api.example/health',{method:'OPTIONS',headers:{Origin:'https://other.example'}}),env);assert.equal(rejected.status,403);assert.equal(rejected.headers.get('Access-Control-Allow-Origin'),null);});
await test('学校の両通信失敗は原因を断定せず確認手順を出す',()=>{const r=explainConnection([{stage:'api_simple',code:'network_or_cors',endpoint:'https://api.example'},{stage:'api_headers',code:'network_or_cors',endpoint:'https://api.example'},{stage:'turn',code:'network_or_cors',endpoint:'https://turn.example'}],{authentication:'ready'});assert.ok(r.facts.some(f=>f.includes('準備は完了')));assert.equal(r.candidates[0].confidence,'未確定');assert.ok(r.nextSteps.length>=3);assert.ok(r.notMeasured.includes('DNSの解決結果'));});
await test('ヘッダー付き通信だけの失敗と現在の復旧を区別する',()=>{const rows=[{stage:'api_simple',code:'ok'},{stage:'api_headers',code:'network_or_cors'}];assert.match(explainConnection(rows).candidates[0].cause,/プリフライト/);rows.push({stage:'api_headers',code:'ok'});assert.equal(explainConnection(rows).candidates.length,0);});
await test('HTTP状態と想定外応答の診断にも秘密を含めない',()=>{const r=explainConnection([{stage:'api_simple',code:'http_error',status:403,endpoint:'https://name:password@api.example/private?token=secret'},{stage:'api_headers',code:'invalid_response'}]);assert.match(r.candidates[0].cause,/拒否/);assert.ok(!JSON.stringify(r).includes('secret'));assert.ok(!JSON.stringify(r).includes('password'));assert.deepEqual(r.requiredEndpoints,['https://api.example']);});
await test('古い失敗を現在の障害判定から除外し時刻を保持する',()=>{const now=600000,r=explainConnection([{at:1,stage:'api_simple',code:'timeout'},{at:2,stage:'api_headers',code:'timeout'},{at:now,stage:'api_simple',code:'ok'},{at:now,stage:'api_headers',code:'ok'}],{now});assert.equal(r.pastRecordCount,2);assert.equal(r.candidates.length,0);assert.ok(!r.nextSteps.some(s=>s.includes('Wi-Fi')));});
await test('今回の翻訳と中継成功を診断の時間切れとは別に出力する',()=>{const now=600000,sessions=[{startedAt:500000,updatedAt:590000,ended:true,captionCount:8,failedCaptions:0,relayBytes:428459,latencies:[17104,334],events:[]}];const r=explainConnection([{at:now,stage:'api_simple',code:'timeout'}],{now,sessions});assert.equal(r.candidates.length,1);assert.equal(r.sessionResults[0].translatedCaptions,8);assert.equal(r.sessionResults[0].firstTranslationMs,17104);assert.equal(r.sessionResults[0].slowTranslationCount,1);assert.ok(r.facts.some(f=>f.includes('TURN中継通信')));});
await test('利用結果の要約に本文・秘密をコピーしない',()=>{const r=summarizeSessions([{startedAt:1,captionCount:2,text:'private speech',token:'secret',events:[{type:'reconnect',reason:'private'}]}]);assert.equal(r[0].reconnectCount,1);assert.equal(r[0].firstTranslationMs,null);assert.ok(!JSON.stringify(r).includes('private'));assert.ok(!JSON.stringify(r).includes('secret'));});


await test('音声認識は一時的なHTTP障害から次の発話で復旧する',async()=>{let calls=0,results=0,errors=0,diagnostics=[];const Recognition=createServerRecognition({endpoint:'https://example.test/transcribe',getStream:()=>null,getToken:async()=> 'test',Context:class{},Worklet:class{},fetcher:async()=>++calls===1?{ok:false,status:503}:{ok:true,status:200,json:async()=>({text:'hello'})},onDiagnostic:d=>diagnostics.push(d)});const r=new Recognition();r.active=true;r.onresult=()=>results++;r.onerror=()=>errors++;r.queue.push({samples:new Int16Array(16000),at:Date.now()});await r.drain();assert.equal(r.active,true);assert.equal(errors,0);r.queue.push({samples:new Int16Array(16000),at:Date.now()});await r.drain();assert.equal(results,1);assert.equal(r.failures,0);assert.deepEqual(diagnostics.map(d=>d.status),[503,200]);r.abort();});



await test('高速音声モデルが失敗したら独立した予備モデルへWAVを渡す',async()=>{const calls=[];const wav=new Uint8Array(encodeWav(new Int16Array(16000)));const result=await recognizeAudio({AI:{run:async(model,input)=>{calls.push({model,input});if(calls.length===1)throw Error('model unavailable');return {text:'hello'};}}},wav,'en');assert.equal(result.text,'hello');assert.equal(calls[0].input.vad_filter,true);assert.equal(calls[1].model,'@cf/openai/whisper');assert.deepEqual(calls[1].input.audio,Array.from(wav));});

await test('低費用認識は無音10秒を送信しない',()=>{const out=[],s=new PcmSegmenter(16000,x=>out.push(x));s.push(new Float32Array(160000));assert.equal(out.length,0);});
await test('短い発話は600msの無音で送信し先頭を保持する',()=>{const out=[],s=new PcmSegmenter(16000,x=>out.push(x));s.push(Float32Array.from({length:6400},(_,i)=>Math.sin(i*.15)*.08));s.push(new Float32Array(9601));assert.equal(out.length,1);assert.ok(out[0].length<=20000);assert.ok(validWav(new Uint8Array(encodeWav(out[0]))));});
await test('連続発話は3秒に制限し停止時に音声を消去する',()=>{const out=[],s=new PcmSegmenter(16000,x=>out.push(x));s.push(Float32Array.from({length:160000},(_,i)=>Math.sin(i*.15)*.08));assert.equal(out.length,3);assert.equal(out[0].length,48000);s.clear();assert.equal(s.length,0);assert.ok(s.samples.every(x=>x===0));assert.ok(s.preroll.every(x=>x===0));});

await test('CloudflareでRequest.signalが未提供でも有効な翻訳を拒否せず、中断と期限切れを止める',async()=>{const started=100000;for(const signal of [undefined,null,{aborted:false}])assert.equal(requestExecutionValid({signal},started,started+1),true);assert.equal(requestExecutionValid({signal:{aborted:true}},started,started+1),false);assert.equal(requestExecutionValid({},started,started+25000),false);const config=JSON.parse(await readFile(new URL('../wrangler.jsonc',import.meta.url),'utf8'));assert.ok(config.compatibility_flags.includes('enable_request_signal'));});
await test('AIの無料枠・混雑・有料要件を区別しneurons単語だけで上限扱いしない',()=>{assert.equal(aiFailure(Error('3036: daily free allocation')).reason,'quota');assert.equal(aiFailure(Error('3040: capacity exceeded')).reason,'overloaded');assert.equal(aiFailure(Error('5035: model requires paid')).reason,'billing');assert.equal(aiFailure(Error('Invalid neurons input')).reason,'input');assert.ok(!JSON.stringify(aiFailure(Error('private speech token secret'))).includes('secret'));});
await test('失敗字幕は翻訳成功に数えない',()=>{const s=summarizeSessions([{startedAt:1,captionCount:1,failedCaptions:1}]);assert.equal(s[0].translatedCaptions,0);});
await test('音声認識と翻訳のAI失敗が原因候補へ含まれる',()=>{const r=explainConnection([{stage:'api',operation:'transcribe',code:'http_error',status:502,aiReason:'overloaded',aiCode:3040},{stage:'api',operation:'translation',code:'http_error',status:502,aiReason:'quota',aiCode:3036}]);assert.ok(r.candidates.some(x=>x.cause==='AIサービスの混雑'));assert.ok(r.candidates.some(x=>x.cause==='AIの無料枠上限'));});
await test('AIの構造化エラーとcauseのコードを落とさずモデルだけを安全に記録',async()=>{await assert.rejects(()=>runAi({AI:{run:async()=>({success:false,errors:[{code:3036,message:'private speech'}]})}},'@cf/google/gemma-4-26b-a4b-it',{}),e=>{const f=aiFailure(e);assert.equal(f.code,3036);assert.equal(f.reason,'quota');assert.equal(f.evidence,'provider_code');assert.equal(f.model,'@cf/google/gemma-4-26b-a4b-it');assert.ok(!JSON.stringify(f).includes('private'));return true;});assert.equal(aiFailure(Error('daily free allocation')).evidence,'provider_message');});
await test('短文の出力予約は128から必要言語に応じて増え上限4096',()=>{assert.equal(translationBudget('こんばんは',1),128);assert.ok(translationBudget('a'.repeat(600),3)>2048);assert.equal(translationBudget('a'.repeat(600),10),4096);});
await test('辞書にある日本語は末尾の句点がなくてもAIなしで訳す',async()=>{let called=false,usage;const result=await translateText({AI:{run:async()=>{called=true;throw Error('quota');}}},'こんにちは','ja',['en'],[],'',{phrases:[{jaText:'こんにちは。',enText:'Hello.'}]},u=>usage=u);assert.equal(result.en,'Hello.');assert.equal(called,false);assert.equal(usage.cacheHit,true);});
await test('辞書翻訳のHTTP失敗も安全なAI詳細とともに診断へ残す',async()=>{const rows=[];await assert.rejects(()=>requestJson('https://api.example/dictionary/translate',{}, {operation:'dictionary_translate',onFailure:r=>rows.push(r),fetcher:async()=>new Response(JSON.stringify({error:'AI error',aiFailure:{reason:'quota',code:3036,evidence:'provider_code',model:'@cf/google/gemma-4-26b-a4b-it'},text:'private'}),{status:429})}));assert.equal(rows[0].aiCode,3036);assert.equal(rows[0].aiModel,'@cf/google/gemma-4-26b-a4b-it');assert.ok(!JSON.stringify(rows).includes('private'));});
await test('混雑の429はマイクを維持し上限の429は明確な理由で停止',async()=>{for(const reason of ['overloaded','quota']){let detail;const Recognition=createServerRecognition({endpoint:'https://example.test/transcribe',getStream:()=>null,getToken:async()=> 'test',Context:class{},Worklet:class{},fetcher:async()=>({ok:false,status:429,json:async()=>({aiFailure:{reason,message:'AI reports '+reason}})})});const r=new Recognition();r.active=true;r.onerror=e=>detail=e;r.queue.push({samples:new Int16Array(16000),at:Date.now()});await r.drain();assert.equal(r.active,reason==='overloaded');if(reason==='quota')assert.equal(detail.message,'AI reports quota');r.abort();}});
await test('マイク許可待ちの時間切れ後は遅れて得た音声を停止する',async()=>{let release,stopped=0;const stream={getTracks:()=>[{stop:()=>stopped++}]};const pending=new Promise(r=>release=r);await assert.rejects(()=>acquireMicrophone(()=>pending,()=>true,{timeoutMs:5}),e=>e.name==='TimeoutError');release(stream);await new Promise(r=>setTimeout(r,0));assert.equal(stopped,1);});
await test('退室後に届いたマイクは保持せず即停止する',async()=>{let stopped=0;await assert.rejects(()=>acquireMicrophone(async()=>({getTracks:()=>[{stop:()=>stopped++}]}),()=>false),e=>e.name==='AbortError');assert.equal(stopped,1);});
await test('HTTP状態がないWebSocket翻訳失敗でundefinedを表示しない',()=>{const r=explainConnection([{stage:'api',operation:'translation',code:'http_error',aiReason:'quota'}]);assert.ok(!JSON.stringify(r).includes('undefined'));assert.equal(r.candidates.length,1);});
await test('やさしい日本語は日本語音声として認識し古い辞書でも選択できる',()=>{assert.equal(spokenLanguage('ja-easy'),'ja');assert.equal(withEasyJapanese({languages:[{code:'ja'}]}).languages.filter(l=>l.code==='ja-easy').length,1);assert.equal(translationOf({simpleJaText:'あした、もってきてください。'},'ja-easy'),'あした、もってきてください。');assert.equal(translationOf({descriptionJa:'文字にかける数です。'},'ja-easy'),'文字にかける数です。');});
await test('やさしい日本語の文例はAIなしでシートの言い換えを利用',async()=>{const out=await translateText({AI:{run:()=>{throw Error('AI must not run');}}},'ご持参ください','ja-easy',['ja-easy'],[],'',{phrases:[{jaText:'ご持参ください',simpleJaText:'もってきてください。'}]});assert.equal(out.ja,'ご持参ください');assert.equal(out['ja-easy'],'もってきてください。');});
await test('日本語からやさしい日本語へも省略せずAIで言い換える',async()=>{let prompt;const out=await translateText({AI:{run:async(model,input)=>{prompt=input.messages;return {response:'{"ja-easy":"あしたは、お休みではありません。"}'};}}},'明日は休業日ではありません','ja',['ja-easy'],[],'',{phrases:[],glossary:[]});assert.equal(out['ja-easy'],'あしたは、お休みではありません。');assert.ok(prompt[0].content.includes('Preserve all facts'));assert.deepEqual(JSON.parse(prompt[1].content).targets,['ja-easy']);assert.deepEqual(callCaptionLanguages('ja-easy'),['ja','ja-easy','en']);});
await test('承認した完全一致訳だけを再利用し数字・用途の違いを除外',()=>{const bank=[{status:'pending',sourceLang:'ja',sourceText:'15ページ',enText:'pending'},{status:'approved',sourceLang:'ja',sourceText:'15ページ',enText:'page 15',subject:'math',bankKey:'b'}];assert.equal(storedTranslations('15ページ','ja',['en'],{bank},'math').translations.en,'page 15');assert.deepEqual(storedTranslations('16ページ','ja',['en'],{bank},'math').translations,{});assert.deepEqual(storedTranslations('15ページ','ja',['en'],{bank},'science').translations,{});});
await test('シートで埋まっている訳を残し不足言語だけAIへ送る',async()=>{let payload;const result=await translateText({AI:{run:async(model,input)=>{payload=JSON.parse(input.messages[1].content);return {response:'{"es":"página 15"}'};}}},'15ページ','ja',['en','es'],[],'数学',{phrases:[],glossary:[],bank:[{status:'approved',sourceLang:'ja',sourceText:'15ページ',enText:'page 15',subject:'math'}]});assert.deepEqual(payload.targets,['es']);assert.equal(result.en,'page 15');assert.equal(result.es,'página 15');});
await test('訂正ヒントは無効・重複・数字を足すルールを除外し原文は変更しない',()=>{const rules=[{from:'感数',to:'関数',enabled:'TRUE',subject:'math'},{from:'感数',to:'関数',enabled:true,subject:'math'},{from:'鳥の子',to:'問いの5',enabled:true,subject:'common'},{from:'少数',to:'小数',enabled:false,subject:'math'}];assert.deepEqual(correctionHints('感数と鳥の子と少数',rules,'math').map(r=>r.possible),['関数']);});
await test('Google辞書は読み・平易説明を補完し承認待ちの訳を公開しない',async()=>{const ctx={};runInNewContext(await readFile(new URL('../sheets/Code.gs',import.meta.url),'utf8'),ctx);const rows={languages:[{code:'ja'}],school_terms:[{id:'t1',ja:'教科書',reading:'',en:'textbook'}],ruby_dictionary:[{text:'教科書',reading:'きょうかしょ',easyJa:'授業で使う本です。'},{text:'欠席届',reading:'けっせきとどけ',easyJa:'休むことを知らせる紙です。',enText:'A notice of absence.'}],tsuyaku_term_candidates:[{term:'教科書',language:'es',translation:'not reviewed',status:'pending'},{term:'欠席届',language:'es',translation:'Aviso de ausencia.',status:'approved'}],interpreter_translation_bank:[{status:'pending',sourceText:'private',sourceLang:'ja',enText:'private'},{bankKey:'ok',status:'approved',sourceText:'こんにちは',sourceLang:'ja',enText:'Hello'}]};ctx.tsuyakuRows_=name=>rows[name]||[];const result=ctx.tsuyakuCatalog_();assert.equal(result.terms[0].reading,'きょうかしょ');assert.equal(result.terms[0].simpleJaText,'授業で使う本です。');assert.equal(result.terms[0].esText,undefined);assert.equal(result.terms[1].esText,'Aviso de ausencia.');assert.equal(result.bank.length,1);assert.ok(!JSON.stringify(result).includes('private'));});
await test('自動候補保存は登録素材の完全一致だけで一般の会話を保存しない',async()=>{const ctx={};runInNewContext(await readFile(new URL('../sheets/Code.gs',import.meta.url),'utf8'),ctx);ctx.tsuyakuRows_=name=>name==='interpreter_template_sources'?[{jaText:'明日の朝は、体温を確認してください。',status:'imported'}]:[];let saves=0;ctx.tsuyakuPhrase_=()=>{saves++;return {ok:true};};ctx.tsuyakuLearn_({text:'私の家の電話番号は123です。'},{});assert.equal(saves,0);ctx.tsuyakuLearn_({text:'明日の朝は、体温を確認してください。'},{});assert.equal(saves,1);ctx.tsuyakuLearn_({text:'明後日の朝は、体温を確認してください。'},{});assert.equal(saves,1);});

await test('短い返事と小さな声を拾い一瞬のクリック音を送らない',()=>{
 const wave=(n,amp)=>Float32Array.from({length:n},(_,i)=>Math.sin(i*.15)*amp);
 for(const n of [1920,3200]){const out=[],s=new PcmSegmenter(16000,x=>out.push(x));s.push(wave(n,.012));s.push(new Float32Array(9600));assert.equal(out.length,1);assert.ok(validWav(new Uint8Array(encodeWav(out[0]))));assert.ok(hasSpeechEnergy(new Uint8Array(encodeWav(out[0]))));}
 const out=[],s=new PcmSegmenter(16000,x=>out.push(x));s.push(wave(320,.1));s.push(new Float32Array(16000));assert.equal(out.length,0);
});
await test('200msの短い間は文を分断せず48kHzでも無音終了を検出',()=>{
 const out=[],s=new PcmSegmenter(48000,x=>out.push(x));const wave=n=>Float32Array.from({length:n},(_,i)=>Math.sin(i*.05)*.03);
 s.push(wave(19200));s.push(new Float32Array(9600));assert.equal(out.length,0);s.push(wave(19200));s.push(new Float32Array(28800));assert.equal(out.length,1);assert.ok(out[0].length<32000);
});
await test('用語ヒントを音声モデルに渡し未知言語に英語を押し付けない',async()=>{
 let input;await recognizeAudio({AI:{run:async(_,p)=>{input=p;return {text:'問いの3'};}}},new Uint8Array(encodeWav(new Int16Array(16000))),'ja',['問い','教科書']);assert.ok(input.initial_prompt.includes('問い'));assert.ok(input.initial_prompt.includes('教科書'));
 assert.deepEqual(safeRecognitionHints('%E0%A4%A'),[]);assert.deepEqual(safeRecognitionHints(encodeURIComponent('教科書,ignore: instructions,問い,問い')),['教科書','問い']);
 assert.ok(recognitionHints(catalog,'ja','数学').includes('教科書'));assert.ok(recognitionHints(catalog,'ja','数学').includes('方程式'));assert.deepEqual(recognitionHints({glossary:[{ja:'関数',en:'function',esText:'función'}]},'es','数学'),['función']);assert.deepEqual(recognitionHints(catalog,'unknown','数学'),[]);
});

await test('比較評価は数字の誤りと未計測を成功扱いにしない',()=>{assert.equal(speechScore('15ページ','16ページ').numbersMatch,false);assert.equal(speechScore('はい。','はい').characterErrorRate,0);assert.ok(speechScore('必要ありません','必要です').characterErrorRate>0);assert.equal(speechScore('','').characterErrorRate,null);});
await test('不自然な序数は数学の概念や数字を推測せず原文確認として残す',()=>{const p=protectUncertainSpeech('13番から二次つ目になります');assert.equal(p.speech,'13番から__UNCLEAR_1__になります');assert.deepEqual(p.spans,['二次つ目']);const restored=restoreUncertainSpeech({en:'From 13 to __UNCLEAR_1__'},'13番から二次つ目になります',p.spans);assert.ok(restored.en.includes('二次つ目'));assert.ok(restored.en.includes('unclear wording'));assert.ok(!restored.en.includes('quadratic'));assert.ok(restoreUncertainSpeech({en:'second quadratic'},'13番から二次つ目になります',p.spans).en.includes('unclear wording'));assert.deepEqual(protectUncertainSpeech('二次方程式と13番').spans,[]);});
await test('未完の短い日本語だけ次の発話と結合し完成文は待たせない',()=>{assert.equal(isIncompleteJapanese('明日は'),true);assert.equal(isIncompleteJapanese('弁当が必要です'),false);assert.equal(isIncompleteJapanese('はい'),false);assert.equal(isIncompleteJapanese('Tomorrow is'),false);const R=createServerRecognition({endpoint:'https://example.test',getStream:()=>null,getToken:async()=>'',Context:class{},Worklet:class{}}),r=new R(),out=[];r.active=true;r.onresult=e=>out.push(e.results[e.resultIndex][0].transcript);r.acceptText('明日は',{speechEndedAt:1,recognitionReadyAt:2});assert.equal(out.length,1);r.acceptText('6時間目に生徒会選挙があります',{speechEndedAt:3,recognitionReadyAt:4});assert.deepEqual(out,['明日は','明日は 6時間目に生徒会選挙があります']);r.abort();});
await test('待ち行列が増えてもマイクを停止せず古い音声を消去する',async()=>{let node,diag,recover;class W{constructor(){node=this;this.port={postMessage(){}};}connect(){}disconnect(){}}const ctx={state:'running',audioWorklet:{async addModule(){}},createMediaStreamSource(){return {connect(){},disconnect(){}};},async close(){}};const R=createServerRecognition({endpoint:'https://example.test',getStream:()=>null,getToken:async()=>'',Context:class{},Worklet:W,onDiagnostic:d=>diag=d}),r=new R();r.context=ctx;r.active=true;r.drain=async()=>{};r.onrecovering=e=>recover=e;r.onerror=()=>assert.fail('停止してはいけない');await r.prepare({},Promise.resolve());const old=new Int16Array([123]),next=new Int16Array([456]);r.queue=[{samples:old,at:Date.now()},{samples:next,at:Date.now()}];node.port.onmessage({data:new Int16Array(16000)});assert.equal(r.active,true);assert.equal(old[0],0);assert.equal(r.queue.length,2);assert.equal(diag.code,'queue_overflow');assert.equal(recover.reason,'queue_overflow');r.abort();});
await test('最後のAPI成功で途中の認識エラーやHTTP失敗を隠さない',()=>{const now=Date.now(),s={startedAt:now-20000,updatedAt:now,captionCount:1,failedCaptions:0,events:[{type:'recognition_error',recognitionCode:'overloaded'},{type:'asr_restart'},{type:'asr_queue_drop'}]};const r=explainConnection([{at:now-1000,stage:'api',operation:'transcribe',code:'http_error',status:502},{at:now,stage:'api',operation:'transcribe',code:'ok',status:200}],{now,sessions:[s]});assert.ok(r.candidates.some(x=>x.cause==='サーバー側のエラー'));assert.ok(r.candidates.some(x=>x.cause==='利用中の音声認識の中断'));assert.equal(r.sessionResults[0].recognitionRestartCount,1);assert.equal(r.sessionResults[0].queueDropCount,1);assert.ok(r.facts.some(x=>x.includes('最後のAPI成功')));});
await test('日付・曜日を内容と結合し処理上の分割だけで文章を確定しない',()=>{const R=createServerRecognition({endpoint:'https://example.test',getStream:()=>null,getToken:async()=>'',Context:class{},Worklet:class{}});for(const prefix of ['10月9日','１０月９日。','金曜日']){const r=new R(),out=[];r.active=true;r.onresult=e=>out.push(e.results[e.resultIndex][0].transcript);r.acceptText(prefix,{boundary:'pause'});assert.equal(out.length,1);r.acceptText('終業式があります',{boundary:'pause'});assert.equal(out.length,2);assert.ok(out[1].includes('終業式があります'));r.abort();}const r=new R(),out=[];r.active=true;r.onresult=e=>out.push(e.results[e.resultIndex][0].transcript);r.acceptText('これから教科書を開いて問題を確認してください',{boundary:'limit'});assert.equal(out.length,1);r.acceptText('15ページの問1を解きます',{boundary:'pause'});assert.equal(out.length,2);assert.ok(out[1].includes('15ページ'));r.acceptText('別の長い発話の処理用の区切りです',{boundary:'limit'});r.acceptText('さらに続く発話の処理用の区切りです',{boundary:'limit'});assert.equal(out.length,4);assert.ok(r.fragment);r.acceptText("完成しました",{boundary:"pause"});assert.equal(r.fragment,null);r.abort();});
await test('400msの間は保ち3秒の処理区切りを発話末尾と区別',()=>{const out=[],boundaries=[],s=new PcmSegmenter(16000,(x,d)=>{out.push(x);boundaries.push(d.boundary);}),wave=n=>Float32Array.from({length:n},(_,i)=>Math.sin(i*.1)*.03);s.push(wave(9600));s.push(new Float32Array(6400));assert.equal(out.length,0);s.push(wave(16000));assert.equal(out.length,0);s.push(new Float32Array(9600));assert.equal(out.length,1);assert.equal(boundaries[0],'pause');const q=new PcmSegmenter(16000,(x,d)=>boundaries.push(d.boundary));q.push(wave(64000));assert.equal(boundaries.at(-1),'limit');});
await test('音声が欠けた前後の日付と内容を勝手に結合しない',()=>{const R=createServerRecognition({endpoint:'https://example.test',getStream:()=>null,getToken:async()=>'',Context:class{},Worklet:class{}}),r=new R(),out=[];r.active=true;r.onresult=e=>out.push(e.results[e.resultIndex][0].transcript);r.acceptText('10月9日',{boundary:'pause'});r.transientFailure();r.acceptText('弁当が必要です',{boundary:'pause'});assert.deepEqual(out,['10月9日','10月9日','弁当が必要です']);r.abort();});
await test('くしゃみ由来の単独んだけを日本語音声から除外する',()=>{
 for(const text of ['ん','ん。',' ん！ ','ン']) assert.equal(cleanRecognition({text},'ja'),'');
 for(const text of ['はい','いいえ','うん','ん？','ん?','みかん','んですね']) assert.equal(cleanRecognition({text},'ja'),text);
 assert.equal(cleanRecognition({text:'ん'},'pt'),'ん');
 assert.equal(cleanRecognition({text:'ん'},'ja-easy'),'');
 assert.equal(cleanRecognition({text:'雑音 ん',segments:[{text:'雑音',no_speech_prob:.9},{text:'ん',no_speech_prob:.01}]},'ja'),'');
});
await test('環境音の誤認識を確信度で除外し正常な前後の声を残す',()=>{
 const result={text:'授業を始めます エアガーフ エアガーフ お願いします',transcription_info:{segments:[{text:'授業を始めます',no_speech_prob:.01,avg_logprob:-.2,compression_ratio:1},{text:'エアガーフ エアガーフ',no_speech_prob:.8},{text:'お願いします',no_speech_prob:.02}]}};
 assert.equal(cleanRecognition(result),'授業を始めます お願いします');
 assert.equal(cleanRecognition({text:'エアガーフ',segments:[{text:'エアガーフ',avg_logprob:-1.5,compression_ratio:3}]}),'');
 assert.equal(cleanRecognition({text:'はい はい はい',segments:[{text:'はい はい はい',no_speech_prob:.01,avg_logprob:-.2,compression_ratio:3}]}),'はい はい はい');
 assert.equal(cleanRecognition({text:'はい',segments:[{avg_logprob:-1.5,compression_ratio:1}]}),'はい');
 assert.equal(cleanRecognition({text:'こんにちは エアガーフ',segments:[{no_speech_prob:.01},{no_speech_prob:.8}]}),'こんにちは エアガーフ');
 assert.equal(cleanRecognition({text:'エアガーフ',transcription_info:{segments:[{no_speech_prob:.9}]}}),'');
});
await test('無言区間の幻覚対策と音声検出を認識モデルに明示する',async()=>{
 let params;await recognizeAudio({AI:{run:async(_,input)=>{params=input;return {text:''};}}},new Uint8Array(encodeWav(new Int16Array(16000))),'ja');
 assert.equal(params.vad_filter,true);assert.equal(params.condition_on_previous_text,false);assert.equal(params.hallucination_silence_threshold,.6);assert.equal(params.compression_ratio_threshold,2.4);assert.equal(params.log_prob_threshold,-1);
});
await test('最初の認識結果を即送信し続きは同じIDの新しい版にする',()=>{
 const R=createServerRecognition({endpoint:'https://example.test',getStream:()=>null,getToken:async()=>'',Context:class{},Worklet:class{}}),r=new R(),events=[];r.active=true;r.onresult=e=>events.push(e);
 r.acceptText('10月9日',{boundary:'limit',speechStartedAt:100,speechEndedAt:1000});assert.equal(events.length,1);assert.equal(events[0].revision,0);assert.equal(events[0].continuing,true);
 r.acceptText('金曜日に終業式があります',{boundary:'pause',speechStartedAt:1100,speechEndedAt:2000});assert.equal(events.length,2);assert.equal(events[1].resultIndex,events[0].resultIndex);assert.equal(events[1].revision,1);assert.equal(events[1].continuing,false);assert.equal(events[1].speechStartedAt,100);
 r.acceptText('弁当が必要です',{boundary:'pause'});assert.notEqual(events[2].resultIndex,events[0].resultIndex);r.abort();
});
await test('続きがなければ同じ文字の完了通知だけを出し退室後には送らない',()=>{
 const R=createServerRecognition({endpoint:'https://example.test',getStream:()=>null,getToken:async()=>'',Context:class{},Worklet:class{}}),r=new R(),events=[];r.active=true;r.onresult=e=>events.push(e);r.acceptText('明日は',{boundary:'pause'});r.finishFragment();assert.equal(events.length,2);assert.equal(events[1].metadataOnly,true);assert.equal(events[1].continuing,false);assert.equal(events[1].resultIndex,events[0].resultIndex);r.acceptText('10月9日',{boundary:'pause'});r.abort();assert.equal(r.fragment,null);assert.equal(events.length,3);
});
await test('翻訳中に届いた続きを落とさず最新の版へ更新する',async()=>{
 const f=fixture('lesson','teacher');let release,calls=0;f.room.env.AI.run=async()=>{calls++;if(calls===1)await new Promise(r=>release=r);return {response:'{"en":"Closing ceremony on Friday, October 9.","pt":"Cerimônia no dia 9."}'};};
 const send=(text,revision,continuing=false)=>f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'progress',text,revision,continuing,final:true}));
 await send('10月9日',0,true);await new Promise(r=>setTimeout(r,0));assert.equal(calls,1);await send('10月9日 金曜日',1,true);await send('10月9日 金曜日に終業式があります',2);release();await Promise.all(f.jobs);
 const saved=f.db.get('caption:'+f.ws.deserializeAttachment().id+'_progress');assert.equal(saved.text,'10月9日 金曜日に終業式があります');assert.equal(saved.revision,2);assert.equal(calls,2);assert.equal(f.db.get('captionCount'),1);assert.equal(f.messages.filter(x=>x.type==='translation').length,2);
 await send('10月9日',0,true);assert.equal(calls,2);assert.equal(f.db.get('caption:'+saved.id).revision,2);
 await send(saved.text,3,false);await Promise.all(f.jobs);assert.equal(calls,2);assert.equal(f.db.get('caption:'+saved.id).revision,3);
});
await test('完了通知を再翻訳せず更新ごとの実費は重複なく数える',async()=>{
 const f=fixture('lesson','teacher');let calls=0;f.room.env.AI.run=async()=>{calls++;return {response:'{"en":"Tomorrow","pt":"Amanhã"}'};};const cap={type:'caption',id:'finish',text:'明日は',revision:0,continuing:true,final:true};await f.room.webSocketMessage(f.ws,JSON.stringify(cap));await Promise.all(f.jobs);await f.room.webSocketMessage(f.ws,JSON.stringify({...cap,revision:1,continuing:false}));await Promise.all(f.jobs);assert.equal(calls,1);const messages=f.messages.filter(x=>x.type==='translation');assert.equal(messages.at(-1).continuing,false);assert.equal(messages[0].usageId,messages[1].usageId);
 const db=new Map(),l=new UsageLedger({getItem:k=>db.get(k),setItem:(k,v)=>db.set(k,v)});l.begin('face',['ja','en']);l.caption({id:'same',at:1,usageId:'run1',final:true,status:'ready',usage:{inputTokens:10,outputTokens:1}});l.caption({id:'same',at:1,usageId:'run2',final:true,status:'ready',usage:{inputTokens:20,outputTokens:2}});l.caption({id:'same',at:1,usageId:'run2',final:true,status:'ready',usage:{inputTokens:20,outputTokens:2}});assert.equal(l.current.captionCount,1);assert.equal(l.current.attemptCount,2);assert.equal(l.current.inputTokens,30);
});
await test('発話開始から最初の表示までを測り更新と文字入力を混ぜない',()=>{
 const pcm=new Int16Array(16000);pcm.fill(1000,3200,8000);assert.equal(firstVoicedAt(pcm,10000),9200);assert.equal(firstVoicedAt(new Int16Array(16000),10000),null);
 const t={kind:'speech',revision:0,speechStartedAt:9200,speechEndedAt:9500,recognitionReadyAt:10000,sentAt:10010};assert.equal(latencyFromTiming(t,11000).firstDisplayMs,1800);assert.equal(latencyFromTiming({...t,revision:1},11000).firstDisplayMs,undefined);
 const db=new Map(),l=new UsageLedger({getItem:k=>db.get(k),setItem:(k,v)=>db.set(k,v)});l.begin('face',['ja']);l.timing('first',latencyFromTiming(t,11000));l.timing('second',latencyFromTiming({...t,revision:1},12000));const a=JSON.parse(analysisReport(l.list()));assert.equal(a.summary.p95FirstDisplayMs,1800);assert.equal(a.summary.firstDisplaySamples,1);
 assert.throws(()=>validateCaption({id:'x',text:'hello',revision:-1}));assert.throws(()=>validateCaption({id:'x',text:'hello',revision:1.5}));
});
await test('背景の会話準備は一つを再利用しマイクを起動せず接続を引き継ぐ',async()=>{
 const source=await readFile(new URL('../web/app.js',import.meta.url),'utf8');
 const pool=source.slice(source.indexOf('// Each inactive conversation'),source.indexOf('const roomPreparations='));
 let calls=0;const sockets=[],timers=new Map();let timer=0;
 class Socket{constructor(){this.readyState=0;this.sent=[];sockets.push(this);Promise.resolve().then(()=>{this.readyState=1;this.onopen();this.onmessage({data:JSON.stringify({type:'ready',id:'self',mode:'face'})});});}send(data){this.sent.push(JSON.parse(data));}close(){this.readyState=3;this.onclose?.();}}
 const scope={AbortController,pageClosing:false,document:{visibilityState:'visible'},Map,Promise,Date,Error,JSON,recordResource:()=>{},WebSocket:Socket,api:async()=>{calls++;return {id:'room'+calls,key:'key'};},token:async()=> 'token',config:{api:'https://example.test'},catalog:{languages:[{code:'ja',labelJa:'日本語'}]},speakingLanguage:()=> 'ja',sharedLanguage:()=> 'es',$:()=>({value:'数学'}),setTimeout:fn=>{timers.set(++timer,fn);return timer;},setInterval:fn=>{timers.set(++timer,fn);return timer;},clearTimeout:id=>timers.delete(id),clearInterval:id=>timers.delete(id)};
 const state=runInNewContext(pool+';({prepareConversation,takeConversation,warmConversation,preparedConversations,disposePreparation})',scope);
 const first=state.prepareConversation('face'),second=state.prepareConversation('face');assert.equal(first,second);const prepared=await first;assert.equal(calls,1);assert.equal(prepared.ws.readyState,1);assert.equal(prepared.messages[0].type,'ready');assert.equal(prepared.ws.sent[0].type,'auth');
 assert.equal(await state.takeConversation('face'),prepared);assert.equal(state.preparedConversations.size,0);assert.equal(timers.size,0);
 const replacement=await state.prepareConversation('face');assert.notEqual(replacement.room.id,prepared.room.id);assert.equal(calls,2);replacement.ws.close();assert.equal(state.preparedConversations.size,0);assert.equal(timers.size,0);
 prepared.ws.close();
});
await test('無人ルームは保存期限まで監視を休止する',async()=>{
 let scheduled;const expiry=Date.now()+86400000;const storage={get:async key=>key==='room'?{expires:expiry}:null,getAlarm:async()=>0,setAlarm:async value=>scheduled=value};
 await new TranslationRoom({storage,getWebSockets:()=>[]},{}).alarm();assert.equal(scheduled,expiry);
});
await test('期限切れ認証を閉じ次の有効期限だけを予約する',async()=>{
 let scheduled,closed=false;const now=Date.now(),expiry=now+86400000;let attachment={uid:'test',expires:now-10};const ws={deserializeAttachment:()=>attachment,serializeAttachment:a=>attachment=a,close:()=>closed=true};
 const storage={get:async key=>key==='room'?{expires:expiry}:null,getAlarm:async()=>0,setAlarm:async value=>scheduled=value};const r=new TranslationRoom({storage,getWebSockets:()=>[ws]},{});
 await r.alarm();assert.equal(closed,true);assert.equal(scheduled,expiry);attachment={uid:'test',expires:now+3600000};await r.scheduleAlarm();assert.equal(scheduled,attachment.expires);
});
await test('再接続は認証拒否と連続失敗とオフラインで停止する',async()=>{
 const {resourceFailure,mayReconnect}=await import('../web/resource-policy.js');assert.equal(resourceFailure(Error('Daily request limit exceeded')).reason,'quota');assert.equal(resourceFailure(Error('upstream timeout')),null);assert.equal(resourceFailure(Error('Exceeded allowed volume of requests in Durable Objects free tier.')).reason,'quota');
 assert.equal(mayReconnect(1008,1),false);assert.equal(mayReconnect(1006,6),false);assert.equal(mayReconnect(1006,1,false),false);assert.equal(mayReconnect(1006,1),true);
});
await test('ブラウザー認識は確定文だけ処理し日付と内容を同じ字幕へ更新する',async()=>{
 const {createBrowserRecognition}=await import('../web/caption-browser.js');assert.equal(createBrowserRecognition({language:'ja'}),null);
 let native;class Native{constructor(){native=this;}start(){}abort(){this.aborted=true;}}
 const Recognizer=createBrowserRecognition({language:'ja',Native});const r=new Recognizer(),events=[];r.onresult=e=>events.push(e);r.start();assert.equal(native.lang,'ja');
 const feed=(text,isFinal=true)=>{const row=[{transcript:text}];row.isFinal=isFinal;native.onresult({resultIndex:0,results:[row]});};
 feed('まだ途中',false);feed('ん');assert.equal(events.length,0);feed('10月9日');feed('金曜日に終業式があります');assert.equal(events.length,2);assert.equal(events[0].resultIndex,events[1].resultIndex);assert.equal(events[1].results[0][0].transcript,'10月9日 金曜日に終業式があります');assert.equal(events[1].speechEndedAt,undefined);r.abort();assert.equal(native.aborted,true);
});
await test('ブラウザー認識の失敗・停止後は古い結果を届けない',async()=>{
 const {createBrowserRecognition}=await import('../web/caption-browser.js');let native;class Native{constructor(){native=this;}start(){}abort(){}}
 const R=createBrowserRecognition({language:'es',Native}),r=new R();let error,results=0;r.onerror=e=>error=e;r.onresult=()=>results++;r.start();const callback=native.onresult;native.onerror({error:'network'});assert.equal(error.error,'service');callback({resultIndex:0,results:[Object.assign([{transcript:'hola'}],{isFinal:true})]});assert.equal(results,0);
});
await test('登録済みの逆方向訳と不足言語を区別し曖昧な辞書一致は使わない',async()=>{
 const {TranslationMemory}=await import('../web/translation-memory.js');const m=new TranslationMemory({getItem:()=>null,setItem(){}}),catalog={phrases:[{id:'a',jaText:'こんにちは',esText:'Hola',enText:'Hello'}]};assert.equal(m.lookup('es','Hola',['ja','en'],'',catalog).translations.ja,'こんにちは');const partial=m.lookup('es','Hola',['ja','pt'],'',catalog,true);assert.deepEqual(partial.missing,['pt']);catalog.phrases.push({id:'b',jaText:'やあ',esText:'Hola'});assert.equal(m.lookup('es','Hola',['ja'],'',catalog),null);
});
await test('対面の完了通知は処理中の訳を再課金せず同じ字幕へ反映する',async()=>{
 const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('const localJobs='),app.indexOf('const invite=new URLSearchParams'));
 let resolve,calls=0;const replies=[],records=new Map(),activeRoom={local:true,unit:''};const scope={Map,Set,Date,JSON,Error,AbortController,room:activeRoom,selfId:'local',sessionEpoch:1,records,catalog:{},pending:new Map(),$:selector=>({value:selector==='#face-other-language'?'es':'ja'}),translationMemory:{lookup:(source,text,targets)=>({translations:{[source]:text},missing:targets,source:'spreadsheet'})},api:()=>{calls++;return new Promise(r=>resolve=r);},message(){},ledger:{event(){},reuseLookup(){}},handle:async r=>{records.set(r.id,r);replies.push(r);}};
 runInNewContext(code+';this.translateLocally=translateLocally;this.cancelLocalTranslations=cancelLocalTranslations;',scope);
 const work=scope.translateLocally({id:'one',text:'10月9日',revision:0,continuing:true},'ja');await scope.translateLocally({id:'one',text:'10月9日',revision:1,metadataOnly:true},'ja');assert.equal(typeof resolve,'function',JSON.stringify(replies));resolve({translations:{ja:'10月9日',es:'9 de octubre'},usage:{inputTokens:10,outputTokens:3},latencyMs:100});await work;assert.equal(calls,1);assert.equal(replies.length,1);assert.equal(replies[0].continuing,false);assert.equal(replies[0].revision,1);
 const late=scope.translateLocally({id:'two',text:'火曜日',revision:0},'ja');scope.cancelLocalTranslations();scope.room=null;scope.sessionEpoch++;resolve({translations:{es:'martes'}});await late;assert.equal(replies.length,1);
});
await test('確認済み訳はホット150件から外れても端末DBの完全一致で取り出す',async()=>{
 const {TranslationMemory}=await import('../web/translation-memory.js');const {memoryKey}=await import('../web/reviewed-store.js');const db=new Map(),store={get:async k=>db.get(k)||null,put:async r=>{db.set(memoryKey(r.source,r.text,r.unit),structuredClone(r));return true;}};
 const m=new TranslationMemory({getItem:()=>null,setItem(){}},store);for(let i=0;i<180;i++)assert.equal(m.remember('ja','文'+i,{en:'Sentence '+i},'math'),true);await new Promise(r=>setTimeout(r,0));assert.equal(m.rows.length,150);assert.equal(db.size,180);const cold=[...db.values()].find(r=>!m.hot.has(memoryKey(r.source,r.text,r.unit)));assert(cold);assert.equal(m.lookup('ja',cold.text,['en'],'math'),null);const found=await m.lookupAsync('ja',cold.text,['en'],'math');assert.equal(found.translations.en,cold.translations.en);assert.equal(m.lookup('ja',cold.text,['en'],'other'),null);assert.equal(m.hot.has(memoryKey('ja',cold.text,'math')),true);assert.equal(m.rows.length,150);
});
await test('確認済み訳の保存は頻度と新しさを優先し件数とバイト数を制限する',async()=>{
 const {retainedRows}=await import('../web/reviewed-store.js'),now=Date.now();const rows=Array.from({length:5100},(_,i)=>({key:String(i),hits:0,lastUsed:now-i*86400000,text:'文'}));rows.push({key:'frequent',hits:1000,lastUsed:now-20*86400000});const kept=retainedRows(rows,now);assert.equal(kept.length,5000);assert(kept.some(r=>r.key==='frequent'));assert(!kept.some(r=>r.key==='5099'));const huge=retainedRows(Array.from({length:20},(_,i)=>({key:String(i),text:'a'.repeat(1000000),lastUsed:now})),now);assert(JSON.stringify(huge).length*2<16*1024*1024);
});
await test('端末DBが使えなくても確認済み訳と共有辞書は利用できる',async()=>{
 const {TranslationMemory}=await import('../web/translation-memory.js');const m=new TranslationMemory({getItem:()=>null,setItem(){throw Error('full');}},{get:async()=>null,put:async()=>false});assert.equal(m.remember('ja','保存した文',{en:'Reviewed'}),true);assert.equal((await m.lookupAsync('ja','保存した文',['en'])).translations.en,'Reviewed');assert.equal(await m.lookupAsync('ja','未登録',['en']),null);
});

await test('非発話の除外をネットワーク障害と誤診断しない',async()=>{
 const {safeConnectionRecord,explainConnection}=await import('../web/network.js');
 const r=safeConnectionRecord({stage:'browser_speech',operation:'transcribe',code:'filtered',filterReason:'nonverbal',endpoint:'',at:Date.now()});assert.equal(r.code,'filtered');assert.equal(r.filterReason,'nonverbal');const report=explainConnection([r],[],Date.now());assert(!JSON.stringify(report).includes('DNS解決・HTTPS'));
});
await test('ブラウザー認識のくしゃみは前後の字幕を結合しない',async()=>{
 const {createBrowserRecognition}=await import('../web/caption-browser.js');let native;class Native{constructor(){native=this;}start(){}abort(){}}
 const diagnostics=[],events=[];const R=createBrowserRecognition({language:'ja',Native,onDiagnostic:r=>diagnostics.push(r)}),r=new R();r.onresult=e=>events.push(e);r.start();const send=text=>{const row=[{transcript:text}];row.isFinal=true;native.onresult({resultIndex:0,results:[row]});};send('10月9日');send('ハックション！');send('はい');assert(diagnostics.some(d=>d.code==='filtered'&&d.filterReason==='nonverbal'));assert(!events.some(e=>e.results[e.resultIndex][0].transcript.includes('ハックション')));assert(!events.some(e=>e.results[e.resultIndex][0].transcript.includes('10月9日 はい')));assert(events.some(e=>e.results[e.resultIndex][0].transcript==='はい'));r.abort();
});
await test('背景停止は録音と待機処理を止め字幕と再利用を保持する',async()=>{
 const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('function pauseConversation('),app.indexOf("document.addEventListener('visibilitychange'"));
 let stopped=0,aborted=0,preserve=false;const button={setAttribute(k,v){this[k]=v;}},scope={idleWatch:{stop(){}},recordPause(){},room:{mode:'face'},mic:true,microphoneStarting:false,microphoneActivation:0,localJobs:new Map([['one',{}]]),localRequest:{},localStream:{getTracks:()=>[{stop(){stopped++;}}]},pending:new Map([['one',{}]]),localTimings:new Map([['one',{}]]),stopRecognition(){aborted++;},cancelLocalTranslations(v){preserve=v;scope.localJobs.clear();scope.localRequest=null;},ledger:{microphone(v){assert.equal(v,false);},event(){}},$:()=>button,paintButton(){},message(){}};
 runInNewContext(code+';this.pause=pauseConversation;',scope);scope.pause();assert.equal(scope.mic,false);assert.equal(scope.microphoneActivation,1);assert.equal(stopped,1);assert.equal(aborted,1);assert.equal(preserve,true);assert.equal(scope.pending.size,0);assert.equal(scope.localStream,null);assert.equal(button['aria-pressed'],'false');scope.room={mode:'lesson'};scope.mic=true;scope.pause();assert.equal(scope.mic,true);
});
await test('背景停止中の辞書検索完了はAIを送らず保存済みキャッシュを残す',async()=>{
 const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('const localJobs='),app.indexOf('const invite=new URLSearchParams'));let resolve,calls=0;const scope={Map,Set,Date,JSON,Error,AbortController,room:{local:true,unit:''},selfId:'local',sessionEpoch:1,records:new Map(),catalog:{},pending:new Map(),$:()=>({value:'en'}),translationMemory:{lookupAsync:()=>new Promise(r=>resolve=r)},api:()=>{calls++;},message(){},ledger:{event(){},reuseLookup(){}},handle:async()=>{throw Error('late display');}};
 runInNewContext(code+';this.translate=translateLocally;this.cancel=cancelLocalTranslations;this.cache=sessionTranslations;',scope);scope.cache.set('saved',{});const work=scope.translate({id:'one',text:'火曜日'},'ja');scope.cancel(true);resolve({translations:{ja:'火曜日'},missing:['en']});await work;assert.equal(calls,0);assert.equal(scope.cache.size,1);scope.cancel();assert.equal(scope.cache.size,0);
});
await test('通話の背景停止は中継・定期通信・再接続を閉じ同じルームを残す',async()=>{
 const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('function pauseConversation('),app.indexOf("document.addEventListener('visibilitychange'"));let closed=0,audioStopped=0,timers=0;const room={mode:'interpreter',id:'room'};const scope={idleWatch:{stop(){}},recordPause(){},room,mic:true,microphoneStarting:false,microphoneActivation:2,backgroundCallPaused:false,sessionEpoch:7,localJobs:new Map(),localRequest:null,localStream:{getTracks:()=>[{stop(){}}]},pending:new Map(),localTimings:new Map(),stopRecognition(){},cancelLocalTranslations(){},ledger:{microphone(){},event(){}},$:()=>({setAttribute(){},replaceChildren(){}}),paintButton(){},message(){},status(){},updateLiveActions(){},renderCallInvite(){},clearTimeout(){timers++;},clearInterval(){timers++;},reconnectTimer:1,authTimer:2,heartbeat:3,refreshTimer:4,metricsTimer:5,socket:{close(){closed++;}},peers:new Map([['peer',{pc:{close(){closed++;}},audio:{pause(){audioStopped++;},remove(){}}}]]),participants:[{}],turnRoomId:'room',callStarted:true};
 runInNewContext(code+';this.pause=pauseConversation;',scope);scope.pause();assert.equal(scope.backgroundCallPaused,true);assert.equal(scope.intentionalClose,true);assert.equal(scope.sessionEpoch,8);assert.equal(closed,2);assert.equal(audioStopped,1);assert.equal(timers,5);assert.equal(scope.socket,null);assert.equal(scope.peers.size,0);assert.equal(scope.pending.size,0);assert.equal(scope.room,room);assert.equal(scope.turnRoomId,null);assert.equal(scope.callStarted,true);
});
await test('通話の再開は明示的なマイク操作で接続し背景へ戻ったら録音しない',async()=>{
 const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf("$('#microphone').onclick="),app.indexOf('function stopRecognition('));let resolve,connected=0,recording=0,timers=0;const button={setAttribute(){}};const scope={idleWatch:{start(){},stop(){}},recordResume(){},room:{mode:'interpreter'},mic:false,microphoneStarting:false,microphoneActivation:0,sessionEpoch:1,backgroundCallPaused:true,intentionalClose:true,document:{visibilityState:'visible'},$:()=>button,paintButton(){},connect:()=>{connected++;return new Promise(r=>resolve=r);},startConnectionTimers(){timers++;},clearInterval(){},metricsTimer:null,setInterval(){return 1;},sampleRtc(){},ensureMicrophone:async()=>{scope.localStream={getAudioTracks:()=>[{enabled:false}]};},startRecognition(){recording++;},stopRecognition(){},ledger:{microphone(){},event(){}},message(){}};
 runInNewContext(code,scope);const first=button.onclick();assert.equal(connected,1);resolve();await first;assert.equal(recording,1);assert.equal(timers,1);assert.equal(scope.mic,true);
 scope.mic=false;scope.backgroundCallPaused=true;const second=button.onclick();scope.microphoneActivation++;scope.sessionEpoch++;scope.document.visibilityState='hidden';resolve();await second;assert.equal(recording,1);assert.equal(timers,1);assert.equal(scope.mic,false);
});
await test('無音と認識されない雑音は期限内に停止する',async()=>{
 const {idleState}=await import('../web/idle-watch.js');const state={started:1000,lastSpeech:0,lastVoice:0};assert.equal(idleState(state,105999),'active');assert.equal(idleState(state,106000),'warn');assert.equal(idleState(state,121000),'stop');assert.equal(idleState({...state,lastVoice:180999},181000),'stop');assert.equal(idleState({...state,lastSpeech:120000},121000),'active');
});
await test('予算はAI実行前に確保し未計測結果も消費として残す',async()=>{
 const {budgetOperation}=await import('../server/ai-budget.js');let data;const storage={transaction:async fn=>fn({get:async()=>structuredClone(data),put:async(k,v)=>{data=structuredClone(v);}})};const now=100000000;
 const first=await budgetOperation(storage,{action:'reserve',uid:'a',cost:10000},now);await budgetOperation(storage,{action:'settle',...first},now);assert.equal(data.total,10000);
 const second=await budgetOperation(storage,{action:'reserve',uid:'a',cost:10000},now);await assert.rejects(budgetOperation(storage,{action:'reserve',uid:'a',cost:1},now));await budgetOperation(storage,{action:'settle',...second,actual:100},now);assert.equal(data.total,10100);await budgetOperation(storage,{action:'block'},now);await assert.rejects(budgetOperation(storage,{action:'reserve',uid:'b',cost:1},now));await budgetOperation(storage,{action:'reserve',uid:'a',cost:1},now+86400000);assert.equal(data.total,1);
});
await test('利用者ごとのAI同時実行を2件に制限する',async()=>{
 const {budgetOperation}=await import('../server/ai-budget.js');let data;const storage={transaction:async fn=>fn({get:async()=>structuredClone(data),put:async(k,v)=>{data=structuredClone(v);}})};const a=await budgetOperation(storage,{action:'reserve',uid:'a',cost:10});await budgetOperation(storage,{action:'reserve',uid:'a',cost:10});await assert.rejects(budgetOperation(storage,{action:'reserve',uid:'a',cost:10}),e=>e.aiReason==='busy');await budgetOperation(storage,{action:'settle',...a,actual:10});await budgetOperation(storage,{action:'reserve',uid:'a',cost:10});
});
await test('辞書更新後に確認済みの古い別言語を混ぜない',async()=>{
 const {TranslationMemory}=await import('../web/translation-memory.js');const m=new TranslationMemory({getItem:()=>null,setItem(){}},{get:async()=>null,put:async()=>true});const first={revision:1},second={revision:2};m.lookup('ja','文',['en'],'',first);m.remember('ja','文',{en:'old',es:'viejo'});assert.equal(m.lookup('ja','文',['en'],'',first).translations.en,'old');assert.equal(m.lookup('ja','文',['en'],'',second),null);m.remember('ja','文',{en:'new'});assert.equal(m.lookup('ja','文',['es'],'',second),null);
});
await test('停止後の完了通信と再開後の新規通信を混ぜない',async()=>{
 const {recordResource,recordPause,recordResume,resourceSnapshot}=await import('../web/resource-usage.js');const rows=new Map(),storage={getItem:k=>rows.get(k),setItem:(k,v)=>rows.set(k,v)};recordPause('idle',storage);recordResource('translationComplete',storage);recordResume(storage);recordResource('translationRequest',storage);const report=resourceSnapshot(storage);assert.equal(report.pauses[0].after.translationComplete,1);assert.equal(report.pauses[0].after.translationRequest,undefined);assert.equal(report.counts.translationRequest,1);
});
await test('混雑・タイムアウトでは別の音声モデルを追加実行しない',async()=>{
 for(const code of [3040,3007,3036]){let calls=0;await assert.rejects(recognizeAudio({AI:{run:async()=>{calls++;throw Object.assign(Error('upstream failed'),{code});}}},new Uint8Array(encodeWav(new Int16Array(16000))),'ja'));assert.equal(calls,1);}
});
await test('退室した参加者の待機字幕をAIへ送らない',async()=>{
 const f=fixture('lesson','teacher');let calls=0;f.room.env.AI.run=async()=>{calls++;return {response:'{"en":"ok","pt":"ok"}'};};f.ws.deserializeAttachment().left=true;f.room.queuedCaptions.set('queued',{ws:f.ws,a:f.ws.deserializeAttachment(),room:f.db.get('room'),cap:{text:'test',revision:0},queuedAt:Date.now()});f.room.startCaptionJob('queued');await Promise.all(f.jobs);assert.equal(calls,0);
});
await test('アプリ内の制限をCloudflareが報告した上限と取り違えない',async()=>{
 const {budgetError}=await import('../server/ai-budget.js');const failure=aiFailure(budgetError());assert.equal(failure.reason,'quota');assert(!failure.message.includes('Cloudflare'));assert.equal(failure.evidence,'unclassified');
});

async function drainJobs(f){while(f.room.jobs.size||f.room.queuedCaptions.size)await Promise.all([...f.room.jobs.values()]);await Promise.all(f.jobs);}
await test('翻訳待ちを24件と実行2件に制限し同じ発話の最新版だけ待つ',async()=>{
 const f=fixture('lesson','teacher');let release,calls=0,active=0,max=0;const gate=new Promise(r=>release=r);f.room.env.AI.run=async()=>{calls++;active++;max=Math.max(max,active);await gate;active--;return {response:'{"en":"ok","pt":"ok"}'};};
 for(let i=0;i<30;i++)await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'bounded'+i,text:'試験文'+i,final:true}));
 assert.equal(calls,2);assert.equal(f.room.jobs.size,2);assert.equal(f.room.queuedCaptions.size,24);assert.equal(f.db.get('captionCount'),26);assert.equal(f.messages.filter(x=>x.type==='caption_rejected').length,4);
 await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'bounded2',text:'新しい試験文',revision:1,final:true}));assert.equal(f.room.queuedCaptions.size,24);release();await drainJobs(f);assert.equal(max,2);assert.equal(calls,26);assert.equal(f.db.get('caption:'+f.ws.deserializeAttachment().id+'_bounded2').text,'新しい試験文');
});
await test('同時に同じ発話を受けても保存数とAI実行は一回',async()=>{
 const f=fixture('lesson','teacher');let calls=0;f.room.env.AI.run=async()=>{calls++;return {response:'{"en":"ok","pt":"ok"}'};};const cap=JSON.stringify({type:'caption',id:'duplicate',text:'同時送信の試験',final:true});await Promise.all(Array.from({length:8},()=>f.room.webSocketMessage(f.ws,cap)));await drainJobs(f);assert.equal(calls,1);assert.equal(f.db.get('captionCount'),1);
});
await test('失敗した同じ発話の再送は保存結果を返し明示的な新版だけ再試行',async()=>{
 const f=fixture('lesson','teacher');let calls=0;f.room.env.AI.run=async()=>{calls++;throw Error('test failure');};const cap={type:'caption',id:'failure',text:'失敗再送の試験',final:true,revision:0};await f.room.webSocketMessage(f.ws,JSON.stringify(cap));await drainJobs(f);const first=f.messages.filter(x=>x.type==='translation').at(-1);await f.room.webSocketMessage(f.ws,JSON.stringify(cap));assert.equal(calls,1);assert.equal(f.messages.filter(x=>x.type==='translation').at(-1).usageId,first.usageId);await f.room.webSocketMessage(f.ws,JSON.stringify({...cap,revision:1}));await drainJobs(f);assert.equal(calls,2);
});
await test('期限切れ認証と15秒以上の待機仕事をAIへ渡さず通知する',async()=>{
 for(const expiredAuth of [false,true]){const f=fixture('lesson','teacher');let calls=0;f.room.env.AI.run=async()=>{calls++;return {};};if(expiredAuth)f.ws.deserializeAttachment().expires=Date.now()-1;f.room.queuedCaptions.set('stale',{ws:f.ws,a:f.ws.deserializeAttachment(),room:f.db.get('room'),cap:{text:'古い試験',revision:0},queuedAt:Date.now()-(expiredAuth?0:16000)});f.room.startCaptionJob('stale');await drainJobs(f);assert.equal(calls,0);assert.equal(f.messages.at(-1).type,'caption_rejected');}
});
await test('処理中に授業終了してもAI結果を配信せず開始済み使用量は保存',async()=>{
 const f=fixture('lesson','teacher');let release;f.room.env.AI.run=async()=>{await new Promise(r=>release=r);return {response:'{"en":"ok","pt":"ok"}',usage:{prompt_tokens:20,completion_tokens:2}};};await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',id:'late',text:'終了途中の試験',final:true}));await new Promise(r=>setTimeout(r,0));assert.equal(typeof release,'function');await f.room.webSocketMessage(f.ws,JSON.stringify({type:'end'}));release();await drainJobs(f);assert.equal(f.messages.filter(x=>x.type==='translation').length,0);const saved=f.db.get('caption:'+f.ws.deserializeAttachment().id+'_late');assert.equal(saved.usage.inputTokens,20);assert.equal(saved.status,'ready');
});
await test('再起動で実行状態が不明な発話を自動で二重実行しない',async()=>{
 const f=fixture('lesson','teacher');let calls=0;f.room.env.AI.run=async()=>{calls++;return {};};const cap={type:'caption',id:'orphan',text:'実行不明の試験',final:true,revision:0};f.db.set('caption:'+f.ws.deserializeAttachment().id+'_orphan',{...cap,id:f.ws.deserializeAttachment().id+'_orphan',status:'translating'});await f.room.webSocketMessage(f.ws,JSON.stringify(cap));assert.equal(calls,0);assert.equal(f.messages.at(-1).status,'failed');assert(f.messages.at(-1).error.includes('完了を確認できません'));
});
await test('予算確保を待つ間に停止した処理はAI実行直前にも拒否する',async()=>{
 let active=true,calls=0;const actions=[];const env={executionValid:()=>active,budgetUid:'user',AI:{run:async()=>{calls++;return {}; }},ROOMS:{idFromName:x=>x,get:()=>({fetch:async r=>{const data=await r.json();actions.push(data.action);if(data.action==='reserve')active=false;return new Response(JSON.stringify({id:'lease',day:1,reserved:10}));}})}};await assert.rejects(runAi(env,'@cf/google/gemma-4-26b-a4b-it',{messages:[],max_completion_tokens:128}));assert.equal(calls,0);assert.deepEqual(actions,['reserve','settle']);
});
await test('遅れた認証更新が別ルームのソケットへ送信されない',async()=>{
 const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('function startConnectionTimers('),app.indexOf('async function connect('));let callback,resolve,sends=0;const old={readyState:1};const scope={backgroundCallPaused:false,socket:old,sessionEpoch:1,refreshTimer:null,heartbeat:null,clearInterval(){},setInterval:fn=>{callback??=fn;return 1;},user:{getIdToken:()=>new Promise(r=>resolve=r)},send:()=>sends++,message(){}};runInNewContext(code+';this.start=startConnectionTimers;',scope);scope.start();const pending=callback();scope.socket={readyState:1};scope.sessionEpoch++;resolve('refreshed');await pending;assert.equal(sends,0);
});

await test('生徒の確定文字入力は配信できる・途中字幕は拒否',async()=>{const f=fixture();for(const flags of [{final:false},{final:true,continuing:true},{final:true,metadataOnly:true}])await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',kind:'text',id:'blocked',text:'質問です',...flags}));assert.equal(f.jobs.length,0);await f.room.webSocketMessage(f.ws,JSON.stringify({type:'caption',kind:'text',id:'question',text:'xは3です',final:true}));await Promise.all(f.jobs);assert.equal(f.messages.find(m=>m.type==='translation').status,'ready');});
await test('生徒の入室を待つ間に戻った場合、遅い成功も失敗も画面を変えない',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('let joiningLesson='),app.indexOf("$('#join-lesson-form').onsubmit"));for(const fail of [false,true]){const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{value:id==='#lesson-code-input'?'1234':'',disabled:false,textContent:''});return nodes.get(id);};let resolve,reject,entered=0,exited=0;const scope={sessionEpoch:1,lessonSelectionEpoch:1,lessonRole:'student',tab:'lesson',$:node,api:()=>new Promise((a,b)=>{resolve=a;reject=b}),enter:async()=>entered++,exitModeFullscreen:async()=>exited++,showConnectionError(){}};runInNewContext(code,scope);const pending=scope.joinLesson();scope.lessonSelectionEpoch++;scope.lessonRole=null;if(fail)reject(Error('late failure'));else resolve({mode:'lesson'});await pending;assert.equal(entered,0);assert.equal(exited,0);assert.equal(node('#join-lesson').disabled,false);}});
await test('生徒・先生・通訳の切替でも入力を復元し、生徒の戻る操作は一つ',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('function updateLiveActions('),app.indexOf("$('#modal-close')"));const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,{hidden:true,setAttribute(){}});return nodes.get(id);};const scope={$:node,room:{mode:'lesson'},role:'guest',lessonRole:'student',callStarted:false,paintButton:(n,text)=>n.text=text};runInNewContext(code,scope);scope.updateLiveActions();assert.equal(node('#leave').hidden,true);assert.equal(node('#text-form').hidden,false);assert.equal(node('#text-toggle').hidden,false);assert.equal(node('#microphone').hidden,true);scope.role='teacher';scope.lessonRole='teacher';scope.updateLiveActions();assert.equal(node('#leave').text,'授業をおわる');scope.room={mode:'face'};scope.updateLiveActions();assert.equal(node('#microphone').hidden,false);assert.equal(node('#text-form').hidden,false);});
await test('前のルームの退室待ち中に戻っても授業へ入らない',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('async function enter('),app.indexOf('function startConnectionTimers('));let resolve,enabled=0,disposed=0;const scope={lessonSelectionEpoch:1,tab:'lesson',room:{mode:'face'},socket:null,leave:()=>new Promise(r=>resolve=r),disposePreparation:()=>disposed++,enableConversationControls:()=>enabled++};runInNewContext(code,scope);const pending=scope.enter({mode:'lesson'});scope.lessonSelectionEpoch++;resolve();await pending;assert.equal(enabled,0);assert.equal(disposed,1);});
await test('翻訳内訳は成功・失敗とも記録し、本文を含まず未計測をnullにする',async()=>{let usage;const env={AI:{run:async()=>({response:'{"en":"Hello"}',usage:{prompt_tokens:10,completion_tokens:2}})}};await translateText(env,'計測専用の挨拶','ja',['en'],[],'',{glossary:[],phrases:[]},u=>usage=u);assert.ok(usage.translationTiming.providerMs>=0);assert.ok(usage.translationTiming.aiTotalMs>=usage.translationTiming.providerMs);assert.ok(usage.translationTiming.dictionaryMs>=0);const data=new Map(),ledger=new UsageLedger({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)});ledger.begin('lesson',['ja','en']);ledger.caption({id:'one',at:1,final:true,status:'ready',usage});ledger.caption({id:'two',at:2,final:true,status:'failed',usage:{translationTiming:{providerMs:null,dictionaryMs:0,secret:'private'}}});const report=JSON.parse(analysisReport(ledger.list()));assert.equal(report.build,'20261009-mobile-speaker-1');assert.equal(report.sessions[0].build,report.build);assert.equal(report.sessions[0].translationTimings[0].queueMs,null);assert.equal(report.sessions[0].translationTimings[1].providerMs,null);assert.ok(!JSON.stringify(report).includes('private'));await assert.rejects(translateText({AI:{run:async()=>{throw Error('failure')}}},'計測専用の挨拶','ja',['en'],[],'',{glossary:[],phrases:[]},u=>usage=u));assert.ok(usage.translationTiming.providerMs>=0);assert.ok(usage.translationTiming.aiTotalMs>=0);});
await test('授業番号の形式・未登録・期限切れを構造化して区別する',async()=>{const {LessonCodes}=await import('../server/lesson-codes.js');const codes=new LessonCodes({get:async k=>k==='code:1234'?{expires:10}:undefined},()=>20);for(const [value,errorCode]of [['x','lesson_code_invalid'],['9999','lesson_code_not_found'],['1234','lesson_code_expired']])await assert.rejects(codes.lookup(value),e=>e.errorCode===errorCode);let recorded;await assert.rejects(requestJson('https://example.test',{},{fetcher:async()=>new Response(JSON.stringify({error:'期限切れ',errorCode:'lesson_code_expired'}),{status:400}),onFailure:r=>recorded=r}),e=>e.errorCode==='lesson_code_expired');assert.equal(recorded.errorCode,'lesson_code_expired');});
await test('翻訳確認は数字の順序・全角・桁区切りを許容し欠落と否定を確認する',async()=>{const {inspectTranslations:q}=await import('../web/translation-quality.js');assert.equal(q('問１から５、1000円','ja',['en'],{en:'1000 yen; questions 5 and 1'}).warnings.length,0);assert.equal(q('1000円','ja',['en'],{en:'1,000 yen'}).warnings.length,0);assert.equal(q('問1から5','ja',['en'],{en:'Questions 1 to 6'}).warnings[0].code,'number_mismatch');assert.equal(q('弁当は必要ありません','ja',['en'],{en:'Lunch is required'}).warnings[0].code,'negation_check');assert.equal(q('弁当は必要ありません','ja',['en'],{en:'Lunch is not required'}).warnings.length,0);assert.equal(q('問1','ja',['en'],{en:'Question one'}).unmeasuredLanguages.length,1);assert.equal(q('こんにちは','ja',['pt'],{}).warnings[0].code,'missing_translation');assert.equal(q('禁止','ja',['ko'],{ko:'금지'}).unmeasuredLanguages.length,1);});
await test('翻訳確認統計は重複配信を除外し本文を保存しない',async()=>{const data=new Map(),l=new UsageLedger({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)});l.begin('face',['ja','en']);const r={id:'q',at:1,final:true,status:'ready',quality:{version:1,warnings:[{code:'number_mismatch',text:'SECRET'}],unmeasuredLanguages:[]},text:'SECRET'};l.caption(r);l.caption(r);assert.equal(l.current.qualityChecks.warningAttempts,1);assert(!JSON.stringify(l.list()).includes('SECRET'));});
await test('翻訳確認は負数の符号と日本語の残存を確認する',async()=>{const {inspectTranslations:q}=await import('../web/translation-quality.js');assert.equal(q('−3です','ja',['en'],{en:'It is 3.'}).warnings[0].code,'number_mismatch');assert.equal(q('問1から5','ja',['pt'],{pt:'Resolva do 問1 ao 問5.'}).warnings[0].code,'source_script_remaining');assert.equal(q('問1から5','ja',['pt'],{pt:'Resolva as questões 1 a 5.'}).warnings.length,0);});
await test('翻訳内訳は予算確保・応答・精算・解析を成功と解析失敗で分ける',async()=>{
 let usage,calls=0;const env={AI:{run:async()=>{calls++;return {response:'{"en":"hello"}',usage:{prompt_tokens:10,completion_tokens:2}};}},ROOMS:{idFromName:x=>x,get:()=>({fetch:async r=>{const d=await r.json();return new Response(JSON.stringify(d.action==='reserve'?{id:'lease',day:1,reserved:10}:{ok:true}));}})}};
 await translateText(env,'独立した計測試験','ja',['en'],[],'',{glossary:[],phrases:[]},u=>usage=u);for(const k of ['budgetWaitMs','providerMs','budgetSettleMs','parseMs'])assert.ok(Number.isFinite(usage.translationTiming[k]));assert.equal(calls,1);
 env.AI.run=async()=>({response:'invalid'});await assert.rejects(translateText(env,'独立した計測試験','ja',['en'],[],'',{glossary:[],phrases:[]},u=>usage=u));assert.ok(Number.isFinite(usage.translationTiming.parseMs));
 const {translationTimingSummary}=await import('../web/usage.js');const summary=translationTimingSummary([{translationTimings:[{providerMs:100,clientQueueMs:0},{providerMs:null,clientQueueMs:null},{providerMs:NaN}]}]);assert.equal(summary.providerMs.samples,1);assert.equal(summary.providerMs.p95Ms,100);assert.equal(summary.clientQueueMs.samples,1);assert.equal(summary.authMs.p95Ms,null);
});
await test('字幕単位の再試行は連打・古いrevision・退室・背景・言語変更を拒否する',async()=>{
 const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('function appendTranslationRetry('),app.indexOf('function showTranslationFailure('));
 for(const scenario of ['normal','stale','left','background','language','quota']){
 let sent=0,button;const data={id:'self_one',text:'原文',source:'ja',speaker:'自分',status:'failed',revision:2,...(scenario==='quota'?{aiFailure:{reason:'quota'}}:{})},active={mode:'lesson'},record={...data};const records=new Map([[data.id,record]]);const scope={selfId:'self',room:active,sessionEpoch:1,records,pending:new Map(),backgroundCallPaused:false,document:{visibilityState:'visible'},currentSource:()=>scenario==='language'?'en':'ja',el:()=>button={append(){},setAttribute(){}},localTimings:new Map(),ledger:{event(){}},message(){},submitCaption:cap=>{sent++;assert.equal(cap.kind,'text');assert.equal(cap.revision,3);assert.equal(cap.text,'原文');records.set(data.id,{...record,status:'translating'});}};runInNewContext(code,scope);scope.appendTranslationRetry({append(){}},data);if(scenario==='quota'){assert.equal(button,undefined);continue;}if(scenario==='stale')record.revision=4;if(scenario==='left')scope.room={mode:'lesson'};if(scenario==='background')scope.document.visibilityState='hidden';button.onclick();button.onclick();assert.equal(sent,scenario==='normal'?1:0);
 }
});
await test('キャッシュ再利用では過去のAI処理時間を今回の観測値にしない',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8');assert.ok(app.includes("if(result)result={...result,usage:{inputTokens:0,outputTokens:0,cacheHit:true},latencyMs:0}"));const data=new Map(),l=new UsageLedger({getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)});l.begin('face',['ja','en']);l.caption({id:'cache',at:1,final:true,status:'ready',usage:{cacheHit:true,translationTiming:{clientQueueMs:0,clientLookupMs:3,clientRequestMs:null}}});assert.equal(l.current.translationTimings[0].providerMs,null);assert.equal(l.current.translationTimings[0].clientQueueMs,0);});
await test('失敗した原文と文単位の再試行は通訳・通話・授業の各画面で残る',async()=>{
 const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),render=app.slice(app.indexOf('function renderCaption('),app.indexOf('function setTextComposer(')),retry=app.slice(app.indexOf('function appendTranslationRetry('),app.indexOf('function showTranslationFailure('));
 for(const mode of ['face','interpreter','lesson']){
 const node=(tag,text,cls)=>({tag,text,textContent:text,children:[],className:cls,style:{},append(...nodes){this.children.push(...nodes);},replaceChildren(...nodes){this.children=nodes;},setAttribute(){},querySelector(){return {};}}),captions=node('section');Object.assign(captions,{scrollHeight:0,scrollTop:0,clientHeight:100});const records=new Map(),elements=new Map();const scope={room:{mode},selfId:'self',sessionEpoch:1,backgroundCallPaused:false,records,elements,sharedLanguage:()=> 'en',callCaptionLanguages:()=>['en'],isDisplayableCaption:()=>false,$:id=>id==='#captions'?captions:id==='#captions .empty'?null:{value:id==='#face-other-language'?'pt':'ja'},el:node,speechControls:()=>node('div'),catalog:{languages:[]},qualityMessage:()=>'',updateSpeechControls(){},pending:new Map()};runInNewContext(retry+render,scope);scope.renderCaption({id:'self_fail',text:'失敗した原文',source:'ja',speaker:'自分',status:'failed',revision:0,final:true,translations:{ja:'失敗した原文'},aiFailure:{reason:'service'}});assert.equal(captions.children.length,1);const flatten=n=>[n,...n.children.flatMap(flatten)],nodes=flatten(captions);assert(nodes.some(n=>n.tag==='p'&&n.text==='失敗した原文'));assert(nodes.some(n=>n.tag==='button'&&n.text==='この文を再試行'));assert.equal(records.get('self_fail').status,'failed');
 }
});

await test('停止の範囲を区別し古い履歴は未計測とする',async()=>{const {recordPause,recordResource,recordResume,resourceSnapshot}=await import('../web/resource-usage.js');const rows=new Map(),storage={getItem:k=>rows.get(k),setItem:(k,v)=>rows.set(k,v)};recordPause('manual',storage,{mode:'interpreter',scope:'microphone'});recordResource('heartbeat',storage);recordResume(storage);recordPause('background',storage,{mode:'interpreter',scope:'conversation'});const report=resourceSnapshot(storage);assert.equal(report.pauses[0].scope,'microphone');assert.equal(report.pauses[0].mode,'interpreter');assert.equal(report.pauses[0].after.heartbeat,1);assert.equal(report.pauses[1].scope,'conversation');const saved=JSON.parse(rows.values().next().value);saved.pauses[0].resumedAt=1;saved.pauses[1].resumedAt=2;rows.set('tsuyaku-resource-v1',JSON.stringify(saved));recordResume(storage);assert.equal(resourceSnapshot(storage).pauses[1].resumedAt,2);});
await test('通話復元は同じタブ内・期限内のルームのみ保持し招待URLを残さない',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8');const code=app.slice(app.indexOf('function rememberCall('),app.indexOf('function readCallResume('))+app.slice(app.indexOf('function readCallResume('),app.indexOf('function readCallResume(')+app.slice(app.indexOf('function readCallResume(')).indexOf('return null;}')+13);const rows=new Map(),scope={sessionStorage:{getItem:k=>rows.get(k),setItem:(k,v)=>rows.set(k,v),removeItem:k=>rows.delete(k)},room:{id:'a'.repeat(32),key:'b'.repeat(32),mode:'interpreter',creator:true,expires:Date.now()+60000},callStarted:true};runInNewContext(code,scope);scope.rememberCall();const r=scope.readCallResume();assert.equal(r.resumePaused,true);assert.equal(r.creator,true);assert.equal(r.callStarted,true);assert.equal(r.id,scope.room.id);scope.room.expires=Date.now()-1;scope.rememberCall();assert.equal(scope.readCallResume(),null);assert.equal(rows.size,0);assert(app.includes("history.replaceState(null,'',location.pathname+location.search)"));assert(!app.includes("location.pathname:'#room='"));});
await test('音声認識の急な切替は最後の一回だけ起動し停止・退室で取り消す',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8');const code=app.slice(app.indexOf('function startRecognition(fallback'),app.indexOf('function startRecognitionNow('));let task,starts=0;const scope={room:{mode:'face'},sessionEpoch:1,microphoneActivation:1,pageClosing:false,backgroundCallPaused:false,stopRecognition(){task=null;},setTimeout:f=>(task=f,1),startRecognitionNow(){starts++;}};runInNewContext(code,scope);scope.startRecognition();scope.startRecognition();task();assert.equal(starts,1);scope.startRecognition();scope.sessionEpoch++;task();assert.equal(starts,1);scope.startRecognition();scope.backgroundCallPaused=true;task();assert.equal(starts,1);});
await test('一時保存ページでは退室せず通常の終了では解放する',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),start=app.indexOf("window.addEventListener('pagehide',event=>"),end=app.indexOf(";",app.indexOf("void leave(false);",start))+4;const handlers=[];let leaves=0,paused=0;const scope={window:{addEventListener:(n,f)=>handlers.push(f)},room:{mode:'interpreter'},suspendBackgroundInterpretation(){paused++;},preparedConversations:new Map(),ledger:{end(){}},leave(){leaves++;}};runInNewContext(app.slice(start,end),scope);handlers[0]({persisted:true});assert.equal(paused,1);assert.equal(leaves,0);handlers[0]({persisted:false});assert.equal(leaves,1);});
await test('復元した通話は招待エリアと対面用コントロールを表示しない',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8');assert(app.includes("clearInterval(metricsTimer);updateFace();$('#microphone').hidden=false"));const code=app.slice(app.indexOf('function renderCallInvite('),app.indexOf('function appendTranslationRetry('));for(const scenario of ['paused','started','waiting']){const n={hidden:false,dataset:{room:'room'},replaceChildren(){}};const scope={tab:'interpreter',room:{id:'room',mode:'interpreter',creator:true},backgroundCallPaused:scenario==='paused',callStarted:scenario==='started',$:()=>n};runInNewContext(code,scope);scope.renderCallInvite();assert.equal(n.hidden,scenario!=='waiting');}});

await test('ブラウザーの一時中断と通常終了は一度だけ復旧通知し有料認識エラーにしない',async()=>{const {createBrowserRecognition}=await import('../web/caption-browser.js');let native;class Native{constructor(){native=this;}start(){}abort(){}}const R=createBrowserRecognition({language:'ja',Native}),r=new R();let ends=0,errors=0;r.onend=()=>ends++;r.onerror=()=>errors++;r.start();native.onerror({error:'aborted'});native.onend();assert.equal(ends,1);assert.equal(errors,0);r.start();native.onend();assert.equal(ends,2);r.start();const end=native.onend;r.abort();end();assert.equal(ends,2);});
await test('通話ルームの更新確認は取得前と再読み込み直前に抑止する',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('async function checkForAppUpdate('),app.indexOf('setInterval(()=>void checkForAppUpdate'));let requests=0;const scope={checkingRelease:false,document:{visibilityState:'visible'},mic:false,$:()=>({value:''}),records:new Map(),participants:[],selfId:'self',room:{local:false,creator:true},fetch:()=>requests++};runInNewContext(code,scope);await scope.checkForAppUpdate();assert.equal(requests,0);assert.equal((code.match(/room&&!room.local/g)||[]).length,2);});


await test('音声の受信offerへanswerを送信し退室中の遅い応答は送らない',async()=>{const app=await readFile(new URL('../web/app.js',import.meta.url),'utf8'),code=app.slice(app.indexOf('async function signal(id,data)'),app.indexOf('async function ensureMicrophone()'));for(const stale of [false,true]){let resolve;const messages=[],errors=[];const pc={signalingState:'stable',setRemoteDescription:()=>stale?new Promise(r=>resolve=r):Promise.resolve(),createAnswer:async()=>({type:'answer',sdp:'test'}),async setLocalDescription(d){this.localDescription=d;}};const p={pc,ice:[]};const scope={room:{mode:'interpreter'},sessionEpoch:1,backgroundCallPaused:false,pageClosing:false,selfId:'z',role:null,peers:new Map([['a',p]]),peer:()=>p,send:m=>messages.push(m),ledger:{event:e=>errors.push(e)},message:e=>errors.push(e)};runInNewContext(code,scope);const pending=scope.signal('a',{description:{type:'offer',sdp:'test'}});if(stale){scope.sessionEpoch++;resolve();}await pending;assert.equal(errors.length,0);assert.equal(messages.length,stale?0:1);if(!stale)assert.equal(messages[0].signal.description.type,'answer');}});
await test('字幕成功や新しい空セッションがあっても直近の音声失敗を診断に出す',()=>{const now=1000000,sessions=[{startedAt:now-10000,updatedAt:now,events:[]},{startedAt:now-90000,updatedAt:now-20000,captionCount:6,latencies:[861],events:[{type:'rtc_failed'},{type:'rtc_failed'}]}];const r=explainConnection([{at:now-80000,stage:'turn',operation:'turn_credentials',code:'ok'}],{now,sessions,authentication:'ready'});assert(r.facts.some(s=>s.includes('音声通話の接続失敗 2回')));assert(r.candidates.some(s=>s.cause.includes('音声通話')));assert.equal(r.sessionResults[1].rtcFailureCount,2);const old=explainConnection([],{now:now+400000,sessions});assert(!old.candidates.some(s=>s.cause.includes('音声通話')));});

console.log(count+' tests passed');


