import {PRICES,costOf,percentile,analysisReport} from './usage.js';
import {listHistory} from './history.js';
import {csv} from './core.js';
export function installAdmin({button,modal,el,ledger,download,currentRecords,message}){
 if(!button)return;
 let unlocked=false;
 const money=(n,fx)=>'約 '+(n*fx).toFixed(4)+'円 / $'+n.toFixed(6);
 button.onclick=()=>{if(unlocked){void dashboard();return;}const form=el('form'),input=el('input'),label=el('label','管理者パスワード'),error=el('p');input.type='password';input.autocomplete='off';input.required=true;label.append(input);const submit=el('button','表示する');submit.type='submit';form.append(label,submit,error);form.onsubmit=e=>{e.preventDefault();if(input.value!=='1111'){error.textContent='パスワードを確認してください。';return;}unlocked=true;void dashboard();};modal('管理者',form);input.focus();};
 async function dashboard(){ledger.save();const n=el('div',undefined,'admin-panel');const fx=el('input');fx.type='number';fx.min='1';fx.max='1000';fx.step='.01';fx.value=localStorage.getItem('tsuyaku-usd-jpy')||'150';const fxLabel=el('label','換算設定（円 / USD）');fxLabel.append(fx);n.append(el('p','この端末の利用履歴と、無料枠適用前の変動費の目安です。パスワードは画面を開くための端末内の確認です。'),fxLabel);const summary=el('div',undefined,'admin-summary'),history=el('div',undefined,'admin-history');n.append(summary,el('h3','1回ごとの利用'),history);
 const rows=ledger.list();function exchange(){return Math.min(1000,Math.max(1,Number(fx.value)||150));}function render(){const rate=exchange();localStorage.setItem('tsuyaku-usd-jpy',String(rate));const total=rows.reduce((t,s)=>t+costOf(s,s.priceSnapshot||PRICES).total,0);summary.replaceChildren(el('strong',rows.length+'回・'+money(total,rate)),el('p','翻訳 P95：'+(percentile(rows.flatMap(s=>s.latencies),.95)===null?'未計測':(percentile(rows.flatMap(s=>s.latencies),.95)/1000).toFixed(2)+'秒')));history.replaceChildren();if(!rows.length)history.append(el('p','利用履歴はまだありません。次の参加から記録します。'));for(const s of rows){const card=el('details'),title=el('summary',new Date(s.startedAt).toLocaleString('ja-JP')+'・'+(s.mode==='lesson'?'授業':'通訳')+'・'+money(costOf(s,s.priceSnapshot||PRICES).total,rate)),c=costOf(s,s.priceSnapshot||PRICES);card.append(title,el('p',Math.round(s.durationSeconds)+'秒・'+s.captionCount+'文・未成功 '+s.failedCaptions+'文・試行 '+s.attemptCount+'回'+(s.ended?'':'・参加中または終了記録なし')),el('p','翻訳 '+money(c.translation,rate)+' / 音声認識 '+money(c.recognition,rate)+' / 中継 '+money(c.turn,rate)),el('p','入力 '+s.inputTokens+' / 出力 '+s.outputTokens+' tokens・推定 '+s.estimatedTokenCalls+'回・未計測 '+s.unmeasuredCalls+'回'),el('p','音声認識 '+(s.streamSeconds+s.whisperSeconds).toFixed(1)+'秒・中継 '+(s.relayBytes/1e6).toFixed(3)+'MB・最大ジッター '+s.maxJitterMs.toFixed(1)+'ms'));history.append(card);}}
 fx.onchange=render;render();n.append(el('h3','改善用の分析出力'));const include=el('input');include.type='checkbox';const includeLabel=el('label','発言・訳の例も含める（現在の字幕と保存済み履歴）');includeLabel.className='admin-check';includeLabel.prepend(include);n.append(includeLabel);const report=el('textarea');report.rows=12;report.readOnly=true;report.setAttribute('aria-label','改善用の分析結果');const output=el('button','分析を作る'),copy=el('button','分析をコピー'),json=el('button','JSONを保存'),saveCSV=el('button','利用履歴CSV');n.append(output,copy,json,saveCSV,report);
 output.onclick=async()=>{ledger.save();let transcripts=[];if(include.checked){const saved=await listHistory();transcripts=[...new Map([...saved.flatMap(s=>s.records||[]),...currentRecords()].filter(r=>r.final).map(r=>[r.id,r])).values()].slice(-200).map(r=>({source:r.source,text:r.text,translations:r.translations,status:r.status,latencyMs:r.latencyMs}));}report.value=analysisReport(ledger.list(),{exchange:exchange(),transcripts});};copy.onclick=async()=>{if(!report.value)await output.onclick();try{await navigator.clipboard.writeText(report.value);copy.textContent='コピーしました';}catch{report.focus();report.select();message('分析欄を選択しました。コピーして、このチャットへ貼り付けてください。');}};json.onclick=async()=>{if(!report.value)await output.onclick();download('通訳君_分析.json',report.value,'application/json');};saveCSV.onclick=()=>download('通訳君_利用履歴.csv',csv([['開始','モード','秒','文数','未成功','試行','翻訳P95ms','推定USD','推定円','未計測回数'],...ledger.list().map(s=>{const c=costOf(s,s.priceSnapshot||PRICES).total;return [new Date(s.startedAt).toISOString(),s.mode,s.durationSeconds,s.captionCount,s.failedCaptions,s.attemptCount,percentile(s.latencies,.95),c,c*exchange(),s.unmeasuredCalls];})]));
 const note=el('details');note.append(el('summary','料金計算と履歴の説明'),el('p','確認日 '+PRICES.checkedAt+'。Gemma 入力 $0.10 / 出力 $0.30（各100万tokens）、Nova-3 WebSocket $0.0092/分、Whisper $0.000513/分、TURN $0.05/GB。token数が返らない場合は文字量から推定します。失敗や再試行も記録します。TURNは選択された中継経路の送受信量による推定です。'),el('p','固定費、サーバー処理・共有保存、無料枠、他の端末の音声認識費用は含みません。Cloudflare全体の請求額とは異なります。履歴はこの端末に最大200回、発言本文は「履歴を保存」した場合のみ残します。'));for(const [name,url]of[['AI料金表','https://developers.cloudflare.com/workers-ai/platform/pricing/'],['TURN料金表','https://developers.cloudflare.com/realtime/sfu/pricing/']]){const a=el('a',name);a.href=url;a.target='_blank';a.rel='noopener';note.append(a,el('br'));}n.append(note);if(ledger.storageError)n.append(el('p','端末の保存領域に書き込めません。分析を保存してください。'));const logout=el('button','管理者表示を閉じて認証解除');logout.onclick=()=>{unlocked=false;document.querySelector('#modal').close();};n.append(logout);modal('管理者・利用料金と分析',n);
 }
}
