// Keep Safari pinch gestures from changing the app scale; scrolling remains available.
for (const type of ['gesturestart','gesturechange']) document.addEventListener(type,event=>event.preventDefault(),{passive:false});
import {UsageLedger} from './usage.js?v=20261006-school-1';
import {SpeechPlayer} from './speech-player.js?v=20261006-playback-2';
import {latencyFromTiming,retryDelay} from './diagnostics.js?v=20261006-telemetry-1';
import {installAdmin} from './admin.js?v=20261006-network-2';
import {config} from './config.js';
import {ConnectionDiary,connectionFailure,requestJson,probeNetwork,explainConnection} from './network.js?v=20261006-network-2';
import {catalog as seed} from '../server/catalog.js';
import {translationOf} from './core.js?v=20261006-school-1';
import {speakerCaption,speakerInfo} from './face-mode.js?v=20261006-school-1';
import {callCaptionLanguages,isDisplayableCaption} from './call-mode.js?v=20261006-call-1';
import {listHistory} from './history.js?v=20261006-school-1';
import {createStreamingRecognition} from './caption-stream.js?v=20261006-telemetry-1';
import {createServerRecognition} from './caption-server.js?v=20261006-telemetry-1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let catalog=seed,authApi,user,socket,room,selfId,role,localStream,recognition,restarting=false,sessionEpoch=0,mic=false,participants=[],tab='interpreter',intentionalClose=false,refreshTimer,reconnectTimer,heartbeat;
let roomExpiryTimer;let faceSide='self';let reconnectAttempts=0,recoveryStartedAt=null,connectedAt=null,authTimer;const localTimings=new Map();
const peers=new Map(),records=new Map(),elements=new Map(),pending=new Map();let turnReady=Promise.resolve(),rtcConfig={iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]};
const ledger=new UsageLedger(localStorage),connections=new ConnectionDiary(localStorage);let metricsTimer;
const message=text=>{$('#message').textContent=text;};
installAdmin({button:$('#admin'),modal,el,ledger,download,currentRecords:()=>[...records.values()],connectionHistory:()=>connections.list(),connectionAnalysis:()=>explainConnection(connections.list(),{authentication:user?'ready':'unavailable',online:navigator.onLine}),checkConnection:showNetworkDiagnostics,message});
const status=text=>{$('#connection').textContent=text;};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;if(tag==='button'&&text){const icons={'接続を確認':'network-wired','再試行':'rotate-right','リンクをコピー':'copy','ひらく':'book-open','候補として送る':'plus','授業を終了する':'stop','自分だけ退室する':'door-open'};if(icons[text])n.prepend(icon(icons[text]));}return n;}
function modal(title,content){delete $('#modal').dataset.kind;$('#modal-title').textContent=title;$('#modal-body').replaceChildren(content);$('#modal').showModal();}
$('#modal-close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close();};
function label(text,input){const n=el('label',text);n.append(input);return n;}
function options(select,selected){select.replaceChildren(...catalog.languages.map(l=>{const o=el('option',l.labelJa+' / '+l.labelNative);o.value=l.code;return o;}));select.value=selected;}
const sharedLanguageIds=['source-language','lesson-language','face-other-language','teacher-view-language','phrase-language','term-language'];
function sharedLanguage(){const value=localStorage.getItem('tsuyaku-display-language')||localStorage.getItem('view-language')||localStorage.getItem('face-other-language')||'pt';return catalog.languages.some(l=>l.code===value)?value:'pt';}
function setSharedLanguage(value){if(!catalog.languages.some(l=>l.code===value))return;localStorage.setItem('tsuyaku-display-language',value);for(const id of sharedLanguageIds){$('#'+id).value=value;localStorage.setItem(id,value);}if(room?.mode==='interpreter'){send({type:'language',language:value});if(mic)startRecognition();}renderReferences();}
function fillLanguages(){options($('#face-self-language'),localStorage.getItem('face-self-language')||'ja');const value=sharedLanguage();for(const id of sharedLanguageIds)options($('#'+id),value);}
fillLanguages();for(const id of sharedLanguageIds)$('#'+id).onchange=()=>setSharedLanguage($('#'+id).value);$('#face-self-language').onchange=()=>localStorage.setItem('face-self-language',$('#face-self-language').value);
let lessonRole="teacher";
function chooseLessonRole(next){lessonRole=next;$("#teacher-entry").hidden=next!=="teacher";$("#student-entry").hidden=next!=="student";$("#lesson-role-teacher").setAttribute("aria-pressed",String(next==="teacher"));$("#lesson-role-student").setAttribute("aria-pressed",String(next==="student"));}
$("#lesson-role-teacher").onclick=()=>chooseLessonRole("teacher");$("#lesson-role-student").onclick=()=>chooseLessonRole("student");
function setTab(next){if(next==="student")next="lesson";if(room&&['interpreter','lesson','face','student'].includes(next)&&next!==(room.mode==='lesson'?'lesson':room.mode)){message('モードを切り替えるときは、一度退室してください。');return;}tab=next;$$('[data-tab]').forEach(b=>{const active=b.dataset.tab===next;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;$('#panel-'+b.dataset.tab).hidden=!active||!!room&&['interpreter','lesson','face','student'].includes(next);});$('#live').hidden=!room||['phrases','terms'].includes(next);renderReferences();}
$$('[data-tab]').forEach(b=>{b.onclick=()=>setTab(b.dataset.tab);b.onkeydown=e=>{const tabs=$$('[data-tab]'),i=tabs.indexOf(b);let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();tabs[n].focus();setTab(tabs[n].dataset.tab);};});
async function initAuth(){try{const [a,b]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js')]);authApi=b;const auth=b.getAuth(a.initializeApp(config.firebase));await auth.authStateReady();if(!auth.currentUser)await b.signInAnonymously(auth);user=auth.currentUser;b.onAuthStateChanged(auth,u=>{user=u;});status('参加できます');}catch(e){status('接続できません');const failure=connectionFailure({code:'auth_unavailable'},{stage:'auth',endpoint:'https://identitytoolkit.googleapis.com',operation:'initial_auth'});connections.add({...failure.connection,online:navigator.onLine});showConnectionError(failure);}}
void listHistory().catch(()=>{});const ready=initAuth();
void ready.then(async()=>{if(!user)return;try{catalog=await api('/catalog');fillLanguages();renderReferences();}catch{message('保存済みの辞書を使っています。');}});
async function token(){await ready;if(!user)throw Error('接続を確認してください。');return user.getIdToken();}
async function api(path,data){let auth;try{auth=await token();}catch(error){const failure=connectionFailure({code:'auth_unavailable'},{stage:'auth',endpoint:'https://identitytoolkit.googleapis.com',operation:'token'});connections.add({...failure.connection,online:navigator.onLine});throw failure;}const operation=({'/rooms':'room_create','/lessons/join':'lesson_join','/catalog':'catalog','/dictionary/translate':'dictionary_translate','/dictionary/candidate':'dictionary_candidate'})[path]||'other';return requestJson(config.api+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+auth,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(25000),referrerPolicy:'no-referrer'},{operation,onFailure:record=>connections.add({...record,online:navigator.onLine})});}
function showConnectionError(error){message(error.message);if(!error.connectionIssue)return;const button=el('button','接続を確認');button.onclick=showNetworkDiagnostics;$('#message').append(button);}
function showNetworkDiagnostics(){const n=el('div',undefined,'connection-diagnostics');n.append(el('p','QRコードが出る前の失敗は、参加の認証やルーム作成の通信が原因です。音声中継（TURN）より前の段階です。'));const rows=el('div'),report=el('textarea');report.rows=10;report.readOnly=true;report.setAttribute('aria-label','接続診断結果');const run=el('button','接続を確認'),copy=el('button','結果をコピー');n.append(run,copy,rows,report);const refresh=()=>{report.value=JSON.stringify({app:'通訳君',schema:'tsuyaku-connection-v1',exportedAt:new Date().toISOString(),pageOrigin:location.origin,online:navigator.onLine,authentication:user?'ready':'unavailable',checks:connections.list(),analysis:explainConnection(connections.list(),{authentication:user?'ready':'unavailable',online:navigator.onLine}),note:'network_or_corsはブラウザーが理由を開示しない通信失敗。学校の制限・DNS・TLS・CORSのどれかは、この値だけでは断定できません。接続キー・token・発言・氏名は含みません。'},null,2);};const labels={api_simple:'字幕・翻訳サーバー',api_headers:'ルーム作成と同じ通信形式'};const results={ok:'接続できました',network_or_cors:'通信失敗（制限・CORSなど）',timeout:'時間切れ',http_error:'HTTPエラー',invalid_response:'アプリ用の応答ではありません'};run.onclick=async()=>{run.disabled=true;rows.replaceChildren(el('p','確認しています…'));try{const checks=await probeNetwork(config.api);checks.forEach(check=>connections.add({...check,online:navigator.onLine}));rows.replaceChildren(...checks.map(check=>el('p',labels[check.stage]+'：'+results[check.code]+(check.status?'（'+check.status+'）':''))));const analysis=explainConnection(connections.list(),{authentication:user?'ready':'unavailable',online:navigator.onLine});rows.append(el('h3','確認できた事実'),...analysis.facts.map(text=>el('p',text)),el('h3','原因の候補'),...analysis.candidates.map(item=>el('p',item.cause+'（'+item.confidence+'）：'+item.evidence)),el('h3','次の確認'),...analysis.nextSteps.map((text,i)=>el('p',(i+1)+'. '+text)),el('p',analysis.limitations));rows.append(el('p',checks.every(check=>check.code==='ok')?'この確認ではAPIへ接続できました。認証やルーム作成そのものの成功までは保証しません。':'この端末からAPIへ正常に接続できない項目があります。結果をコピーして、このチャットへ貼り付けてください。'));refresh();}finally{run.disabled=false;}};copy.onclick=async()=>{refresh();try{await navigator.clipboard.writeText(report.value);copy.textContent='コピーしました';}catch{report.focus();report.select();message('診断欄をコピーして、このチャットへ貼り付けてください。');}};refresh();modal('接続の確認',n);void run.onclick();}
async function exitModeFullscreen(){document.body.classList.remove("mode-active");delete document.body.dataset.activeMode;}
async function create(mode){const button=$('#create-'+mode);button.disabled=true;try{await ready;if(mode==='face')faceSide='self';const r=await api('/rooms',{mode,unit:$('#unit').value||'数学'});await enter({...r,creator:true});if(mode==='interpreter')showInvite();}catch(e){await exitModeFullscreen();showConnectionError(e);}finally{button.disabled=false;}}
$('#create-face').onclick=()=>create('face');$('#create-interpreter').onclick=()=>create('interpreter');$('#create-lesson').onclick=()=>create('lesson');
async function enter(r){await leave(false);room=r;if(r.mode==='lesson')chooseLessonRole(r.creator?'teacher':'student');scheduleRoomExpiry();message('');ledger.begin(r.mode,r.mode==='interpreter'?callCaptionLanguages($('#source-language').value):[r.mode==='lesson'?'ja':$('#face-self-language').value,sharedLanguage(),'en']);clearInterval(metricsTimer);metricsTimer=setInterval(()=>void sampleRtc(),15000);role=r.creator?'teacher':null;participants=[];$('#participants').replaceChildren();intentionalClose=false;records.clear();elements.clear();$('#captions').replaceChildren($('#empty-caption')||el('div','話したことばが、ここに。','empty'));$$('[role=tabpanel]').forEach(n=>n.hidden=true);$('#live').hidden=false;$$('[data-tab]').forEach(b=>b.disabled=false);setTab(r.mode==='lesson'&&!r.creator?'student':r.mode);document.body.classList.add('mode-active');document.body.dataset.activeMode=r.mode;history.replaceState(null,'',r.mode!=='interpreter'?location.pathname:'#room='+r.id+'&key='+r.key+'&mode='+r.mode);await connect();refreshTimer=setInterval(async()=>{try{if(socket?.readyState===1)socket.send(JSON.stringify({type:'reauth',token:await user.getIdToken(true)}));}catch{message('ログインの更新に失敗しました。');}},45*60000);heartbeat=setInterval(()=>send({type:'ping'}),20000);}
async function connect(){const epoch=sessionEpoch;const t=await token();if(!room||epoch!==sessionEpoch)return;clearTimeout(reconnectTimer);status('接続しています');turnReady=room.mode==='face'?Promise.resolve():loadTurn();const r=room,ws=new WebSocket(config.api.replace(/^http/,'ws')+'/rooms/'+r.id+'/socket');socket=ws;const current=()=>socket===ws&&epoch===sessionEpoch&&!!room;
 ws.onopen=()=>{if(!current())return;ws.send(JSON.stringify({type:'auth',token:t,key:r.key,name:(catalog.languages.find(l=>l.code===currentSource())?.labelJa||'ことば')+'の参加者',viewLanguage:r.mode==='face'?$('#face-other-language').value:r.mode==='lesson'?$('#lesson-language').value:$('#source-language').value,language:r.mode==='face'?$('#face-self-language').value:r.mode==='lesson'?(role==='teacher'?'ja':$('#lesson-language').value):$('#source-language').value}));authTimer=setTimeout(()=>{if(current()&&connectedAt===null){ledger.event('auth_timeout');ws.close(4000,'authentication timeout');}},12000);};
 ws.onmessage=e=>{if(!current())return;try{void handle(JSON.parse(e.data)).catch(e=>message('接続を確認してください。 '+e.message));}catch{message('受信したデータを確認できませんでした。');}};
 ws.onerror=()=>{if(!current())return;ledger.event('socket_error',{online:navigator.onLine,visibility:document.visibilityState});status('再接続しています');};
 ws.onclose=e=>{if(!current()||intentionalClose)return;clearTimeout(authTimer);const now=Date.now();recoveryStartedAt??=now;reconnectAttempts++;const retryMs=navigator.onLine?retryDelay(reconnectAttempts):15000;ledger.event('reconnect',{code:e.code,wasClean:e.wasClean,openSeconds:connectedAt===null?0:(now-connectedAt)/1000,attempt:reconnectAttempts,retryMs,online:navigator.onLine,visibility:document.visibilityState});connectedAt=null;participants=[];$('#participants').replaceChildren();status('再接続しています');stopRecognition();for(const p of peers.values()){p.pc.close();p.audio.remove();}peers.clear();reconnectTimer=setTimeout(()=>void connect().catch(()=>ledger.event('reconnect_error')),retryMs);};}
window.addEventListener('online',()=>{if(room&&socket?.readyState===3){clearTimeout(reconnectTimer);void connect();}});

function send(data){if(socket?.readyState!==1)return false;socket.send(JSON.stringify(data));return true;}
async function handle(data){
 if(data.type==='error'){ledger.event('server_error');message(data.error);return;}
 if(data.type==='ready'){clearTimeout(authTimer);connectedAt=Date.now();if(recoveryStartedAt!==null)ledger.event('connection_restored',{recoverySeconds:(connectedAt-recoveryStartedAt)/1000,attempt:reconnectAttempts});recoveryStartedAt=null;reconnectAttempts=0;selfId=data.id;role=data.role;room.mode=data.mode;room.code=data.code||room.code;room.expires=data.expires||room.expires;scheduleRoomExpiry();updateLessonCode();room.unit=data.unit;updateFace();status('接続中');$('#microphone').hidden=room.mode==='lesson'&&role!=='teacher';$('#text-form').hidden=room.mode==='lesson'&&role!=='teacher';$('#invite').hidden=room.mode!=='interpreter'||role!=='teacher';for(const r of data.history||[])renderCaption(r);for(const p of pending.values())send(p);await turnReady;if(data.ended){await handle({type:'ended'});return;}if(mic)startRecognition();return;}
 if(data.type==='participants'){if(room.mode==='face')return;participants=data.participants||[];$('#participants').replaceChildren(...participants.map(p=>el('span',(p.id===selfId?'あなた':p.name)+(p.role==='teacher'&&room.mode==='lesson'?'・先生':''),'participant')));if(room.mode==='interpreter'&&participants.some(p=>p.id!==selfId)&&$('#modal').open&&$('#modal').dataset.kind==='invite')$('#modal').close();for(const [id,p] of peers){if(!participants.some(x=>x.id===id)){p.pc.close();p.audio.remove();peers.delete(id);}}const epoch=sessionEpoch;await turnReady;if(epoch!==sessionEpoch||!room)return;for(const p of participants){if(p.id===selfId)continue;if(room.mode==='interpreter'&&selfId<p.id||room.mode==='lesson'&&role==='teacher')await offer(p.id);}return;}
 if(data.type==='signal'){await turnReady;await signal(data.from,data.signal);return;}
 if(data.type==='caption')return;
 if(data.type==='translation'){const rawId=[...localTimings.keys()].find(id=>data.id===selfId+'_'+id);if(rawId){if(data.status==='ready'){const metrics=latencyFromTiming(localTimings.get(rawId),Date.now());ledger.timing(data.id,metrics);}localTimings.delete(rawId);}ledger.caption(data);renderCaption(data);records.set(data.id,data);if(data.status==='failed')showTranslationFailure(data);for(const [id,p] of pending){if(data.id.endsWith('_'+id))pending.delete(id);}return;}
 if(data.type==='notice'){message(data.text);return;}
 if(data.type==='ended'){ledger.event('lesson_ended');await leave(true);message('授業が終了しました。');return;}
}
async function loadTurn(){rtcConfig={iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]};try{const data=await requestJson(config.turn,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({callId:room?.id||'tsuyaku',clientId:crypto.randomUUID()}),signal:AbortSignal.timeout(8000)},{stage:'turn',operation:'turn_credentials',onFailure:record=>connections.add({...record,online:navigator.onLine})});if(!Array.isArray(data.iceServers)||!data.iceServers.some(server=>[server.urls].flat().some(url=>/^turns?:/.test(url))))throw connectionFailure({code:'no_turn_server'},{stage:'turn',endpoint:config.turn,operation:'turn_credentials'});rtcConfig={iceServers:data.iceServers};connections.add({stage:'turn',endpoint:config.turn,operation:'turn_credentials',code:'ok',online:navigator.onLine});}catch(error){if(!error.connectionIssue)connections.add({stage:'turn',endpoint:config.turn,operation:'turn_credentials',code:'http_error',status:error.httpStatus,online:navigator.onLine});else if(error.connection?.code==='no_turn_server')connections.add({...error.connection,online:navigator.onLine});message('音声の中継を利用できません。字幕は利用できますが、音声は直接接続のみになります。');const button=el('button','接続を確認');button.onclick=showNetworkDiagnostics;$('#message').append(button);}}
function peer(id){if(peers.has(id))return peers.get(id);const pc=new RTCPeerConnection(rtcConfig),audio=el('audio');audio.autoplay=false;audio.muted=true;audio.setAttribute('playsinline','');document.body.append(audio);const p={pc,audio,metricsId:crypto.randomUUID(),ice:[],offering:false};peers.set(id,p);pc.onicecandidate=e=>{if(e.candidate)send({type:'signal',to:id,signal:{candidate:e.candidate}});};pc.ontrack=e=>{audio.srcObject=e.streams[0]||new MediaStream([e.track]);};pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed'){ledger.event('rtc_failed');if(role==='teacher'||selfId<id){pc.restartIce();void offer(id,true);}}};if(localStream&&(room.mode==='interpreter'||role==='teacher'))localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));else pc.addTransceiver('audio',{direction:'recvonly'});return p;}
async function offer(id,restart=false){const p=peer(id);if(p.offering||p.pc.signalingState!=='stable')return;if(p.pc.currentLocalDescription&&!restart)return;p.offering=true;try{await p.pc.setLocalDescription(await p.pc.createOffer({iceRestart:restart}));send({type:'signal',to:id,signal:{description:p.pc.localDescription}});}catch(e){message('音声の接続に失敗しました。 '+e.message);}finally{p.offering=false;}}
async function signal(id,data){const p=peer(id);try{if(data.description){const polite=selfId>id||room.mode==='lesson'&&role!=='teacher';if(data.description.type==='offer'&&(p.offering||p.pc.signalingState!=='stable')){if(!polite)return;await p.pc.setLocalDescription({type:'rollback'});}await p.pc.setRemoteDescription(data.description);for(const candidate of p.ice.splice(0))await p.pc.addIceCandidate(candidate);if(data.description.type==='offer'){await p.pc.setLocalDescription(await p.pc.createAnswer());send({type:'signal',to:id,signal:{description:p.pc.localDescription}});}}else if(data.candidate){if(p.pc.remoteDescription)await p.pc.addIceCandidate(data.candidate);else p.ice.push(data.candidate);}}catch(e){message('音声接続を確認してください。 '+e.message);}}
async function ensureMicrophone(){if(!localStream)localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});for(const [id,p] of peers){const sender=p.pc.getSenders().find(s=>s.track?.kind==='audio'),transceiver=p.pc.getTransceivers().find(t=>t.receiver.track.kind==='audio');if(sender)await sender.replaceTrack(localStream.getAudioTracks()[0]);else if(transceiver){await transceiver.sender.replaceTrack(localStream.getAudioTracks()[0]);transceiver.direction='sendrecv';}else p.pc.addTrack(localStream.getAudioTracks()[0],localStream);await offer(id,true);}return localStream;}
$('#microphone').onclick=async()=>{if(!room)return;try{mic=!mic;if(mic){await ensureMicrophone();localStream.getAudioTracks().forEach(t=>t.enabled=true);startRecognition();}else{stopRecognition();localStream?.getAudioTracks().forEach(t=>t.enabled=false);}ledger.microphone(mic);ledger.event(mic?'mic_on':'mic_off');paintButton($('#microphone'),mic?'マイク ON':'マイク OFF',mic?'microphone':'microphone-slash');$('#microphone').setAttribute('aria-pressed',mic);}catch(e){mic=false;stopRecognition();localStream?.getAudioTracks().forEach(t=>t.enabled=false);$('#microphone').setAttribute('aria-pressed','false');paintButton($('#microphone'),'マイクを再開','microphone');ledger.microphone(false);ledger.event('microphone_error');message('マイクを許可して、もう一度押してください。 '+e.message);}};
function stopRecognition(){restarting=false;const previous=recognition;recognition=null;previous?.abort();}
function startRecognition(fallback=false){stopRecognition();if(!mic||!room)return;const lang=currentSource(),side=faceSide;let factory;if(lang==='ja'&&!fallback)factory=createStreamingRecognition({endpoint:'wss://kouryu-captions.allinone-hiroakiaa.workers.dev/stream',getStream:()=>localStream,getToken:token,onUsage:seconds=>ledger.audio(seconds,'stream')});else factory=createServerRecognition({endpoint:config.api+'/transcribe?language='+encodeURIComponent(lang),getStream:()=>localStream,getToken:token,onUsage:seconds=>ledger.audio(seconds,'whisper')});recognition=new factory();const activeRecognition=recognition;recognition.setHints?.(()=>catalog.glossary.map(t=>t.ja));const prefix=crypto.randomUUID().slice(0,8);recognition.onresult=e=>{if(recognition!==activeRecognition)return;const r=e.results[e.resultIndex];if(!r?.[0]?.transcript?.trim())return;const cap={type:'caption',id:prefix+'_'+e.resultIndex,text:r[0].transcript,final:r.isFinal,...(room?.mode==='face'?speakerCaption(side,$('#face-self-language').value,$('#face-other-language').value):{})};if(r.isFinal){const now=Date.now();localTimings.set(cap.id,{kind:'speech',speechEndedAt:e.speechEndedAt,recognitionReadyAt:e.recognitionReadyAt??now,sentAt:now});pending.set(cap.id,cap);}send(cap);};recognition.onerror=e=>{if(recognition!==activeRecognition)return;ledger.event('recognition_error',{recognitionCode:['network','auth','quota','overloaded','interrupted','audio-capture'].includes(e?.error)?e.error:'unknown'});if(mic&&room&&!fallback&&lang==='ja'){ledger.event('asr_fallback');message('音声認識を補助方式へ切り替えました。');startRecognition(true);}else{ledger.event('asr_error');ledger.microphone(false);message('字幕の接続が途切れました。マイクを押し直すか文字で伝えてください。');mic=false;stopRecognition();localStream?.getAudioTracks().forEach(t=>t.enabled=false);paintButton($('#microphone'),'マイクを再開','microphone');$('#microphone').setAttribute('aria-pressed','false');}};recognition.onend=()=>{if(recognition!==activeRecognition)return;if(mic&&room&&!restarting){restarting=true;setTimeout(()=>{if(mic&&room)startRecognition(fallback);},1000);}};recognition.start();}


const speechPlayer=new SpeechPlayer({engine:window.speechSynthesis,Utterance:window.SpeechSynthesisUtterance,onChange:updateSpeechControls,onError:error=>message(error==='unsupported'?'この端末では読み上げを使えません。':'読み上げを再生できませんでした。対応する音声が端末にあるか確認してください。')});
$('#modal').addEventListener('close',()=>speechPlayer.stop());
function updateSpeechControls(){for(const group of $$('[data-speech-key]')){const active=group.dataset.speechKey===speechPlayer.key,play=group.querySelector('[data-play]'),stop=group.querySelector('[data-stop]');play.replaceChildren(icon(active&&!speechPlayer.paused?'pause':'play'));play.setAttribute('aria-label',group.dataset.speechLabel+(active?(speechPlayer.paused?'の読み上げを再開':'の読み上げを一時停止'):'を読み上げる'));play.title=active?(speechPlayer.paused?'再開':'一時停止'):'再生';stop.hidden=!active;}}
function speechControls(text,lang,key){const group=el('div',undefined,'speech-controls'),play=el('button'),stop=el('button');group.dataset.speechKey=key;group.dataset.speechLabel=(catalog.languages.find(l=>l.code===lang)?.labelJa||lang)+'の文';play.dataset.play='';stop.dataset.stop='';play.append(icon('play'));stop.append(icon('stop'));stop.hidden=true;play.type=stop.type='button';play.setAttribute('aria-label',group.dataset.speechLabel+'を読み上げる');stop.setAttribute('aria-label',group.dataset.speechLabel+'の読み上げを停止');stop.title='停止';play.onclick=()=>speechPlayer.toggle(key,text,catalog.languages.find(l=>l.code===lang)?.speechCode||lang);stop.onclick=()=>speechPlayer.stop();group.append(play,stop);return group;}

function renderCaption(r){const old=records.get(r.id)||{},next={...old,...r};if(!isDisplayableCaption(next))return;const view=sharedLanguage();const codes=room?.mode==='interpreter'?callCaptionLanguages($('#source-language').value):[...new Set(room?.mode==='face'?['ja',$('#face-self-language').value,$('#face-other-language').value,'en']:['ja',view,'en'])];const lines=codes.map(code=>({code,text:next.translations?.[code]||(code===next.source?next.text:'')})).filter(line=>line.text);if(!lines.length)return;const nearBottom=$('#captions').scrollHeight-$('#captions').scrollTop-$('#captions').clientHeight<100;let article=elements.get(r.id);if(!article){$('#captions .empty')?.remove();article=el('article',undefined,'caption');elements.set(r.id,article);$('#captions').append(article);}article.className='caption';article.replaceChildren();const meta=el('div',undefined,'caption-meta');meta.append(el('span',next.speaker||'参加者'));if(next.latencyMs)meta.append(el('span',(next.latencyMs/1000).toFixed(1)+'秒'));article.append(meta);for(const {code,text} of lines){const line=el('div',undefined,'caption-line');line.append(el('small',catalog.languages.find(l=>l.code===code)?.labelJa||code),el('p',text),speechControls(text,code,next.id+':'+code));article.append(line);}records.set(r.id,next);updateSpeechControls();if(nearBottom)$('#captions').scrollTop=$('#captions').scrollHeight;}
$('#text-form').onsubmit=e=>{e.preventDefault();const text=$('#text-input').value.trim();if(!text)return;const cap={...(room.mode==='face'?speakerCaption(faceSide,$('#face-self-language').value,$('#face-other-language').value):{}),type:'caption',id:crypto.randomUUID(),text,final:true};localTimings.set(cap.id,{kind:'text',sentAt:Date.now()});pending.set(cap.id,cap);if(send(cap))$('#text-input').value='';else message('再接続後に送信します。');};
function inviteLink(){const url=new URL(location.href);url.hash=new URLSearchParams({room:room.id,key:room.key,mode:room.mode}).toString();return url.href;}
function showInvite(){if(!room||room.mode!=='interpreter'||participants.some(p=>p.id!==selfId))return;const n=el('div'),input=el('input');input.readOnly=true;input.value=inviteLink();n.append(label('招待リンク',input));const copy=el('button','リンクをコピー');copy.onclick=async()=>{try{await navigator.clipboard.writeText(input.value);copy.textContent='コピーしました';}catch{input.select();message('招待リンクをコピーしてください。');}};n.append(copy);const canvas=el('canvas');canvas.className='qr';n.append(canvas);void import('./qr.js').then(m=>m.drawQr(canvas,input.value)).catch(()=>{});n.append(el('p','このリンクを受け取った人が参加できます。'));modal('相手を招待',n);$('#modal').dataset.kind='invite';}
$('#invite').onclick=showInvite;
function download(name,text,type='text/csv;charset=utf-8'){const a=el('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function showTranslationFailure(data){message('翻訳できませんでした。');if(!data.id.startsWith(selfId+'_'))return;const retry=el('button','再試行');retry.onclick=()=>{send({type:'caption',id:data.id.slice(selfId.length+1),text:data.text,final:true,...(room?.mode==='face'?{source:data.source,speakerSide:data.speaker==='相手'?'other':'self'}:{})});message('翻訳を再試行しています。');};$('#message').append(retry);}


async function leave(show=true){intentionalClose=true;if(socket?.readyState===1)send({type:'leave'});stopRecognition();localStream?.getAudioTracks().forEach(t=>t.enabled=false);speechPlayer.stop();await sampleRtc();ledger.end();clearInterval(metricsTimer);clearTimeout(roomExpiryTimer);sessionEpoch++;intentionalClose=true;clearTimeout(reconnectTimer);clearTimeout(authTimer);reconnectAttempts=0;recoveryStartedAt=null;connectedAt=null;localTimings.clear();clearInterval(refreshTimer);clearInterval(heartbeat);stopRecognition();mic=false;socket?.close();socket=null;for(const p of peers.values()){p.pc.close();p.audio.remove();}peers.clear();localStream?.getTracks().forEach(t=>t.stop());localStream=null;pending.clear();participants=[];$('#participants').replaceChildren();if($('#modal').dataset.kind==='invite')$('#modal').close();room=null;updateFace();updateLessonCode();paintButton($('#microphone'),'マイクを開始','microphone');$('#microphone').setAttribute('aria-pressed','false');$('#microphone').disabled=false;if(show){await exitModeFullscreen();lastJoinCode='';$('#live').hidden=true;$$('[data-tab]').forEach(b=>b.disabled=false);setTab(tab);history.replaceState(null,'',location.pathname);status('退室しました');}}
$('#leave').onclick=()=>{if(role==='teacher'&&room?.mode==='lesson'){const n=el('div');n.append(el('p','授業を終了すると、生徒への音声と字幕の配信が止まります。'));const end=el('button','授業を終了する');end.onclick=()=>{send({type:'end'});$('#modal').close();setTimeout(()=>void leave(),200);};const exit=el('button','自分だけ退室する');exit.onclick=()=>{$('#modal').close();void leave();};n.append(end,exit);modal('授業を終了',n);}else void leave();};
window.addEventListener('pagehide',()=>{ledger.end();void leave(false);});
async function sampleRtc(){for(const [id,p]of peers){try{const report=await p.pc.getStats();let pair;for(const v of report.values())if(v.type==='transport'&&v.selectedCandidatePairId)pair=report.get(v.selectedCandidatePairId);if(!pair)for(const v of report.values())if(v.type==='candidate-pair'&&v.state==='succeeded'&&v.nominated)pair=v;let lost=0,jitterMs=0;for(const v of report.values())if(v.type==='inbound-rtp'&&v.kind==='audio'){lost+=v.packetsLost||0;jitterMs=Math.max(jitterMs,(v.jitter||0)*1000);}if(pair)ledger.rtc(p.metricsId,{bytes:(pair.bytesSent||0)+(pair.bytesReceived||0),relay:report.get(pair.localCandidateId)?.candidateType==='relay'||report.get(pair.remoteCandidateId)?.candidateType==='relay',lost,jitterMs,rttMs:Number.isFinite(pair.currentRoundTripTime)?pair.currentRoundTripTime*1000:undefined});}catch{}}ledger.save();}
const referenceTranslations=new Map();
function translateReference(row,type,lang){const text=type==='phrase'?row.jaText:[row.ja||row.title,row.descriptionJa].filter(Boolean).join('\n');const key=JSON.stringify([type,text,lang]);if(referenceTranslations.has(key))return referenceTranslations.get(key);const refLedger=new UsageLedger(localStorage);refLedger.begin(type==='phrase'?'phrases':'terms',['ja',lang]);const id=crypto.randomUUID(),at=Date.now();const job=api('/dictionary/translate',{text,language:lang,subject:row.subject||row.category||''}).then(result=>{refLedger.caption({id,at,final:true,status:'ready',usage:result.usage,latencyMs:result.latencyMs});return result.translation;}).catch(error=>{refLedger.caption({id,at,final:true,status:'failed',usage:error.usage,latencyMs:error.latencyMs});referenceTranslations.delete(key);throw error;}).finally(()=>refLedger.end());referenceTranslations.set(key,job);return job;}
function showReference(row,type){const lang=sharedLanguage(),n=el('div',undefined,'reference-detail'),ja=type==='phrase'?row.jaText:row.descriptionJa||row.ja||row.title,en=type==='phrase'?row.enText:row.enText||row.en,translated=translationOf(row,lang);if(ja)n.append(el('h3','日本語'),el('p',ja));const translatedBody=el('div');n.append(el('h3',catalog.languages.find(l=>l.code===lang)?.labelJa||'あなたのことば'),translatedBody);if(en)n.append(el('h3','English'),el('p',en));const show=text=>{translatedBody.replaceChildren(el('p',text),speechControls(text,lang,'reference:'+type+':'+(row.id||row.ja||row.title)+':'+lang));updateSpeechControls();};const load=async()=>{translatedBody.replaceChildren(el('p','翻訳しています…'));try{show(await translateReference(row,type,lang));translatedBody.append(el('small','自動翻訳'));}catch(error){translatedBody.replaceChildren(el('p',error.message));const retry=el('button','再試行');retry.onclick=load;translatedBody.append(retry);}};modal(row.title||row.ja,n);if(translated)show(translated);else void load();}
function renderReferences(){const lang=sharedLanguage();for(const [type,list,q,rows]of[['phrase',$('#phrase-list'),$('#phrase-search').value,catalog.phrases],['term',$('#term-list'),$('#term-search').value,[...catalog.glossary,...catalog.terms]]]){const found=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())).slice(0,80);list.replaceChildren(...found.map(row=>{const card=el('article',undefined,'reference-card'),left=el('div');left.append(el('h3',row.title||row.ja),el('p',row.category||row.subject||''));card.append(left);const button=el('button','ひらく');button.onclick=()=>showReference(row,type);card.append(button);return card;}));if(!found.length)list.append(el('p','見つかりませんでした。'));}}
$('#phrase-search').oninput=renderReferences;$('#term-search').oninput=renderReferences;renderReferences();
$('#add-term').onclick=()=>{const n=el('form'),term=el('input'),tr=el('input'),lang=el('select');term.maxLength=80;tr.maxLength=500;options(lang,sharedLanguage());n.append(label('ことば',term),label('訳',tr),label('言語',lang));const b=el('button','候補として送る');b.type='submit';n.append(b);n.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await api('/dictionary/candidate',{term:term.value,translation:tr.value,language:lang.value});message('スプレッドシートに候補を追加しました。');$('#modal').close();}catch(e){message(e.message);}finally{b.disabled=false;}};modal('ことばを追加',n);};
const invite=new URLSearchParams(location.hash.slice(1));if(/^[a-f0-9]{32}$/.test(invite.get('room')||'')&&/^[a-f0-9]{32}$/.test(invite.get('key')||'')){const n=el('div'),lang=el('select');options(lang,$('#source-language').value);n.append(label('話すことば',lang));const b=el('button','参加する');b.onclick=async()=>{b.disabled=true;try{setSharedLanguage(lang.value);await ready;await enter({id:invite.get('room'),key:invite.get('key'),mode:invite.get('mode')==='lesson'?'lesson':'interpreter'});$('#modal').close();}catch(e){message(e.message);}finally{b.disabled=false;}};n.append(b);modal('招待が届いています',n);}


function currentSource(){return room?.mode==='lesson'?'ja':room?.mode==='face'?speakerInfo(faceSide,$('#face-self-language').value,$('#face-other-language').value).language:$('#source-language').value;}
function updateFace(){const face=room?.mode==='face';$('#face-controls').hidden=!face;$('#participants').hidden=face;if(!face){$('#text-input').placeholder='文字でも伝えられます';return;}const info=speakerInfo(faceSide,$('#face-self-language').value,$('#face-other-language').value);$('#face-speaker').textContent=info.speaker+'が話す';$('#face-language').textContent=catalog.languages.find(l=>l.code===info.language)?.labelJa||info.language;paintButton($('#switch-speaker'),(faceSide==='self'?'相手':'自分')+'に切り替える','arrow-right-arrow-left');$('#text-input').placeholder=info.speaker+'のことばを入力';}
$('#switch-speaker').onclick=()=>{if(room?.mode!=='face')return;speechPlayer.stop();stopRecognition();faceSide=faceSide==='self'?'other':'self';$('#text-input').value='';updateFace();if(mic)startRecognition();ledger.event('speaker_switch');};

function icon(name){const i=el('i',undefined,'fa-solid fa-'+name);i.setAttribute('aria-hidden','true');return i;}
function paintButton(button,text,name){button.replaceChildren(icon(name),el('span',text));}
function updateLessonCode(){const visible=room?.mode==='lesson'&&role==='teacher'&&!!room.code;$('#lesson-code-card').hidden=!visible;$('#lesson-room-code').textContent=visible?room.code:'';}
$('#copy-lesson-code').onclick=async()=>{try{await navigator.clipboard.writeText(room.code);message('ルームIDをコピーしました。');}catch{message('ルームID：'+room.code);}};
let joiningLesson=false,lastJoinCode='';async function joinLesson(){const input=$('#lesson-code-input'),code=input.value.replace(/[０-９]/g,c=>String(c.charCodeAt(0)-65296)).trim();input.value=code;if(joiningLesson||!/^\d{4}$/.test(code))return;joiningLesson=true;lastJoinCode=code;$('#join-lesson').disabled=true;input.disabled=true;$('#join-status').textContent='参加しています…';try{const r=await api('/lessons/join',{code});await enter(r);$('#join-status').textContent='4桁を入力すると参加できます。';}catch(e){await exitModeFullscreen();lastJoinCode='';$('#join-status').textContent=e.message;if(e.connectionIssue)showConnectionError(e);}finally{joiningLesson=false;input.disabled=false;$('#join-lesson').disabled=false;}}
$('#join-lesson-form').onsubmit=e=>{e.preventDefault();void joinLesson();};$('#lesson-code-input').oninput=e=>{if(e.isComposing)return;const code=e.target.value.replace(/[０-９]/g,c=>String(c.charCodeAt(0)-65296)).trim();if(/^\d{4}$/.test(code)&&code!==lastJoinCode)void joinLesson();};
for(const [id,name]of [['microphone','microphone'],['leave','door-open'],['invite','user-plus']]){const b=$('#'+id);paintButton(b,b.textContent,name);}

function scheduleRoomExpiry(){clearTimeout(roomExpiryTimer);if(!room?.expires)return;const activeRoom=room;roomExpiryTimer=setTimeout(async()=>{if(room!==activeRoom)return;await leave();records.clear();elements.clear();$('#captions').replaceChildren();void listHistory().catch(()=>{});message('ルームの24時間の有効期限が切れました。新しいルームを作成してください。');},Math.max(0,room.expires-Date.now()));}
