import {TranslationMemory} from './translation-memory.js?v=20261007-learning-1';
import {PersonalPhrases} from './personal-phrases.js?v=20261007-learning-1';
import {recognitionHints} from './recognition-hints.js?v=20261007-progressive-1';
import {acquireMicrophone} from './microphone.js?v=20261006-mic-1';
import {UsageLedger} from './usage.js?v=20261007-learning-1';
import {SpeechPlayer} from './speech-player.js?v=20261006-playback-2';
import {latencyFromTiming,retryDelay} from './diagnostics.js?v=20261007-progressive-1';
import {installAdmin} from './admin.js?v=20261007-progressive-1';
import {config} from './config.js';
import {ConnectionDiary,connectionFailure,requestJson,probeNetwork,explainConnection} from './network.js?v=20261007-progressive-1';
import {catalog as seed} from '../server/catalog.js?v=20261006-easy-1';
import {translationOf,spokenLanguage,withEasyJapanese} from './core.js?v=20261007-progressive-1';
import {speakerCaption,speakerInfo} from './face-mode.js?v=20261006-school-1';
import {callCaptionLanguages,isDisplayableCaption} from './call-mode.js?v=20261006-easy-1';
import {listHistory} from './history.js?v=20261006-school-1';
import {createServerRecognition} from './caption-server.js?v=20261007-learning-1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function readCatalogCache(){try{const saved=JSON.parse(localStorage.getItem('tsuyaku-catalog-v1'));if(saved&&Array.isArray(saved.languages)&&Array.isArray(saved.phrases)&&Array.isArray(saved.terms)&&Array.isArray(saved.glossary))return saved;}catch{}return seed;}
let catalog=withEasyJapanese(readCatalogCache()),authApi,user,socket,room,selfId,role,localStream,recognition,restarting=false,recognitionRetries=0,recognitionRetryTimer,sessionEpoch=0,mic=false,participants=[],tab='face',intentionalClose=false,refreshTimer,reconnectTimer,heartbeat;
let roomExpiryTimer;let faceSide='self';let reconnectAttempts=0,recoveryStartedAt=null,connectedAt=null,authTimer;const localTimings=new Map();
const peers=new Map(),records=new Map(),elements=new Map(),pending=new Map();let turnReady=Promise.resolve(),rtcConfig={iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]};
const ledger=new UsageLedger(localStorage),connections=new ConnectionDiary(localStorage);let metricsTimer;
let messageTimer;const message=text=>{clearTimeout(messageTimer);const n=$('#message');n.textContent=text;n.hidden=!text;if(text)messageTimer=setTimeout(()=>{n.replaceChildren();n.hidden=true;},6000);};
installAdmin({button:$('#admin'),modal,el,ledger,download,currentRecords:()=>[...records.values()],connectionHistory:()=>connections.list(),connectionAnalysis:()=>explainConnection(connections.list(),{authentication:user?'ready':'unavailable',online:navigator.onLine,sessions:ledger.list()}),checkConnection:showNetworkDiagnostics,message});
const status=text=>{$('#connection').textContent=text;};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;if(tag==='button'&&text){const icons={'接続を確認':'network-wired','再試行':'rotate-right','リンクをコピー':'copy','ひらく':'book-open','候補として送る':'plus','授業をおわる':'stop','じぶんだけホームにもどる':'door-open'};if(icons[text])n.prepend(icon(icons[text]));}return n;}
function modal(title,content){delete $('#modal').dataset.kind;$('#modal-title').textContent=title;$('#modal-reading')?.remove();$('#modal-body').replaceChildren(content);$('#modal').showModal();}

let callStarted=false;
function updateLiveActions(){
 $('#leave').hidden=!room||room.mode==='face'||(room.mode==='interpreter'&&!callStarted);
 if(!room)return;

 const endingLesson=room.mode==='lesson'&&role==='teacher';const endLabel=endingLesson?'授業をおわる':room.mode==='interpreter'?'通話をおわる':room.mode==='face'?'会話をおわる':'もどる';paintButton($('#leave'),endLabel,'door-open');$('#leave').setAttribute('aria-label',endLabel);
}

$('#modal-close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close();};
function label(text,input){const n=el('label',text);n.append(input);return n;}
function options(select,selected){select.replaceChildren(...catalog.languages.map(l=>{const o=el('option',l.labelNative&&l.labelNative!==l.labelJa?l.labelJa+' / '+l.labelNative:l.labelJa);o.value=l.code;return o;}));select.value=selected;}
const sharedLanguageIds=['face-other-language'];
function sharedLanguage(){const value=localStorage.getItem('tsuyaku-display-language')||localStorage.getItem('view-language')||localStorage.getItem('face-other-language')||'pt';return catalog.languages.some(l=>l.code===value)?value:'pt';}
function speakingLanguage(){const value=localStorage.getItem('tsuyaku-speaking-language')||localStorage.getItem('face-self-language')||'ja';return catalog.languages.some(l=>l.code===value)?value:'ja';}
function setSpeakingLanguage(value){if(!catalog.languages.some(l=>l.code===value))return;localStorage.setItem('tsuyaku-speaking-language',value);for(const id of ['face-self-language','source-language']){$('#'+id).value=value;localStorage.setItem(id,value);}if(room?.mode==='interpreter'){send({type:'language',language:value});if(mic)startRecognition();}}
function setSharedLanguage(value){if(!catalog.languages.some(l=>l.code===value))return;localStorage.setItem('tsuyaku-display-language',value);for(const id of sharedLanguageIds){$('#'+id).value=value;localStorage.setItem(id,value);}renderReferences();}
function fillLanguages(){for(const id of ['face-self-language','source-language'])options($('#'+id),speakingLanguage());const value=sharedLanguage();for(const id of sharedLanguageIds)options($('#'+id),value);}
fillLanguages();options($('#face-language'),speakingLanguage());for(const id of sharedLanguageIds)$('#'+id).onchange=()=>setSharedLanguage($('#'+id).value);for(const id of ['face-self-language','source-language'])$('#'+id).onchange=()=>setSpeakingLanguage($('#'+id).value);
function showLanguageOptions(){const content=el('div',undefined,'language-panel'),spoken=el('select'),display=el('select');options(spoken,speakingLanguage());options(display,sharedLanguage());spoken.onchange=()=>{setSpeakingLanguage(spoken.value);if(room?.mode==='face'){updateFace();if(mic)startRecognition();}};display.onchange=()=>{setSharedLanguage(display.value);if(room?.mode==='face')updateFace();for(const record of [...records.values()])renderCaption(record);};content.append(label('じぶんが話すことば',spoken),label('訳を読むことば',display));const done=el('button','閉じる','primary');done.onclick=()=>$('#modal').close();content.append(done);modal('言語を選ぶ',content);}
$('#language-options').onclick=showLanguageOptions;
let lessonRole=null;
function chooseLessonRole(next){lessonRole=next;$("#lesson-toolbar").hidden=!next;const codeEntry=$("#lesson-code-entry");if(codeEntry)codeEntry.hidden=next!=="student"||room?.mode==="lesson";$("#lesson-role-picker").hidden=!!next;$("#lesson-role-back").hidden=!next;$("#teacher-entry").hidden=next!=="teacher";$("#student-entry").hidden=next!=="student";$("#join-lesson-form").hidden=next!=="student";$("#lesson-role-teacher").setAttribute("aria-pressed",String(next==="teacher"));$("#lesson-role-student").setAttribute("aria-pressed",String(next==="student"));}
$("#lesson-role-teacher").onclick=()=>{chooseLessonRole("teacher");void create("lesson",{automatic:true});};$("#lesson-role-student").onclick=()=>chooseLessonRole("student");
$('#lesson-role-back').onclick=async()=>{if(room?.mode==='lesson')await leave(false);$('#live').hidden=true;chooseLessonRole(null);};
let referenceTab='phrases';
function chooseReferenceTab(next){referenceTab=next;for(const button of $$('[data-reference-tab]')){const active=button.dataset.referenceTab===next;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;}$('#panel-phrases').hidden=next!=='phrases';$('#panel-terms').hidden=next!=='terms';}
for(const button of $$('[data-reference-tab]')){button.onclick=()=>chooseReferenceTab(button.dataset.referenceTab);button.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?'phrases':e.key==='End'?'terms':referenceTab==='phrases'?'terms':'phrases';chooseReferenceTab(next);$('[data-reference-tab="'+next+'"]').focus();};}
function setTab(next){if(next==="student")next="lesson";if(next==='lesson'&&!room&&tab!=='lesson')chooseLessonRole(null);tab=next;$$('[data-tab]').forEach(b=>{const active=b.dataset.tab===next;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;$('#panel-'+b.dataset.tab).hidden=!active;});$('#live').hidden=!room||room.mode!==next;if(next==='words')chooseReferenceTab(referenceTab);renderReferences();}
function mountConversation(mode){const panel=$('#panel-'+mode);panel.append($('#live'));const entry=panel.querySelector('.entry-card');if(entry&&mode!=='lesson')entry.hidden=true;if(mode==='lesson'){for(const id of ['lesson-role-picker','teacher-entry','student-entry'])$('#'+id).hidden=true;$('#lesson-role-back').hidden=false;}}
const qrModule=import('./qr.js').catch(()=>null);
function resetConversationContents(){}
function showConversationPreparation(mode){
 $('#leave').hidden=true;const endLabel=mode==='interpreter'?'通話をおわる':'会話をおわる';paintButton($('#leave'),endLabel,'door-open');$('#leave').setAttribute('aria-label',endLabel);$('#text-input').value='';const empty=el('div',undefined,'empty'),symbol=icon('comments');empty.id='empty-caption';symbol.classList.add('speech-symbol');empty.append(symbol,el('h2','話したことばが、ここに。'));$('#captions').replaceChildren(empty);if(mode==='face'){showFacePreparation();return;}mountConversation('interpreter');$('#panel-interpreter').hidden=false;$('#live').hidden=false;$('#face-controls').hidden=true;$('#participants').hidden=true;$('#invite').hidden=true;document.body.classList.add('mode-active');document.body.dataset.activeMode='interpreter';const n=$('#call-invite');n.hidden=false;n.replaceChildren();delete n.dataset.room;const language=el('select');options(language,speakingLanguage());language.onchange=()=>setSpeakingLanguage(language.value);const preparing=el('div','接続を準備しています','invite-preparing');preparing.setAttribute('role','status');n.append(label('じぶんが話すことば',language),preparing);$('#text-input').placeholder='ことばを入力して送る';for(const selector of ['#text-input','#text-form button','#microphone'])$(selector).disabled=true;}
function showFacePreparation(){mountConversation('face');$('#panel-face').hidden=false;$('#live').hidden=false;$('#face-controls').hidden=false;$('#participants').hidden=true;$('#invite').hidden=true;document.body.classList.add('mode-active');document.body.dataset.activeMode='face';$('#face-speaker').textContent='自分が話す';options($('#face-language'),$('#face-self-language').value);paintButton($('#switch-speaker'),'相手の番にする','arrow-right-arrow-left');for(const selector of ['#face-language','#switch-speaker','#text-input','#text-form button','#microphone'])$(selector).disabled=true;}
function enableConversationControls(){for(const selector of ['#face-language','#switch-speaker','#text-input','#text-form button','#microphone'])$(selector).disabled=false;}
// Each inactive conversation owns at most one fresh, microphone-free connection.
const preparedConversations=new Map();let pageClosing=false;
function disposePreparation(prepared){clearInterval(prepared?.heartbeat);clearTimeout(prepared?.expiry);if(prepared?.ws&&prepared.ws.readyState<2)prepared.ws.close();}
function conversationAuth(r,t){return {type:'auth',token:t,key:r.key,name:(catalog.languages.find(l=>l.code===speakingLanguage())?.labelJa||'ことば')+'の参加者',viewLanguage:r.mode==='face'?sharedLanguage():speakingLanguage(),language:speakingLanguage()};}
function prepareConversation(mode){
 const existing=preparedConversations.get(mode);if(existing)return existing.promise;
 const entry={};preparedConversations.set(mode,entry);
 entry.promise=(async()=>{
  const r={...await api('/rooms',{mode,unit:$('#unit').value||'数学'}),creator:true};
  const t=await token();if(pageClosing)throw Error('画面を閉じています。');const ws=new WebSocket(config.api.replace(/^http/,'ws')+'/rooms/'+r.id+'/socket');
  const prepared={room:r,ws,messages:[],createdAt:Date.now(),turn:mode==='interpreter'?requestTurnCredentials(r.id).catch(()=>null):null};entry.prepared=prepared;
  await new Promise((resolve,reject)=>{
   const timeout=setTimeout(()=>{disposePreparation(prepared);reject(Error('接続の準備に時間がかかっています。'));},12000);
   const fail=()=>{clearTimeout(timeout);reject(Error('接続を準備できませんでした。'));};
   ws.onopen=()=>ws.send(JSON.stringify(conversationAuth(r,t)));
   ws.onerror=fail;ws.onclose=fail;
   ws.onmessage=e=>{try{const data=JSON.parse(e.data);if(data.type==='error'){fail();return;}
    if(data.type==='ready'){prepared.messages.push(data);clearTimeout(timeout);resolve();}
    else if(data.type==='participants'){prepared.messages=prepared.messages.filter(m=>m.type!=='participants');prepared.messages.push(data);}
   }catch{fail();}};
  });
  ws.onerror=()=>{};ws.onclose=()=>{disposePreparation(prepared);if(preparedConversations.get(mode)===entry)preparedConversations.delete(mode);};
  prepared.heartbeat=setInterval(()=>{if(ws.readyState===1)ws.send(JSON.stringify({type:'ping'}));},20000);
  prepared.expiry=setTimeout(()=>{if(preparedConversations.get(mode)===entry){preparedConversations.delete(mode);disposePreparation(prepared);}},10*60000);
  return prepared;
 })().catch(error=>{disposePreparation(entry.prepared);if(preparedConversations.get(mode)===entry)preparedConversations.delete(mode);throw error;});
 return entry.promise;
}
async function takeConversation(mode){const prepared=await prepareConversation(mode);if(prepared.ws.readyState!==1){preparedConversations.delete(mode);disposePreparation(prepared);return takeConversation(mode);}preparedConversations.delete(mode);clearInterval(prepared.heartbeat);clearTimeout(prepared.expiry);return prepared;}
function warmConversation(mode){if(!pageClosing&&['face','interpreter'].includes(mode))void prepareConversation(mode).catch(()=>{});}
const roomPreparations=new Map();
let requestedMode='face',modeActivation=0,modeTransition=Promise.resolve();
function activateTab(next){if(next==='student')next='lesson';requestedMode=next;const activation=++modeActivation;if(next!==tab){sessionEpoch++;}modeTransition=modeTransition.catch(showConnectionError).then(async()=>{if(activation!==modeActivation)return;if(room&&room.mode!==next){const previous=room.mode;await leave(false);warmConversation(previous);}if(activation!==modeActivation)return;if(!room){await exitModeFullscreen();history.replaceState(null,'',location.pathname);}setTab(next);if(['face','interpreter'].includes(next)&&!room){const cached=preparedConversations.get(next)?.prepared;if(!cached||cached.ws.readyState!==1)showConversationPreparation(next);}if(['face','interpreter'].includes(next)&&tab===next&&!room)void create(next,{automatic:true});});return modeTransition;}
$$('[data-tab]').forEach(b=>{b.onclick=()=>void activateTab(b.dataset.tab);b.onkeydown=e=>{const tabs=$$('[data-tab]'),i=tabs.indexOf(b);let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();tabs[n].focus();void activateTab(tabs[n].dataset.tab);};});
async function initAuth(){try{const [a,b]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js')]);authApi=b;const auth=b.getAuth(a.initializeApp(config.firebase));await auth.authStateReady();if(!auth.currentUser)await b.signInAnonymously(auth);user=auth.currentUser;b.onAuthStateChanged(auth,u=>{user=u;});status('参加できます');}catch(e){status('接続できません');const failure=connectionFailure({code:'auth_unavailable'},{stage:'auth',endpoint:'https://identitytoolkit.googleapis.com',operation:'initial_auth'});connections.add({...failure.connection,online:navigator.onLine,sessions:ledger.list()});showConnectionError(failure);}}
void listHistory().catch(()=>{});const ready=initAuth();void ready.then(()=>{if(user)warmConversation('interpreter');});
void ready.then(async()=>{if(!user)return;try{catalog=withEasyJapanese(await api('/catalog'));try{localStorage.setItem('tsuyaku-catalog-v1',JSON.stringify(catalog));}catch{}fillLanguages();renderReferences();}catch{message('保存済みの辞書を使っています。');}});
async function token(){await ready;if(!user)throw Error('接続を確認してください。');return user.getIdToken();}
async function api(path,data,{signal}={}){let auth;try{auth=await token();}catch(error){const failure=connectionFailure({code:'auth_unavailable'},{stage:'auth',endpoint:'https://identitytoolkit.googleapis.com',operation:'token'});connections.add({...failure.connection,online:navigator.onLine,sessions:ledger.list()});throw failure;}const operation=({'/rooms':'room_create','/lessons/join':'lesson_join','/catalog':'catalog','/dictionary/translate':'dictionary_translate','/dictionary/candidate':'dictionary_candidate'})[path]||'other';return requestJson(config.api+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+auth,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(25000)]):AbortSignal.timeout(25000),referrerPolicy:'no-referrer'},{operation,onFailure:record=>{if(!signal?.aborted)connections.add({...record,online:navigator.onLine,sessions:ledger.list()});}});}
function showConnectionError(error){message(error.message);if(!error.connectionIssue)return;const button=el('button','接続を確認');button.onclick=showNetworkDiagnostics;$('#message').append(button);}
function showNetworkDiagnostics(){const n=el('div',undefined,'connection-diagnostics');n.append(el('p','QRコードが出る前の失敗は、参加の認証やルーム作成の通信が原因です。音声中継（TURN）より前の段階です。'));const rows=el('div'),report=el('textarea');report.rows=10;report.readOnly=true;report.setAttribute('aria-label','接続診断結果');const run=el('button','接続を確認'),copy=el('button','結果をコピー');n.append(run,copy,rows,report);const refresh=()=>{report.value=JSON.stringify({app:'通訳君',schema:'tsuyaku-connection-v1',exportedAt:new Date().toISOString(),pageOrigin:location.origin,online:navigator.onLine,authentication:user?'ready':'unavailable',checks:connections.list(),analysis:explainConnection(connections.list(),{authentication:user?'ready':'unavailable',online:navigator.onLine,sessions:ledger.list()}),note:'network_or_corsはブラウザーが理由を開示しない通信失敗。学校の制限・DNS・TLS・CORSのどれかは、この値だけでは断定できません。接続キー・token・発言・氏名は含みません。'},null,2);};const labels={api_simple:'字幕・翻訳サーバー',api_headers:'ルーム作成と同じ通信形式'};const results={ok:'接続できました',network_or_cors:'通信失敗（制限・CORSなど）',timeout:'時間切れ',http_error:'HTTPエラー',invalid_response:'アプリ用の応答ではありません'};run.onclick=async()=>{run.disabled=true;rows.replaceChildren(el('p','確認しています…'));try{const checks=await probeNetwork(config.api);checks.forEach(check=>connections.add({...check,online:navigator.onLine,sessions:ledger.list()}));rows.replaceChildren(...checks.map(check=>el('p',labels[check.stage]+'：'+results[check.code]+(check.status?'（'+check.status+'）':''))));const analysis=explainConnection(connections.list(),{authentication:user?'ready':'unavailable',online:navigator.onLine,sessions:ledger.list()});rows.append(el('h3','確認できた事実'),...analysis.facts.map(text=>el('p',text)),el('h3','原因の候補'),...analysis.candidates.map(item=>el('p',item.cause+'（'+item.confidence+'）：'+item.evidence)),el('h3','次の確認'),...analysis.nextSteps.map((text,i)=>el('p',(i+1)+'. '+text)),el('p',analysis.limitations));rows.append(el('p',checks.every(check=>check.code==='ok')?'この確認ではAPIへ接続できました。認証やルーム作成そのものの成功までは保証しません。':'この端末からAPIへ正常に接続できない項目があります。結果をコピーして、このチャットへ貼り付けてください。'));refresh();}finally{run.disabled=false;}};copy.onclick=async()=>{refresh();try{await navigator.clipboard.writeText(report.value);copy.textContent='コピーしました';}catch{report.focus();report.select();message('診断欄をコピーして、このチャットへ貼り付けてください。');}};refresh();modal('接続の確認',n);void run.onclick();}
async function exitModeFullscreen(){document.body.classList.remove("mode-active");delete document.body.dataset.activeMode;}
async function create(mode,{automatic=false}={}){const button=$('#create-'+mode);if(button.disabled)return;button.disabled=true;const creationEpoch=sessionEpoch,controller=new AbortController();roomPreparations.set(mode,controller);try{await ready;if(tab!==mode||room||sessionEpoch!==creationEpoch)return;if(mode==='face')faceSide='self';const prepared=['face','interpreter'].includes(mode)?await takeConversation(mode):null;const r=prepared?.room||await api('/rooms',{mode,unit:$('#unit').value||'数学'},{signal:controller.signal});if(tab!==mode||room||sessionEpoch!==creationEpoch){disposePreparation(prepared);warmConversation(mode);return;}await enter({...r,creator:true},prepared);if(mode==='interpreter')renderCallInvite();}catch(e){if(controller.signal.aborted||creationEpoch!==sessionEpoch)return;await exitModeFullscreen();showConnectionError(e);if(automatic&&mode==='face'&&tab==='face'&&!room){const retry=el('button','再試行');retry.onclick=()=>void activateTab('face');$('#message').append(retry);}}finally{if(roomPreparations.get(mode)===controller)roomPreparations.delete(mode);button.disabled=false;if(automatic&&requestedMode===mode&&tab===mode&&!room&&creationEpoch!==sessionEpoch)void activateTab(mode);}}
$('#create-face').onclick=()=>create('face');$('#create-interpreter').onclick=()=>create('interpreter');$('#unit').oninput=()=>{if(room?.mode==='lesson'&&room.creator)room.unit=$('#unit').value.trim()||'数学';};
async function enter(r,prepared=null){if(room||socket)await leave(false);enableConversationControls();callStarted=false;room=r;if(r.mode==='lesson')chooseLessonRole(r.creator?'teacher':'student');$('#lesson-theme').hidden=r.mode!=='lesson'||!r.creator;mountConversation(r.mode);updateLiveActions();scheduleRoomExpiry();message('');ledger.begin(r.mode,r.mode==='interpreter'?callCaptionLanguages($('#source-language').value):[r.mode==='lesson'?'ja':$('#face-self-language').value,sharedLanguage(),'en']);clearInterval(metricsTimer);metricsTimer=setInterval(()=>void sampleRtc(),15000);role=r.creator?'teacher':null;participants=[];$('#participants').replaceChildren();intentionalClose=false;records.clear();elements.clear();resetConversationContents();$$('[role=tabpanel]').forEach(n=>n.hidden=true);$('#live').hidden=false;$$('[data-tab]').forEach(b=>b.disabled=false);setTab(r.mode==='lesson'&&!r.creator?'student':r.mode);document.body.classList.add('mode-active');document.body.dataset.activeMode=r.mode;history.replaceState(null,'',r.mode!=='interpreter'?location.pathname:'#room='+r.id+'&key='+r.key+'&mode='+r.mode);await connect(prepared);refreshTimer=setInterval(async()=>{try{if(socket?.readyState===1)socket.send(JSON.stringify({type:'reauth',token:await user.getIdToken(true)}));}catch{message('ログインの更新に失敗しました。');}},45*60000);heartbeat=setInterval(()=>send({type:'ping'}),20000);}
async function connect(prepared=null){const epoch=sessionEpoch;const t=await token();if(!room||epoch!==sessionEpoch)return;clearTimeout(reconnectTimer);status('接続しています');turnReady=room.mode==='face'?Promise.resolve():prepared?.turn?prepared.turn.then(data=>{if(!data)return loadTurn();rtcConfig={iceServers:data.iceServers};}):loadTurn();const r=room,ws=prepared?.ws||new WebSocket(config.api.replace(/^http/,'ws')+'/rooms/'+r.id+'/socket');socket=ws;const current=()=>socket===ws&&epoch===sessionEpoch&&!!room;
 ws.onopen=()=>{if(!current())return;ws.send(JSON.stringify({type:'auth',token:t,key:r.key,name:(catalog.languages.find(l=>l.code===currentSource())?.labelJa||'ことば')+'の参加者',viewLanguage:r.mode==='face'?$('#face-other-language').value:r.mode==='lesson'?sharedLanguage():$('#source-language').value,language:r.mode==='face'?$('#face-self-language').value:r.mode==='lesson'?(role==='teacher'?'ja':sharedLanguage()):$('#source-language').value}));authTimer=setTimeout(()=>{if(current()&&connectedAt===null){ledger.event('auth_timeout');ws.close(4000,'authentication timeout');}},12000);};
 ws.onmessage=e=>{if(!current())return;try{void handle(JSON.parse(e.data)).catch(e=>message('接続を確認してください。 '+e.message));}catch{message('受信したデータを確認できませんでした。');}};
 ws.onerror=()=>{if(!current())return;ledger.event('socket_error',{online:navigator.onLine,visibility:document.visibilityState});status('再接続しています');};
 ws.onclose=e=>{if(!current()||intentionalClose)return;clearTimeout(authTimer);const now=Date.now();recoveryStartedAt??=now;reconnectAttempts++;const retryMs=navigator.onLine?retryDelay(reconnectAttempts):15000;ledger.event('reconnect',{code:e.code,wasClean:e.wasClean,openSeconds:connectedAt===null?0:(now-connectedAt)/1000,attempt:reconnectAttempts,retryMs,online:navigator.onLine,visibility:document.visibilityState});connectedAt=null;participants=[];$('#participants').replaceChildren();status('再接続しています');stopRecognition();for(const p of peers.values()){p.pc.close();p.audio.remove();}peers.clear();reconnectTimer=setTimeout(()=>void connect().catch(()=>ledger.event('reconnect_error')),retryMs);};if(prepared){for(const data of prepared.messages){if(current())await handle(data);}send({type:'language',language:currentSource()});}}
window.addEventListener('online',()=>{if(room&&socket?.readyState===3){clearTimeout(reconnectTimer);void connect();}});

function send(data){if(socket?.readyState!==1)return false;socket.send(JSON.stringify(data));return true;}
async function handle(data){
 if(data.type==='error'){ledger.event('server_error');message(data.error);return;}
 if(data.type==='ready'){clearTimeout(authTimer);connectedAt=Date.now();if(recoveryStartedAt!==null)ledger.event('connection_restored',{recoverySeconds:(connectedAt-recoveryStartedAt)/1000,attempt:reconnectAttempts});recoveryStartedAt=null;reconnectAttempts=0;selfId=data.id;role=data.role;room.mode=data.mode;room.code=data.code||room.code;room.expires=data.expires||room.expires;scheduleRoomExpiry();updateLessonCode();room.unit=data.unit;updateFace();updateLiveActions();status('接続中');$('#microphone').hidden=room.mode==='lesson'&&role!=='teacher';$('#text-form').hidden=room.mode==='lesson'&&role!=='teacher';$('#invite').hidden=true;renderCallInvite();for(const r of data.history||[])renderCaption(r);for(const p of pending.values())send(p);await turnReady;if(data.ended){await handle({type:'ended'});return;}if(mic)startRecognition();return;}
 if(data.type==='participants'){if(room.mode==='face')return;participants=data.participants||[];if(room.mode==='interpreter'&&participants.some(p=>p.id!==selfId))callStarted=true;updateLiveActions();$('#participants').replaceChildren(...participants.map(p=>el('span',(p.id===selfId?'あなた':p.name)+(p.role==='teacher'&&room.mode==='lesson'?'・先生':''),'participant')));if(room.mode==='interpreter'&&participants.some(p=>p.id!==selfId)&&$('#modal').open&&$('#modal').dataset.kind==='invite')$('#modal').close();for(const [id,p] of peers){if(!participants.some(x=>x.id===id)){p.pc.close();p.audio.remove();peers.delete(id);}}const epoch=sessionEpoch;await turnReady;if(epoch!==sessionEpoch||!room)return;for(const p of participants){if(p.id===selfId)continue;if(room.mode==='interpreter'&&selfId<p.id||room.mode==='lesson'&&role==='teacher')await offer(p.id);}return;}
 if(data.type==='signal'){await turnReady;await signal(data.from,data.signal);return;}
 if(data.type==='caption')return;
 if(data.type==='translation'){data.updating=false;data.memorySource=data.memorySource||null;const rawId=[...localTimings.keys()].find(key=>{const t=localTimings.get(key);return data.id===selfId+'_'+(t.id||key)&&(t.revision??0)===(data.revision??0);});if(rawId){if(data.status==='ready'){const metrics=latencyFromTiming(localTimings.get(rawId),Date.now());ledger.timing(data.id+':'+(data.revision??0),metrics);}localTimings.delete(rawId);}ledger.caption(data);if(data.id.startsWith(selfId+'_')&&personalPhrases.observe(data))renderReferences();if(data.status==='ready')for(const id of data.usage?.bankKeys||[])void api('/dictionary/usage',{kind:'bank',id}).catch(()=>{});if(data.status==='failed'){const previous=records.get(data.id);if(previous?.status==='ready')renderCaption({...previous,updating:false});}renderCaption(data);if((data.revision??0)>=(records.get(data.id)?.revision??0))records.set(data.id,data);if(data.status==='failed')showTranslationFailure(data);for(const [id,p] of pending){if(data.id.endsWith('_'+id)&&(data.revision??0)>=(p.revision??0))pending.delete(id);}return;}
 if(data.type==='notice'){message(data.text);return;}
 if(data.type==='ended'){ledger.event('lesson_ended');await leave(true);message('授業が終了しました。');return;}
}
async function requestTurnCredentials(roomId){const data=await requestJson(config.turn,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({callId:roomId||'tsuyaku',clientId:crypto.randomUUID()}),signal:AbortSignal.timeout(8000)},{stage:'turn',operation:'turn_credentials',onFailure:record=>connections.add({...record,online:navigator.onLine,sessions:ledger.list()})});if(!Array.isArray(data.iceServers)||!data.iceServers.some(server=>[server.urls].flat().some(url=>/^turns?:/.test(url))))throw connectionFailure({code:'no_turn_server'},{stage:'turn',endpoint:config.turn,operation:'turn_credentials'});return data;}
async function loadTurn(){rtcConfig={iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]};try{const data=await requestTurnCredentials(room?.id);if(!Array.isArray(data.iceServers)||!data.iceServers.some(server=>[server.urls].flat().some(url=>/^turns?:/.test(url))))throw connectionFailure({code:'no_turn_server'},{stage:'turn',endpoint:config.turn,operation:'turn_credentials'});rtcConfig={iceServers:data.iceServers};connections.add({stage:'turn',endpoint:config.turn,operation:'turn_credentials',code:'ok',online:navigator.onLine,sessions:ledger.list()});}catch(error){if(!error.connectionIssue)connections.add({stage:'turn',endpoint:config.turn,operation:'turn_credentials',code:'http_error',status:error.httpStatus,online:navigator.onLine,sessions:ledger.list()});else if(error.connection?.code==='no_turn_server')connections.add({...error.connection,online:navigator.onLine,sessions:ledger.list()});message('音声の中継を利用できません。字幕は利用できますが、音声は直接接続のみになります。');const button=el('button','接続を確認');button.onclick=showNetworkDiagnostics;$('#message').append(button);}}
function peer(id){if(peers.has(id))return peers.get(id);const pc=new RTCPeerConnection(rtcConfig),audio=el('audio');audio.autoplay=false;audio.muted=true;audio.setAttribute('playsinline','');document.body.append(audio);const p={pc,audio,metricsId:crypto.randomUUID(),ice:[],offering:false};peers.set(id,p);pc.onicecandidate=e=>{if(e.candidate)send({type:'signal',to:id,signal:{candidate:e.candidate}});};pc.ontrack=e=>{audio.srcObject=e.streams[0]||new MediaStream([e.track]);};pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed'){ledger.event('rtc_failed');if(role==='teacher'||selfId<id){pc.restartIce();void offer(id,true);}}};if(localStream&&(room.mode==='interpreter'||role==='teacher'))localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));else pc.addTransceiver('audio',{direction:'recvonly'});return p;}
async function offer(id,restart=false){const p=peer(id);if(p.offering||p.pc.signalingState!=='stable')return;if(p.pc.currentLocalDescription&&!restart)return;p.offering=true;try{await p.pc.setLocalDescription(await p.pc.createOffer({iceRestart:restart}));send({type:'signal',to:id,signal:{description:p.pc.localDescription}});}catch(e){message('音声の接続に失敗しました。 '+e.message);}finally{p.offering=false;}}
async function signal(id,data){const p=peer(id);try{if(data.description){const polite=selfId>id||room.mode==='lesson'&&role!=='teacher';if(data.description.type==='offer'&&(p.offering||p.pc.signalingState!=='stable')){if(!polite)return;await p.pc.setLocalDescription({type:'rollback'});}await p.pc.setRemoteDescription(data.description);for(const candidate of p.ice.splice(0))await p.pc.addIceCandidate(candidate);if(data.description.type==='offer'){await p.pc.setLocalDescription(await p.pc.createAnswer());send({type:'signal',to:id,signal:{description:p.pc.localDescription}});}}else if(data.candidate){if(p.pc.remoteDescription)await p.pc.addIceCandidate(data.candidate);else p.ice.push(data.candidate);}}catch(e){message('音声接続を確認してください。 '+e.message);}}
async function ensureMicrophone(){const epoch=sessionEpoch;if(!localStream)localStream=await acquireMicrophone(()=>navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false}),()=>!!room&&epoch===sessionEpoch);for(const [id,p] of peers){const sender=p.pc.getSenders().find(s=>s.track?.kind==='audio'),transceiver=p.pc.getTransceivers().find(t=>t.receiver.track.kind==='audio');if(sender)await sender.replaceTrack(localStream.getAudioTracks()[0]);else if(transceiver){await transceiver.sender.replaceTrack(localStream.getAudioTracks()[0]);transceiver.direction='sendrecv';}else p.pc.addTrack(localStream.getAudioTracks()[0],localStream);await offer(id,true);}return localStream;}
let microphoneStarting=false;
$('#microphone').onclick=async()=>{if(!room||microphoneStarting)return;const epoch=sessionEpoch,button=$('#microphone');microphoneStarting=true;button.disabled=true;try{if(!mic){paintButton(button,'マイクを準備しています','microphone');await ensureMicrophone();if(!room||sessionEpoch!==epoch)return;mic=true;localStream.getAudioTracks().forEach(t=>t.enabled=true);startRecognition();}else{mic=false;stopRecognition(true);localStream?.getAudioTracks().forEach(t=>t.enabled=false);}ledger.microphone(mic);ledger.event(mic?'mic_on':'mic_off');paintButton(button,mic?'マイクをとめる':'マイクをONにする',mic?'microphone':'microphone-slash');button.setAttribute('aria-pressed',mic);}catch(e){if(sessionEpoch!==epoch)return;mic=false;stopRecognition();localStream?.getAudioTracks().forEach(t=>t.enabled=false);button.setAttribute('aria-pressed','false');paintButton(button,'マイクをONにする','microphone');ledger.microphone(false);ledger.event('microphone_error');message(e.name==='TimeoutError'?e.message:'マイクを許可して、もう一度押してください。 '+e.message);}finally{microphoneStarting=false;button.disabled=false;}};
function stopRecognition(finish=false){clearTimeout(recognitionRetryTimer);restarting=false;const previous=recognition;if(finish)previous?.finishFragment?.();recognition=null;previous?.abort();}
function startRecognition(fallback=false){stopRecognition();if(!fallback)recognitionRetries=0;if(!mic||!room)return;const lang=spokenLanguage(currentSource()),side=faceSide;const factory=createServerRecognition({endpoint:config.api+'/transcribe?language='+encodeURIComponent(lang),getStream:()=>localStream,getToken:token,onUsage:seconds=>ledger.audio(seconds,'whisper'),onDiagnostic:result=>connections.add({stage:'api',operation:'transcribe',endpoint:config.api,...result,online:navigator.onLine})});recognition=new factory();const activeRecognition=recognition;recognition.setHints?.(()=>[...recognitionHints(catalog,lang,room?.unit||''),...translationMemory.hints(room?.unit||'')]);const prefix=crypto.randomUUID().slice(0,8);recognition.onresult=e=>{if(recognition!==activeRecognition)return;recognitionRetries=0;const r=e.results[e.resultIndex];if(!r?.[0]?.transcript?.trim())return;const cap={type:'caption',id:prefix+'_'+e.resultIndex,text:r[0].transcript,final:r.isFinal,revision:e.revision??0,continuing:e.continuing===true,metadataOnly:e.metadataOnly===true,...(room?.mode==='face'?speakerCaption(side,$('#face-self-language').value,$('#face-other-language').value):{})};if(r.isFinal){const now=Date.now();if(!e.metadataOnly)localTimings.set(cap.id+':'+cap.revision,{id:cap.id,revision:cap.revision,kind:'speech',speechStartedAt:e.speechStartedAt,speechEndedAt:e.speechEndedAt,recognitionReadyAt:e.recognitionReadyAt??now,sentAt:now});pending.set(cap.id,cap);}submitCaption(cap,true);};recognition.onerror=e=>{if(recognition!==activeRecognition)return;ledger.event('recognition_error',{recognitionCode:['network','auth','quota','billing','input','model','service','timeout','overloaded','interrupted','audio-capture'].includes(e?.error)?e.error:'unknown'});if(['network','service','timeout','overloaded','interrupted'].includes(e?.error)&&mic&&room&&recognitionRetries<3){const attempt=++recognitionRetries,activeRoom=room;stopRecognition();ledger.event('asr_restart',{attempt});message('音声認識をつなぎ直しています。');recognitionRetryTimer=setTimeout(()=>{if(mic&&room===activeRoom)startRecognition(true);},Math.min(4000,1000*attempt));return;}{ledger.event('asr_error');ledger.microphone(false);message(e.message||'字幕の接続が途切れました。マイクを押し直すか文字で伝えてください。');mic=false;stopRecognition();localStream?.getAudioTracks().forEach(t=>t.enabled=false);paintButton($('#microphone'),'マイクをONにする','microphone');$('#microphone').setAttribute('aria-pressed','false');}};recognition.onrecovering=e=>{if(recognition!==activeRecognition)return;ledger.event(e?.reason==='queue_overflow'?'asr_queue_drop':'asr_retry');message(e?.reason==='queue_overflow'?'認識待ちが増えました。マイクは継続しています。短く区切ってもう一度話してください。':'音声認識の通信を再試行しています。もう一度話してください。');};recognition.onend=()=>{if(recognition!==activeRecognition)return;if(mic&&room&&!restarting){restarting=true;setTimeout(()=>{if(mic&&room)startRecognition(fallback);},1000);}};recognition.start();}


const speechPlayer=new SpeechPlayer({engine:window.speechSynthesis,Utterance:window.SpeechSynthesisUtterance,onChange:updateSpeechControls,onError:error=>message(error==='unsupported'?'この端末では読み上げを使えません。':'読み上げを再生できませんでした。対応する音声が端末にあるか確認してください。')});
$('#modal').addEventListener('close',()=>speechPlayer.stop());
function updateSpeechControls(){for(const group of $$('[data-speech-key]')){const active=group.dataset.speechKey===speechPlayer.key,play=group.querySelector('[data-play]'),stop=group.querySelector('[data-stop]');const action=active?(speechPlayer.paused?'再開':'一時停止'):'再生';group.dataset.speechState=active?(speechPlayer.paused?'paused':'playing'):'idle';play.replaceChildren(icon(active&&!speechPlayer.paused?'pause':'play'));if(group.dataset.visibleSpeechLabel)play.append(el('span',group.dataset.visibleSpeechLabel+'を'+action));play.setAttribute('aria-label',group.dataset.speechLabel+(active?(speechPlayer.paused?'の読み上げを再開':'の読み上げを一時停止'):'を読み上げる'));play.title=group.dataset.speechLabel+'を'+action;stop.hidden=!active;}}
function speechControls(text,lang,key,labeled=false){const group=el('div',undefined,'speech-controls'),play=el('button'),stop=el('button');group.dataset.speechKey=key;if(labeled){group.classList.add('speech-controls-labeled');group.dataset.visibleSpeechLabel=catalog.languages.find(l=>l.code===lang)?.labelJa||lang;stop.append(el('span','停止'));}group.dataset.speechLabel=(catalog.languages.find(l=>l.code===lang)?.labelJa||lang)+'の文';play.dataset.play='';stop.dataset.stop='';play.append(icon('play'));stop.append(icon('stop'));stop.hidden=true;play.type=stop.type='button';play.setAttribute('aria-label',group.dataset.speechLabel+'を読み上げる');stop.setAttribute('aria-label',group.dataset.speechLabel+'の読み上げを停止');stop.title='停止';play.onclick=()=>speechPlayer.toggle(key,text,catalog.languages.find(l=>l.code===lang)?.speechCode||lang);stop.onclick=()=>speechPlayer.stop();group.append(play,stop);return group;}

function renderCaption(r){const old=records.get(r.id)||{};if((r.revision??0)<(old.revision??0))return;const next={...old,...r};if(!isDisplayableCaption(next))return;const view=sharedLanguage();const codes=room?.mode==='interpreter'?callCaptionLanguages($('#source-language').value):[...new Set(room?.mode==='face'?['ja',$('#face-self-language').value,$('#face-other-language').value,'en']:['ja',view,'en'])];const lines=codes.map(code=>({code,text:next.translations?.[code]||(code===next.source?next.text:'')})).filter(line=>line.text);if(!lines.length)return;const nearBottom=$('#captions').scrollHeight-$('#captions').scrollTop-$('#captions').clientHeight<100;let article=elements.get(r.id);if(!article){$('#captions .empty')?.remove();article=el('article',undefined,'caption');elements.set(r.id,article);$('#captions').append(article);}article.className='caption';article.replaceChildren();const meta=el('div',undefined,'caption-meta');meta.append(el('span',next.speaker||'参加者'));if(next.updating)meta.append(el('span','訳を更新中…','caption-progress'));if(next.memorySource)meta.append(el('span',next.memorySource==='spreadsheet'?'辞書の訳':'確認した訳','caption-memory'));if(next.id.startsWith(selfId+'_')&&next.source==='ja'&&next.status==='ready'&&!next.continuing&&!next.updating){const edit=el('button',undefined,'secondary');edit.type='button';edit.setAttribute('aria-label','日本語を直す');edit.title='日本語を直す';edit.append(icon('pen'));edit.onclick=()=>editJapanese(next);meta.append(edit);}if(next.continuing)meta.append(el('span','続きのことばを待っています','caption-progress'));if(next.source==='ja'&&next.status==='ready'&&!next.continuing&&!next.updating){const save=el('button',undefined,'secondary');save.type='button';save.setAttribute('aria-label','訳を確認して覚える');save.title='訳を確認して覚える';save.append(icon('book-medical'));save.onclick=()=>phraseCandidate(next);meta.append(save);}if(next.latencyMs)meta.title='翻訳処理 '+(next.latencyMs/1000).toFixed(1)+'秒';article.append(meta);for(const {code,text} of lines){const primaryCode=room?.mode==='face'?(next.speaker==='相手'?$('#face-self-language').value:$('#face-other-language').value):room?.mode==='interpreter'?$('#source-language').value:view;const line=el('div',undefined,'caption-line'+(code===primaryCode?' caption-line-primary':''));line.append(el('small',catalog.languages.find(l=>l.code===code)?.labelJa||code),el('p',text),speechControls(text,code,next.id+':'+code));article.append(line);}records.set(r.id,next);updateSpeechControls();if(nearBottom)$('#captions').scrollTop=$('#captions').scrollHeight;}
$('#text-form').onsubmit=e=>{e.preventDefault();const text=$('#text-input').value.trim();if(!text)return;const cap={...(room.mode==='face'?speakerCaption(faceSide,$('#face-self-language').value,$('#face-other-language').value):{}),type:'caption',id:crypto.randomUUID(),text,final:true};localTimings.set(cap.id,{kind:'text',sentAt:Date.now()});pending.set(cap.id,cap);if(submitCaption(cap))$('#text-input').value='';else message('再接続後に送信します。');};
function inviteLink(){const url=new URL(location.href);url.hash=new URLSearchParams({room:room.id,key:room.key,mode:room.mode}).toString();return url.href;}
function renderCallInvite(){const n=$('#call-invite');if(!room||room.mode!=='interpreter'||!room.creator){n.hidden=true;n.replaceChildren();return;}n.hidden=false;if(n.dataset.room===room.id)return;n.dataset.room=room.id;n.replaceChildren();const input=el('input');input.readOnly=true;input.value=inviteLink();input.setAttribute('aria-label','相手に送るリンク');const language=el('select');options(language,$('#source-language').value);language.onchange=()=>setSpeakingLanguage(language.value);n.append(label('じぶんが話すことば',language));const canvas=el('canvas');canvas.className='qr';canvas.setAttribute('aria-label','通話に参加するQRコード');n.append(canvas);void qrModule.then(m=>m?.drawQr(canvas,input.value)).catch(()=>{});const linkArea=el('div',undefined,'invite-link-area');const linkLabel=el('label','相手に送るリンク');input.id='call-invite-link';linkLabel.htmlFor=input.id;const row=el('div',undefined,'invite-link-row');const copy=el('button',undefined,'invite-copy');copy.type='button';copy.setAttribute('aria-label','リンクをコピー');copy.title='リンクをコピー';copy.append(icon('copy'));copy.onclick=async()=>{try{await navigator.clipboard.writeText(input.value);copy.replaceChildren(icon('check'));copy.setAttribute('aria-label','コピーしました');copy.title='コピーしました';setTimeout(()=>{copy.replaceChildren(icon('copy'));copy.setAttribute('aria-label','リンクをコピー');copy.title='リンクをコピー';},2000);}catch{input.select();message('招待リンクをコピーしてください。');}};row.append(input,copy);linkArea.append(linkLabel,row);n.append(linkArea);}
function download(name,text,type='text/csv;charset=utf-8'){const a=el('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function showTranslationFailure(data){connections.add({stage:'api',operation:'translation',code:'http_error',endpoint:config.api,aiReason:data.aiFailure?.reason,aiCode:data.aiFailure?.code,aiEvidence:data.aiFailure?.evidence,aiModel:data.aiFailure?.model,online:navigator.onLine});message(data.error||'翻訳できませんでした。');if(!data.id.startsWith(selfId+'_')||['quota','billing','auth','input'].includes(data.aiFailure?.reason))return;const retry=el('button','再試行');retry.onclick=()=>{send({type:'caption',id:data.id.slice(selfId.length+1),text:data.text,final:true,...(room?.mode==='face'?{source:data.source,speakerSide:data.speaker==='相手'?'other':'self'}:{})});message('翻訳を再試行しています。');};$('#message').append(retry);}


async function leave(show=true){const previousMode=room?.mode;intentionalClose=true;if(socket?.readyState===1)send({type:'leave'});stopRecognition();localStream?.getAudioTracks().forEach(t=>t.enabled=false);speechPlayer.stop();await sampleRtc();ledger.end();clearInterval(metricsTimer);clearTimeout(roomExpiryTimer);sessionEpoch++;intentionalClose=true;clearTimeout(reconnectTimer);clearTimeout(authTimer);reconnectAttempts=0;recoveryStartedAt=null;connectedAt=null;localTimings.clear();clearInterval(refreshTimer);clearInterval(heartbeat);stopRecognition();mic=false;socket?.close();socket=null;for(const p of peers.values()){p.pc.close();p.audio.remove();}peers.clear();localStream?.getTracks().forEach(t=>t.stop());localStream=null;pending.clear();participants=[];$('#participants').replaceChildren();if($('#modal').dataset.kind==='invite')$('#modal').close();room=null;callStarted=false;$('#leave').hidden=true;if(previousMode)warmConversation(previousMode);resetConversationContents();records.clear();elements.clear();$('#call-invite').hidden=true;$('#call-invite').replaceChildren();delete $('#call-invite').dataset.room;$('#panel-interpreter>.entry-card').hidden=false;$('#panel-face').append($('#live'));updateFace();updateLessonCode();paintButton($('#microphone'),'マイクをONにする','microphone');$('#microphone').setAttribute('aria-pressed','false');$('#microphone').disabled=false;if(show){enableConversationControls();if(tab==='lesson')chooseLessonRole(null);await exitModeFullscreen();lastJoinCode='';$('#live').hidden=true;$$('[data-tab]').forEach(b=>b.disabled=false);setTab(tab);history.replaceState(null,'',location.pathname);status('退室しました');if(['face','interpreter'].includes(tab))void activateTab(tab);}}
$('#leave').onclick=()=>{if(role==='teacher'&&room?.mode==='lesson'){const n=el('div');n.append(el('p','授業をおわると、生徒にことばが届かなくなります。'));const end=el('button','授業をおわる');end.onclick=()=>{send({type:'end'});$('#modal').close();setTimeout(()=>void leave(),200);};const exit=el('button','じぶんだけホームにもどる');exit.onclick=()=>{$('#modal').close();void leave();};n.append(end,exit);modal('授業をおわりますか？',n);}else void leave();};
window.addEventListener('pagehide',()=>{pageClosing=true;for(const entry of preparedConversations.values())disposePreparation(entry.prepared);preparedConversations.clear();ledger.end();void leave(false);});
async function sampleRtc(){for(const [id,p]of peers){try{const report=await p.pc.getStats();let pair;for(const v of report.values())if(v.type==='transport'&&v.selectedCandidatePairId)pair=report.get(v.selectedCandidatePairId);if(!pair)for(const v of report.values())if(v.type==='candidate-pair'&&v.state==='succeeded'&&v.nominated)pair=v;let lost=0,jitterMs=0;for(const v of report.values())if(v.type==='inbound-rtp'&&v.kind==='audio'){lost+=v.packetsLost||0;jitterMs=Math.max(jitterMs,(v.jitter||0)*1000);}if(pair)ledger.rtc(p.metricsId,{bytes:(pair.bytesSent||0)+(pair.bytesReceived||0),relay:report.get(pair.localCandidateId)?.candidateType==='relay'||report.get(pair.remoteCandidateId)?.candidateType==='relay',lost,jitterMs,rttMs:Number.isFinite(pair.currentRoundTripTime)?pair.currentRoundTripTime*1000:undefined});}catch{}}ledger.save();}
const referenceTranslations=new Map();
function showReference(row,type){
 if(!String(row.id||'').startsWith('personal-'))void api('/dictionary/usage',{kind:type==='phrase'?'phrase':'term',id:row.id}).catch(()=>{});
 const lang=sharedLanguage(),n=el('div',undefined,'reference-detail'),ja=type==='phrase'?row.jaText:row.descriptionJa||row.ja||row.title,en=type==='phrase'?row.enText:row.enText||row.en,translated=translationOf(row,lang);
 const addLanguage=(code,text)=>{const section=el('section',undefined,'reference-language'),heading=el('div',undefined,'reference-language-heading'),name=catalog.languages.find(l=>l.code===code)?.labelJa||code;const title=el('h3',name);title.id='reference-language-'+code;section.setAttribute('aria-labelledby',title.id);heading.append(title);if(text)heading.append(speechControls(text,code,'reference:'+type+':'+(row.id||row.ja||row.title)+':'+code));section.append(heading,el('p',text||'この言語の訳はスプレッドシートにまだ登録されていません。',text?'reference-language-text':'reference-missing'));n.append(section);};
 if(ja)addLanguage('ja',ja);if(lang!=='ja')addLanguage(lang,translated);if(en&&lang!=='en')addLanguage('en',en);const improve=el('button','訳の追加・修正', 'secondary');improve.prepend(icon('pen'));improve.onclick=()=>candidateForm(row.jaText||row.ja||row.title,lang,translated);n.append(improve);modal(row.title||row.ja,n);if(type==='term'&&row.reading){const reading=el('span',row.reading,'modal-reading');reading.id='modal-reading';$('#modal-title').after(reading);}updateSpeechControls();
}
const personalPhrases=new PersonalPhrases(localStorage);
const translationMemory=new TranslationMemory(localStorage);
const referenceCategory={phrase:'すべて',term:'すべて'};
function referenceCategoryName(row){return String(row.category||row.subject||'その他').trim()||'その他';}
const referenceVisibleLimits=new Map();
function renderReferences(){for(const [type,list,q,rawRows]of[['phrase',$('#phrase-list'),$('#phrase-search').value,[...personalPhrases.list(),...catalog.phrases]],['term',$('#term-list'),$('#term-search').value,[...personalPhrases.list('term'),...catalog.glossary,...catalog.terms]]]){
 const rows=[...new Map(rawRows.map(r=>[r.jaText||r.ja||r.title,r])).values()];const categories=[...new Set(rows.map(referenceCategoryName))].sort((a,b)=>a==='あなたのよく使う文'?-1:b==='あなたのよく使う文'?1:a.localeCompare(b,'ja'));
 if(!categories.includes(referenceCategory[type]))referenceCategory[type]='すべて';
 const filters=$('#'+type+'-categories');filters.replaceChildren(...['すべて',...categories].map(name=>{const button=el('button',name,'category-filter');button.type='button';button.setAttribute('aria-pressed',String(referenceCategory[type]===name));button.onclick=()=>{const oldLeft=filters.scrollLeft;referenceCategory[type]=name;renderReferences();filters.scrollLeft=oldLeft;const selected=[...filters.children].find(b=>b.textContent===name);if(selected){const target=selected.offsetLeft-filters.offsetLeft+selected.offsetWidth/2-filters.clientWidth/2;if(target>=0&&target<=filters.scrollWidth-filters.clientWidth)filters.scrollTo({left:target,behavior:'smooth'});}};return button;}));
 const query=q.normalize('NFKC').trim().toLowerCase();const found=rows.filter(r=>JSON.stringify(r).normalize('NFKC').toLowerCase().includes(query)&&(referenceCategory[type]==='すべて'||referenceCategoryName(r)===referenceCategory[type]));
 list.replaceChildren();for(const category of categories){const groupRows=found.filter(r=>referenceCategoryName(r)===category).sort((a,b)=>(Number(b.useCount)||Number(b.viewCount)||0)-(Number(a.useCount)||Number(a.viewCount)||0));if(!groupRows.length)continue;
 const section=el('section',undefined,'reference-group'),heading=el('h3',category,'reference-group-title');heading.append(el('span',String(groupRows.length),'reference-group-count'));const cards=el('div',undefined,'reference-group-cards');
 const limitKey=JSON.stringify([type,referenceCategory[type],query,category]);const pageSize=referenceCategory[type]==='すべて'&&!query?3:12;const visibleLimit=referenceVisibleLimits.get(limitKey)||pageSize;
 for(const row of groupRows.slice(0,visibleLimit)){const card=el('button',undefined,'reference-card');card.type='button';const left=el('span',undefined,'reference-copy');left.append(el('span',row.title||row.ja,'reference-title'));if(type==='term'&&row.reading)left.append(el('span',row.reading,'reference-reading'));const badge=el('span',category,'reference-category');const arrow=el('i',undefined,'fa-solid fa-chevron-right');arrow.setAttribute('aria-hidden','true');card.append(left,badge,arrow);card.onclick=()=>showReference(row,type);cards.append(card);}section.append(heading,cards);if(groupRows.length>visibleLimit){const more=el('button',`あと${groupRows.length-visibleLimit}件 · 続きを見る`,'reference-more');more.type='button';more.setAttribute('aria-label',category+'の続きを見る');more.onclick=()=>{referenceVisibleLimits.set(limitKey,visibleLimit+pageSize);renderReferences();};section.append(more);}if(visibleLimit>pageSize){const less=el('button','少なく表示','reference-less');less.type='button';less.setAttribute('aria-label',category+'を少なく表示');less.onclick=()=>{referenceVisibleLimits.delete(limitKey);renderReferences();$('#'+type+'-list').querySelectorAll('.reference-group')[categories.filter(c=>found.some(r=>referenceCategoryName(r)===c)).indexOf(category)]?.scrollIntoView({block:'nearest'});};section.append(less);}list.append(section);
 }if(!found.length)list.append(el('p','見つかりませんでした。'));
}}
for(const type of ['phrase','term']){const categoryStrip=$('#'+type+'-categories');categoryStrip.addEventListener('wheel',event=>{if(event.ctrlKey||categoryStrip.scrollWidth<=categoryStrip.clientWidth)return;const delta=Math.abs(event.deltaX)>Math.abs(event.deltaY)?event.deltaX:event.deltaY;const unit=event.deltaMode===1?16:event.deltaMode===2?categoryStrip.clientWidth:1;const next=Math.max(0,Math.min(categoryStrip.scrollWidth-categoryStrip.clientWidth,categoryStrip.scrollLeft+delta*unit));if(next!==categoryStrip.scrollLeft){event.preventDefault();categoryStrip.scrollLeft=next;}},{passive:false});const input=$('#'+type+'-search'),clear=$('#clear-'+type);input.oninput=()=>{if(clear)clear.hidden=!input.value;renderReferences();};if(clear)clear.onclick=()=>{input.value='';clear.hidden=true;renderReferences();input.focus();};}renderReferences();
function candidateForm(word='',language=sharedLanguage(),value=''){const n=el('form'),term=el('input'),tr=el('textarea'),lang=el('select');term.maxLength=80;tr.maxLength=500;term.value=word.slice(0,80);tr.value=value;options(lang,language);n.append(label('ことば',term),label('訳',tr),label('言語',lang),el('p','内容を確認して送ってください。個人情報は入れないでください。確認後に共有辞書へ反映します。','reference-category'));const b=el('button','候補として送る');b.type='submit';n.append(b);n.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await api('/dictionary/candidate',{term:term.value,translation:tr.value,language:lang.value});message('スプレッドシートに候補を追加しました。');$('#modal').close();}catch(e){message(e.message);}finally{b.disabled=false;}};modal('ことば・訳の候補',n);}

function phraseCandidate(record){const n=el('form'),source=el('textarea');source.value=record.text;source.readOnly=true;n.append(label('日本語の原文',source));const inputs=[];for(const [code,value] of Object.entries(record.translations||{})){if(code==='ja')continue;const input=el('textarea');input.value=value;input.maxLength=1500;inputs.push([code,input]);n.append(label(catalog.languages.find(l=>l.code===code)?.labelJa||code,input));}const values=()=>Object.fromEntries(inputs.map(([code,input])=>[code,input.value.trim()]));const remember=el('button','この訳を覚える','primary');remember.type='submit';n.append(remember,el('p','確認した訳を、この端末の次の通訳で使います。','reference-category'));n.onsubmit=e=>{e.preventDefault();const translations={ja:record.text,...values()};if(!translationMemory.remember('ja',record.text,translations,room?.unit||'')){message('覚える訳を入力してください。');return;}personalPhrases.confirm({...record,translations});renderReferences();renderCaption({...record,translations,memorySource:'reviewed'});message('確認した訳を覚えました。');$('#modal').close();};const share=el('button','共有辞書の候補に送る','secondary');share.type='button';share.onclick=async()=>{share.disabled=true;try{await api('/dictionary/phrase',{text:record.text,translations:values()});message('文例の候補をスプレッドシートに追加しました。');$('#modal').close();}catch(e){message(e.message);}finally{share.disabled=false;}};n.append(share,el('p','共有する場合は、人名や連絡先を取り除いてください。候補は確認後に共有辞書へ反映します。','reference-category'));modal('訳を確認して覚える',n);}
function editJapanese(record){record={...record,revision:Math.max(record.revision??0,records.get(record.id)?.revision??0)};const form=el('form'),input=el('textarea');input.value=record.text;input.maxLength=480;input.required=true;const check=el('input');check.type='checkbox';form.append(label('日本語を直す',input),label('次から同じ聞き間違いを直す',check));const button=el('button','直して翻訳する','primary');button.type='submit';form.append(button);form.onsubmit=e=>{e.preventDefault();const text=input.value.trim();if(!text)return;if(records.get(record.id)?.revision!==record.revision){message('字幕が更新されました。もう一度開いてください。');return;}if(check.checked)translationMemory.correct(record.text,text,room?.unit||'');personalPhrases.discard(record.text,record.id);const cap={type:'caption',id:record.id.slice(selfId.length+1),text,final:true,revision:(record.revision??0)+1,...(room?.mode==='face'?{source:record.source,speakerSide:record.speaker==='相手'?'other':'self',speaker:record.speaker}:{})};localTimings.set(cap.id+':'+cap.revision,{id:cap.id,revision:cap.revision,kind:'text',sentAt:Date.now()});renderCaption({...record,updating:true});submitCaption(cap);$('#modal').close();};modal('聞き取った日本語を直す',form);}
function submitCaption(cap,speech=false){const source=cap.source||currentSource(),unit=room?.unit||'';if(speech&&source==='ja')cap.text=translationMemory.corrected(cap.text,unit);const previous=records.get(selfId+'_'+cap.id);if(room?.mode==='face'&&cap.final){const targets=[...new Set(['ja',$('#face-self-language').value,$('#face-other-language').value,'en'])].filter(c=>c!==source);const cached=translationMemory.lookup(source,cap.text,targets,unit,catalog);if(cached){const same=cap.metadataOnly&&previous?.memorySource&&previous.text===cap.text;void handle({type:'translation',id:selfId+'_'+cap.id,source,text:cap.text,speaker:cap.speaker||(cap.speakerSide==='other'?'相手':previous?.speaker||'自分'),translations:cached.translations,status:'ready',final:true,revision:cap.revision??0,continuing:cap.continuing===true,at:Date.now(),latencyMs:0,memorySource:cached.source,usageId:same?previous.usageId:'local-'+cap.id+'-'+(cap.revision??0),usage:{inputTokens:0,outputTokens:0,cacheHit:true}});return true;}}if(cap.final)pending.set(cap.id,cap);return send(cap);}

const invite=new URLSearchParams(location.hash.slice(1));if(/^[a-f0-9]{32}$/.test(invite.get('room')||'')&&/^[a-f0-9]{32}$/.test(invite.get('key')||'')){const n=el('div'),lang=el('select');options(lang,$('#source-language').value);n.append(label('話すことば',lang));const b=el('button','参加する');b.onclick=async()=>{b.disabled=true;try{setSpeakingLanguage(lang.value);await ready;await enter({id:invite.get('room'),key:invite.get('key'),mode:invite.get('mode')==='lesson'?'lesson':'interpreter'});$('#modal').close();}catch(e){message(e.message);}finally{b.disabled=false;}};n.append(b);modal('招待が届いています',n);}


function currentSource(){return room?.mode==='lesson'?'ja':room?.mode==='face'?speakerInfo(faceSide,$('#face-self-language').value,$('#face-other-language').value).language:$('#source-language').value;}
function updateFace(){const face=room?.mode==='face';$('#face-controls').hidden=!face;$('#participants').hidden=face;if(!face){$('#text-input').placeholder='ことばを入力して送る';return;}const info=speakerInfo(faceSide,$('#face-self-language').value,$('#face-other-language').value);$('#face-speaker').textContent=info.speaker+'が話す';options($('#face-language'),info.language);paintButton($('#switch-speaker'),(faceSide==='self'?'相手の番にする':'じぶんの番にする'),'arrow-right-arrow-left');$('#text-input').placeholder=info.speaker+'のことばを入力';}

$('#face-language').onchange=()=>{if(room?.mode!=='face')return;const value=$('#face-language').value;speechPlayer.stop();stopRecognition(true);if(faceSide==='self')setSpeakingLanguage(value);else setSharedLanguage(value);updateFace();for(const record of [...records.values()])renderCaption(record);if(mic)startRecognition();};
$('#switch-speaker').onclick=()=>{if(room?.mode!=='face')return;speechPlayer.stop();stopRecognition(true);faceSide=faceSide==='self'?'other':'self';$('#text-input').value='';updateFace();if(mic)startRecognition();ledger.event('speaker_switch');};

function icon(name){const i=el('i',undefined,'fa-solid fa-'+name);i.setAttribute('aria-hidden','true');return i;}
function paintButton(button,text,name){button.replaceChildren(icon(name),el('span',text));if(button.id==='microphone')queueMicrotask(updateLiveActions);}
function updateLessonCode(){const visible=room?.mode==='lesson'&&!!room.code;$('#lesson-code-card').hidden=!visible;$('#lesson-room-code').textContent=visible?room.code:'';}
$('#copy-lesson-code').onclick=async()=>{try{await navigator.clipboard.writeText(room.code);message('ルームIDをコピーしました。');}catch{message('ルームID：'+room.code);}};
let joiningLesson=false,lastJoinCode='';async function joinLesson(){const input=$('#lesson-code-input'),code=input.value.replace(/[０-９]/g,c=>String(c.charCodeAt(0)-65296)).trim();input.value=code;if(joiningLesson||!/^\d{4}$/.test(code))return;joiningLesson=true;lastJoinCode=code;$('#join-lesson').disabled=true;input.disabled=true;$('#join-status').textContent='授業に入っています…';const joinEpoch=sessionEpoch;try{const r=await api('/lessons/join',{code});if(tab!=='lesson'||sessionEpoch!==joinEpoch)return;await enter(r);$('#join-status').textContent='';}catch(e){await exitModeFullscreen();lastJoinCode='';$('#join-status').textContent=e.message;if(e.connectionIssue)showConnectionError(e);}finally{joiningLesson=false;input.disabled=false;$('#join-lesson').disabled=false;}}
$('#join-lesson-form').onsubmit=e=>{e.preventDefault();void joinLesson();};$('#lesson-code-input').oninput=e=>{if(e.isComposing)return;const code=e.target.value.replace(/[０-９]/g,c=>String(c.charCodeAt(0)-65296)).trim();if(/^\d{4}$/.test(code)&&code!==lastJoinCode)void joinLesson();};
for(const [id,name]of [['microphone','microphone'],['leave','door-open'],['invite','user-plus']]){const b=$('#'+id);paintButton(b,b.textContent,name);}

function scheduleRoomExpiry(){clearTimeout(roomExpiryTimer);if(!room?.expires)return;const activeRoom=room;roomExpiryTimer=setTimeout(async()=>{if(room!==activeRoom)return;await leave();records.clear();elements.clear();$('#captions').replaceChildren();void listHistory().catch(()=>{});message('ルームの24時間の有効期限が切れました。新しいルームを作成してください。');},Math.max(0,room.expires-Date.now()));}

// Open the default conversation once; invitation links keep their join dialog.
if(!(/^[a-f0-9]{32}$/.test(invite.get('room')||'')&&/^[a-f0-9]{32}$/.test(invite.get('key')||''))){
 sessionStorage.removeItem('tsuyaku-update-tab');void activateTab('face');
} resetConversationContents();



// Refresh only an idle screen; never interrupt speech, peers, drafts or captions.
let checkingRelease=false;
async function checkForAppUpdate(){if(checkingRelease||document.visibilityState!=='visible'||mic||$('#text-input').value.trim()||records.size||participants.some(p=>p.id!==selfId)||(room&&!room.creator))return;checkingRelease=true;try{const url=new URL('index.html',location.href);url.searchParams.set('release-check',String(Date.now()));url.hash='';const response=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)return;const doc=new DOMParser().parseFromString(await response.text(),'text/html'),incoming=doc.querySelector('script[type="module"][src*="app.js"]')?.getAttribute('src'),current=document.querySelector('script[type="module"][src*="app.js"]')?.getAttribute('src');if(!incoming||incoming===current||mic||$('#text-input').value.trim()||records.size||participants.some(p=>p.id!==selfId))return;sessionStorage.setItem('tsuyaku-update-tab',tab);const fresh=new URL('index.html',location.href);fresh.searchParams.set('update',new URL(incoming,location.href).searchParams.get('v')||String(Date.now()));fresh.hash='';location.replace(fresh);}catch{}finally{checkingRelease=false;}}
setInterval(()=>void checkForAppUpdate(),60000);
window.addEventListener('pageshow',()=>void checkForAppUpdate());
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')void checkForAppUpdate();});
