import {UsageLedger} from './usage.js';
import {installAdmin} from './admin.js';
import {config} from './config.js';
import {catalog as seed} from '../server/catalog.js';
import {translationOf,csv} from './core.js';
import {saveHistory,listHistory} from './history.js';
import {createStreamingRecognition} from './caption-stream.js';
import {createServerRecognition} from './caption-server.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let catalog=seed,authApi,user,socket,room,selfId,role,localStream,recognition,restarting=false,sessionEpoch=0,listening=false,mic=false,participants=[],tab='interpreter',intentionalClose=false,refreshTimer,reconnectTimer,heartbeat;
const peers=new Map(),records=new Map(),elements=new Map(),pending=new Map();let turnReady=Promise.resolve(),rtcConfig={iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]};
const ledger=new UsageLedger(localStorage);let metricsTimer;
const message=text=>{$('#message').textContent=text;};
installAdmin({button:$('#admin'),modal,el,ledger,download,currentRecords:()=>[...records.values()],message});
const status=text=>{$('#connection').textContent=text;};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function modal(title,content){$('#modal-title').textContent=title;$('#modal-body').replaceChildren(content);$('#modal').showModal();}
$('#modal-close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close();};
function label(text,input){const n=el('label',text);n.append(input);return n;}
function options(select,selected){select.replaceChildren(...catalog.languages.map(l=>{const o=el('option',l.labelJa+' / '+l.labelNative);o.value=l.code;return o;}));select.value=selected;}
function fillLanguages(){for(const id of ['source-language','view-language','lesson-language'])options($('#'+id),localStorage.getItem(id)||(id==='source-language'?'ja':'pt'));}
fillLanguages();for(const id of ['source-language','view-language','lesson-language'])$('#'+id).onchange=()=>{localStorage.setItem(id,$('#'+id).value);renderReferences();};$('#name').value=localStorage.getItem('tsuyaku-name')||'';
function setTab(next){if(room&&['interpreter','lesson'].includes(next)&&next!==room.mode){message('モードを切り替えるときは、一度退室してください。');return;}tab=next;$$('[data-tab]').forEach(b=>{const active=b.dataset.tab===next;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;$('#panel-'+b.dataset.tab).hidden=!active||!!room&&['interpreter','lesson'].includes(next);});$('#live').hidden=!room||['phrases','terms'].includes(next);renderReferences();}
$$('[data-tab]').forEach(b=>{b.onclick=()=>setTab(b.dataset.tab);b.onkeydown=e=>{const tabs=$$('[data-tab]'),i=tabs.indexOf(b);let n;if(e.key==='ArrowRight')n=(i+1)%4;else if(e.key==='ArrowLeft')n=(i+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();tabs[n].focus();setTab(tabs[n].dataset.tab);};});
$('#help').onclick=()=>{const n=el('div');['通訳：招待リンクを相手に送り、2人で参加します。マイクを開始すると、声と字幕が相手に届きます。','授業：先生がログインして授業を開始し、生徒へ招待リンクを渡します。先生だけがマイクを使います。','授業の音声はミュートで始まります。「音声を再生」で先生の声を聞けます。翻訳の▶は、その文の読み上げです。','音声認識や翻訳には誤りが出ることがあります。数学の数字・符号が違うときは文字入力で伝え直せます。','履歴はこの端末へ保存できます。ルーム情報は最長6時間、授業終了後は1時間で削除します。音声は録音保存しません。','辞書の追加は先生が候補として送信し、確認した用語をスプレッドシートへ登録します。'].forEach(t=>n.append(el('p',t)));modal('使い方',n);};
$('#settings').onclick=async()=>{const n=el('div'),state=el('p',user?.isAnonymous?'ゲストで利用中':user?.displayName||'接続を準備中');n.append(state);const reload=el('button','辞書を更新');reload.onclick=async()=>{try{catalog=await api('/catalog');fillLanguages();renderReferences();message('辞書を更新しました。');$('#modal').close();}catch(e){message(e.message);}};n.append(reload);const link=el('a','スプレッドシートを開く');link.href=config.spreadsheet;link.target='_blank';link.rel='noopener';n.append(el('p'));n.append(link);const history=el('button','保存した履歴');history.onclick=showHistory;n.append(el('p'));n.append(history);const login=el('button','先生のログイン');login.onclick=loginTeacher;n.append(login);modal('設定',n);};
async function initAuth(){try{const [a,b]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js')]);authApi=b;const auth=b.getAuth(a.initializeApp(config.firebase));await auth.authStateReady();if(!auth.currentUser)await b.signInAnonymously(auth);user=auth.currentUser;b.onAuthStateChanged(auth,u=>{user=u;if(u&&!u.isAnonymous)$('#teacher-login').textContent=u.displayName||'先生でログイン中';});status('参加できます');}catch(e){status('接続できません');message('ログイン接続を確認してください。 '+e.message);}}
const ready=initAuth();
void ready.then(async()=>{if(!user)return;try{catalog=await api('/catalog');fillLanguages();renderReferences();}catch{message('保存済みの辞書を使っています。');}});
async function token(){await ready;if(!user)throw Error('ログイン接続を確認してください。');return user.getIdToken();}
async function api(path,data){const res=await fetch(config.api+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+await token(),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(25000),referrerPolicy:'no-referrer'});const result=await res.json();if(!res.ok||result.error)throw Error(result.error||'接続に失敗しました。');return result;}
async function loginTeacher(){try{await ready;if(room)throw Error('ログイン前に退室してください。');const result=await authApi.signInWithPopup(authApi.getAuth(),new authApi.GoogleAuthProvider());user=result.user;$('#teacher-login').textContent=user.displayName||'先生でログイン中';message('先生としてログインしました。');$('#modal').close();}catch(e){message(e.code==='auth/operation-not-allowed'?'先生のGoogleログインがまだ有効になっていません。管理者の設定が必要です。':e.message);}}
$('#teacher-login').onclick=loginTeacher;
async function create(mode){const button=$('#create-'+mode);button.disabled=true;try{await ready;if(mode==='lesson'&&user?.isAnonymous){await loginTeacher();if(user?.isAnonymous)return;}const r=await api('/rooms',{mode,unit:$('#unit').value||'数学'});await enter({...r,creator:true});showInvite();}catch(e){message(e.message);}finally{button.disabled=false;}}
$('#create-interpreter').onclick=()=>create('interpreter');$('#create-lesson').onclick=()=>create('lesson');
async function enter(r){await leave(false);room=r;ledger.begin(r.mode,[r.mode==='lesson'?'ja':$('#source-language').value,r.mode==='lesson'?$('#lesson-language').value:$('#view-language').value,'en']);clearInterval(metricsTimer);metricsTimer=setInterval(()=>void sampleRtc(),15000);role=r.creator?'teacher':null;listening=false;intentionalClose=false;records.clear();elements.clear();$('#captions').replaceChildren($('#empty-caption')||el('div','話したことばが、ここに。','empty'));$$('[role=tabpanel]').forEach(n=>n.hidden=true);$('#live').hidden=false;$$('[data-tab]').forEach(b=>b.disabled=false);setTab(r.mode);$('#live-mode').textContent=r.mode==='lesson'?'授業':'通訳';$('#live-title').textContent=r.mode==='lesson'?($('#unit').value||'数学'):'話しましょう';updateListen();localStorage.setItem('tsuyaku-name',$('#name').value);history.replaceState(null,'','#room='+r.id+'&key='+r.key+'&mode='+r.mode);await connect();refreshTimer=setInterval(async()=>{try{if(socket?.readyState===1)socket.send(JSON.stringify({type:'reauth',token:await user.getIdToken(true)}));}catch{message('ログインの更新に失敗しました。');}},45*60000);heartbeat=setInterval(()=>send({type:'ping'}),20000);}
async function connect(){const epoch=sessionEpoch;const t=await token();if(!room||epoch!==sessionEpoch)return;status('接続しています');turnReady=loadTurn();const r=room;socket=new WebSocket(config.api.replace(/^http/,'ws')+'/rooms/'+r.id+'/socket');socket.onopen=()=>socket.send(JSON.stringify({type:'auth',token:t,key:r.key,name:$('#name').value||user?.displayName||'参加者',viewLanguage:r.mode==='lesson'?$('#lesson-language').value:$('#view-language').value,language:r.mode==='lesson'?(role==='teacher'?'ja':$('#lesson-language').value):$('#source-language').value}));socket.onmessage=e=>{try{void handle(JSON.parse(e.data)).catch(e=>message('接続を確認してください。 '+e.message));}catch{message('受信したデータを確認できませんでした。');}};socket.onerror=()=>{ledger.event('socket_error');status('再接続しています');};socket.onclose=()=>{if(intentionalClose||!room)return;ledger.event('reconnect');status('再接続しています');stopRecognition();for(const p of peers.values()){p.pc.close();p.audio.remove();}peers.clear();reconnectTimer=setTimeout(()=>void connect(),2000);};}
function send(data){if(socket?.readyState!==1)return false;socket.send(JSON.stringify(data));return true;}
async function handle(data){
 if(data.type==='error'){ledger.event('server_error');message(data.error);return;}
 if(data.type==='ready'){selfId=data.id;role=data.role;room.mode=data.mode;$('#live-title').textContent=data.unit;status('接続中');$('#microphone').hidden=room.mode==='lesson'&&role!=='teacher';$('#text-form').hidden=room.mode==='lesson'&&role!=='teacher';$('#invite').hidden=role!=='teacher';for(const r of data.history||[])renderCaption(r);for(const p of pending.values())send(p);await turnReady;if(data.ended){await handle({type:'ended'});return;}if(mic)startRecognition();return;}
 if(data.type==='participants'){await turnReady;participants=data.participants;$('#participants').replaceChildren(...participants.map(p=>el('span',(p.id===selfId?'あなた':p.name)+(p.role==='teacher'&&room.mode==='lesson'?'・先生':''),'participant')));for(const [id,p] of peers){if(!participants.some(x=>x.id===id)){p.pc.close();p.audio.remove();peers.delete(id);}}for(const p of participants){if(p.id===selfId)continue;if(room.mode==='interpreter'&&selfId<p.id||room.mode==='lesson'&&role==='teacher')await offer(p.id);}return;}
 if(data.type==='signal'){await turnReady;await signal(data.from,data.signal);return;}
 if(data.type==='caption'){renderCaption(data);return;}
 if(data.type==='translation'){ledger.caption(data);renderCaption(data);records.set(data.id,data);for(const [id,p] of pending){if(data.id.endsWith('_'+id))pending.delete(id);}return;}
 if(data.type==='notice'){message(data.text);return;}
 if(data.type==='ended'){ledger.event('lesson_ended');ledger.end();clearInterval(metricsTimer);message('授業が終了しました。履歴を保存できます。');stopRecognition();mic=false;for(const p of peers.values()){p.pc.close();p.audio.remove();}peers.clear();localStream?.getTracks().forEach(t=>t.stop());localStream=null;$('#microphone').disabled=true;$('#text-form').hidden=true;return;}
}
async function loadTurn(){try{const response=await fetch(config.turn,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({callId:room?.id||'tsuyaku',clientId:crypto.randomUUID()}),signal:AbortSignal.timeout(8000)});if(response.ok){const data=await response.json();if(Array.isArray(data.iceServers))rtcConfig={iceServers:data.iceServers};}}catch{message('直接接続を使っています。音声が届かない場合は、一度退室して参加し直してください。');}}
function peer(id){if(peers.has(id))return peers.get(id);const pc=new RTCPeerConnection(rtcConfig),audio=el('audio');audio.autoplay=listening;audio.muted=!listening;audio.setAttribute('playsinline','');document.body.append(audio);const p={pc,audio,metricsId:crypto.randomUUID(),ice:[],offering:false};peers.set(id,p);pc.onicecandidate=e=>{if(e.candidate)send({type:'signal',to:id,signal:{candidate:e.candidate}});};pc.ontrack=e=>{audio.srcObject=e.streams[0]||new MediaStream([e.track]);if(listening)audio.play().catch(()=>message('「音声を再生」を押してください。'));};pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed'){ledger.event('rtc_failed');if(role==='teacher'||selfId<id){pc.restartIce();void offer(id,true);}}};if(localStream&&(room.mode==='interpreter'||role==='teacher'))localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));else pc.addTransceiver('audio',{direction:'recvonly'});return p;}
async function offer(id,restart=false){const p=peer(id);if(p.offering||p.pc.signalingState!=='stable')return;if(p.pc.currentLocalDescription&&!restart)return;p.offering=true;try{await p.pc.setLocalDescription(await p.pc.createOffer({iceRestart:restart}));send({type:'signal',to:id,signal:{description:p.pc.localDescription}});}catch(e){message('音声の接続に失敗しました。 '+e.message);}finally{p.offering=false;}}
async function signal(id,data){const p=peer(id);try{if(data.description){const polite=selfId>id||room.mode==='lesson'&&role!=='teacher';if(data.description.type==='offer'&&(p.offering||p.pc.signalingState!=='stable')){if(!polite)return;await p.pc.setLocalDescription({type:'rollback'});}await p.pc.setRemoteDescription(data.description);for(const candidate of p.ice.splice(0))await p.pc.addIceCandidate(candidate);if(data.description.type==='offer'){await p.pc.setLocalDescription(await p.pc.createAnswer());send({type:'signal',to:id,signal:{description:p.pc.localDescription}});}}else if(data.candidate){if(p.pc.remoteDescription)await p.pc.addIceCandidate(data.candidate);else p.ice.push(data.candidate);}}catch(e){message('音声接続を確認してください。 '+e.message);}}
async function ensureMicrophone(){if(!localStream)localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});for(const [id,p] of peers){const sender=p.pc.getSenders().find(s=>s.track?.kind==='audio'),transceiver=p.pc.getTransceivers().find(t=>t.receiver.track.kind==='audio');if(sender)await sender.replaceTrack(localStream.getAudioTracks()[0]);else if(transceiver){await transceiver.sender.replaceTrack(localStream.getAudioTracks()[0]);transceiver.direction='sendrecv';}else p.pc.addTrack(localStream.getAudioTracks()[0],localStream);await offer(id,true);}return localStream;}
$('#microphone').onclick=async()=>{if(!room)return;try{mic=!mic;if(mic){await ensureMicrophone();localStream.getAudioTracks().forEach(t=>t.enabled=true);startRecognition();}else{stopRecognition();localStream?.getAudioTracks().forEach(t=>t.enabled=false);}ledger.microphone(mic);ledger.event(mic?'mic_on':'mic_off');$('#microphone').textContent=mic?'マイク ON':'マイク OFF';$('#microphone').setAttribute('aria-pressed',mic);}catch(e){mic=false;ledger.microphone(false);ledger.event('microphone_error');message('マイクを許可して、もう一度押してください。 '+e.message);}};
function stopRecognition(){restarting=false;recognition?.abort();recognition=null;}
function startRecognition(fallback=false){stopRecognition();if(!mic||!room)return;const lang=room.mode==='lesson'?'ja':$('#source-language').value;let factory;if(lang==='ja'&&!fallback)factory=createStreamingRecognition({endpoint:'wss://kouryu-captions.allinone-hiroakiaa.workers.dev/stream',getStream:()=>localStream,getToken:token,onUsage:seconds=>ledger.audio(seconds,'stream')});else factory=createServerRecognition({endpoint:config.api+'/transcribe?language='+encodeURIComponent(lang),getStream:()=>localStream,getToken:token,onUsage:seconds=>ledger.audio(seconds,'whisper')});recognition=new factory();recognition.setHints?.(()=>catalog.glossary.map(t=>t.ja));const prefix=crypto.randomUUID().slice(0,8);recognition.onresult=e=>{const r=e.results[e.resultIndex];if(!r?.[0]?.transcript?.trim())return;const cap={type:'caption',id:prefix+'_'+e.resultIndex,text:r[0].transcript,final:r.isFinal};if(r.isFinal)pending.set(cap.id,cap);send(cap);};recognition.onerror=()=>{if(mic&&room&&!fallback&&lang==='ja'){ledger.event('asr_fallback');message('音声認識を補助方式へ切り替えました。');startRecognition(true);}else{ledger.event('asr_error');ledger.microphone(false);message('字幕の接続が途切れました。マイクを押し直すか文字で伝えてください。');mic=false;$('#microphone').textContent='マイクを再開';}};recognition.onend=()=>{if(mic&&room&&!restarting){restarting=true;setTimeout(()=>{if(mic&&room)startRecognition(fallback);},1000);}};recognition.start();}
function updateListen(){$('#listen').textContent=listening?'音声 ON':'音声を再生';$('#listen').setAttribute('aria-pressed',listening);for(const p of peers.values()){p.audio.muted=!listening;if(listening)p.audio.play().catch(()=>message('音声の再生を許可してください。'));else p.audio.pause();}}
$('#listen').onclick=()=>{listening=!listening;updateListen();};
function speak(text,lang){if(!('speechSynthesis' in window)){message('この端末では読み上げを使えません。');return;}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=catalog.languages.find(l=>l.code===lang)?.speechCode||lang;utterance.onerror=()=>message('この言語の読み上げ音声を端末に追加してください。');speechSynthesis.speak(utterance);}
function renderCaption(r){const nearBottom=$('#captions').scrollHeight-$('#captions').scrollTop-$('#captions').clientHeight<100;const old=records.get(r.id)||{};const next={...old,...r};if(!next.text)return;let article=elements.get(r.id);if(!article){$('#captions .empty')?.remove();article=el('article',undefined,'caption');elements.set(r.id,article);$('#captions').append(article);}article.className='caption'+(!next.final?' interim':next.status==='translating'||next.final&&!next.translations?' pending':'');article.replaceChildren();const meta=el('div',undefined,'caption-meta');meta.append(el('span',next.speaker||'参加者'));if(next.latencyMs)meta.append(el('span',(next.latencyMs/1000).toFixed(1)+'秒'));article.append(meta);const view=room?.mode==='lesson'?$('#lesson-language').value:$('#view-language').value;const codes=[...new Set(['ja',view,'en'])];for(const code of codes){const text=next.translations?.[code]||(code===next.source?next.text:'');const line=el('div',undefined,'caption-line');line.append(el('small',catalog.languages.find(l=>l.code===code)?.labelJa||code));line.append(el('p',text||(!next.final?'…':next.status==='failed'?'翻訳できませんでした':'翻訳しています…')));if(text){const button=el('button','▶');button.setAttribute('aria-label',code+'の文を読み上げる');button.onclick=()=>speak(text,code);line.append(button);}article.append(line);}if(next.status==='failed'&&next.id.startsWith(selfId+'_')){const retry=el('button','再試行');retry.onclick=()=>send({type:'caption',id:r.id.slice(r.id.indexOf('_')+1),text:next.text,final:true});article.append(retry);}records.set(r.id,next);if(nearBottom)$('#captions').scrollTop=$('#captions').scrollHeight;}
$('#text-form').onsubmit=e=>{e.preventDefault();const text=$('#text-input').value.trim();if(!text)return;const cap={type:'caption',id:crypto.randomUUID(),text,final:true};pending.set(cap.id,cap);if(send(cap))$('#text-input').value='';else message('再接続後に送信します。');};
function inviteLink(){const url=new URL(location.href);url.hash=new URLSearchParams({room:room.id,key:room.key,mode:room.mode}).toString();return url.href;}
function showInvite(){if(!room)return;const n=el('div'),input=el('input');input.readOnly=true;input.value=inviteLink();n.append(label('招待リンク',input));const copy=el('button','リンクをコピー');copy.onclick=async()=>{try{await navigator.clipboard.writeText(input.value);copy.textContent='コピーしました';}catch{input.select();message('招待リンクをコピーしてください。');}};n.append(copy);const canvas=el('canvas');canvas.className='qr';n.append(canvas);void import('./qr.js').then(m=>m.drawQr(canvas,input.value)).catch(()=>{});n.append(el('p','このリンクを受け取った人が参加できます。'));modal('相手を招待',n);}
$('#invite').onclick=showInvite;
function download(name,text,type='text/csv;charset=utf-8'){const a=el('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function exportHistory(){const session={id:room?.id||crypto.randomUUID(),at:Date.now(),mode:room?.mode||'interpreter',unit:$('#live-title').textContent,records:[...records.values()].filter(r=>r.final)};try{await saveHistory(session);message('この端末へ履歴を保存しました。');}catch{message('端末への保存に失敗しました。CSVはダウンロードできます。');}download('通訳君_'+new Date().toISOString().slice(0,10)+'.csv',csv([['日時','発言者','原文','日本語','英語','母語'],...session.records.map(r=>[new Date(r.at).toLocaleString('ja-JP'),r.speaker,r.text,r.translations?.ja,r.translations?.en,r.translations?.[room?.mode==='lesson'?$('#lesson-language').value:$('#view-language').value]])]));}
$('#export').onclick=exportHistory;
async function showHistory(){const n=el('div',undefined,'history-list');try{const sessions=await listHistory();if(!sessions.length)n.append(el('p','保存した履歴はまだありません。'));for(const s of sessions){const b=el('button',new Date(s.at).toLocaleString('ja-JP')+'・'+s.unit+'・'+s.records.length+'文');b.onclick=()=>download('通訳君_履歴.json',JSON.stringify(s,null,2),'application/json');n.append(b);}modal('保存した履歴',n);}catch{message('履歴を読み込めませんでした。');}}
async function leave(show=true){await sampleRtc();ledger.end();clearInterval(metricsTimer);sessionEpoch++;intentionalClose=true;clearTimeout(reconnectTimer);clearInterval(refreshTimer);clearInterval(heartbeat);stopRecognition();mic=false;socket?.close();socket=null;for(const p of peers.values()){p.pc.close();p.audio.remove();}peers.clear();localStream?.getTracks().forEach(t=>t.stop());localStream=null;pending.clear();room=null;$('#microphone').textContent='マイクを開始';$('#microphone').setAttribute('aria-pressed','false');$('#microphone').disabled=false;if(show){$('#live').hidden=true;$$('[data-tab]').forEach(b=>b.disabled=false);setTab(tab);history.replaceState(null,'',location.pathname);status('退室しました');}}
$('#leave').onclick=()=>{if(role==='teacher'&&room?.mode==='lesson'){const n=el('div');n.append(el('p','授業を終了すると、生徒への音声と字幕の配信が止まります。'));const end=el('button','授業を終了する');end.onclick=()=>{send({type:'end'});$('#modal').close();setTimeout(()=>void leave(),200);};const exit=el('button','自分だけ退室する');exit.onclick=()=>{$('#modal').close();void leave();};n.append(end,exit);modal('授業を終了',n);}else void leave();};
window.addEventListener('pagehide',()=>{ledger.end();void leave(false);});
async function sampleRtc(){for(const [id,p]of peers){try{const report=await p.pc.getStats();let pair;for(const v of report.values())if(v.type==='transport'&&v.selectedCandidatePairId)pair=report.get(v.selectedCandidatePairId);if(!pair)for(const v of report.values())if(v.type==='candidate-pair'&&v.state==='succeeded'&&v.nominated)pair=v;let lost=0,jitterMs=0;for(const v of report.values())if(v.type==='inbound-rtp'&&v.kind==='audio'){lost+=v.packetsLost||0;jitterMs=Math.max(jitterMs,(v.jitter||0)*1000);}if(pair)ledger.rtc(p.metricsId,{bytes:(pair.bytesSent||0)+(pair.bytesReceived||0),relay:report.get(pair.localCandidateId)?.candidateType==='relay'||report.get(pair.remoteCandidateId)?.candidateType==='relay',lost,jitterMs,rttMs:Number.isFinite(pair.currentRoundTripTime)?pair.currentRoundTripTime*1000:undefined});}catch{}}ledger.save();}
function showReference(row,type){const lang=room?.mode==='lesson'?$('#lesson-language').value:$('#view-language').value;const n=el('div',undefined,'reference-detail'),ja=type==='phrase'?row.jaText:row.descriptionJa,en=type==='phrase'?row.enText:row.en;for(const [name,text]of[['日本語',ja],['あなたのことば',translationOf(row,lang)],['English',en]]){if(text){n.append(el('h3',name),el('p',text));}}const play=el('button','訳を読み上げる');play.onclick=()=>speak(translationOf(row,lang)||en,translationOf(row,lang)?lang:'en');n.append(play);modal(row.title||row.ja,n);}
function renderReferences(){const lang=$('#view-language').value;for(const [type,list,q,rows]of[['phrase',$('#phrase-list'),$('#phrase-search').value,catalog.phrases],['term',$('#term-list'),$('#term-search').value,[...catalog.glossary,...catalog.terms]]]){const found=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())).slice(0,80);list.replaceChildren(...found.map(row=>{const card=el('article',undefined,'reference-card'),left=el('div');left.append(el('h3',row.title||row.ja),el('p',row.category||row.subject||''));card.append(left);const button=el('button','ひらく');button.onclick=()=>showReference(row,type);card.append(button);return card;}));if(!found.length)list.append(el('p','見つかりませんでした。'));}}
$('#phrase-search').oninput=renderReferences;$('#term-search').oninput=renderReferences;renderReferences();
$('#add-term').onclick=()=>{const n=el('form'),term=el('input'),tr=el('input'),lang=el('select');term.maxLength=80;tr.maxLength=500;options(lang,'en');n.append(label('ことば',term),label('訳',tr),label('言語',lang));const b=el('button','候補として送る');b.type='submit';n.append(b);n.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await api('/dictionary/candidate',{term:term.value,translation:tr.value,language:lang.value});message('スプレッドシートに候補を追加しました。');$('#modal').close();}catch(e){message(e.message);}finally{b.disabled=false;}};modal('ことばを追加',n);};
const invite=new URLSearchParams(location.hash.slice(1));if(/^[a-f0-9]{32}$/.test(invite.get('room')||'')&&/^[a-f0-9]{32}$/.test(invite.get('key')||'')){const n=el('div'),name=el('input'),lang=el('select');name.maxLength=40;name.value=$('#name').value;options(lang,$('#lesson-language').value);n.append(label('あなたの名前',name),label('あなたのことば',lang));const b=el('button','参加する');b.onclick=async()=>{b.disabled=true;try{$('#name').value=name.value;$('#lesson-language').value=lang.value;$('#source-language').value=lang.value;$('#view-language').value=lang.value;await ready;await enter({id:invite.get('room'),key:invite.get('key'),mode:invite.get('mode')==='lesson'?'lesson':'interpreter'});$('#modal').close();}catch(e){message(e.message);}finally{b.disabled=false;}};n.append(b);modal('招待が届いています',n);}

