// Private to this browser profile. Only explicitly reviewed translations are stored.
import {phraseIdentity} from './phrase-equivalence.js?v=20261007-reuse-1';
export const memoryKey=(source,text,unit='')=>JSON.stringify([source,phraseIdentity(text,source),unit]);
const MAX_ROWS=5000,MAX_BYTES=16*1024*1024;
export function retentionScore(row,now=Date.now()){return Math.log2(1+Math.min(row.hits||0,1024))*7-Math.max(0,now-(row.lastUsed||row.at||now))/86400000;}
export function retainedRows(rows,now=Date.now()){let bytes=0;return rows.sort((a,b)=>retentionScore(b,now)-retentionScore(a,now)).filter((row,index)=>{const size=JSON.stringify(row).length*2;if(index>=MAX_ROWS||bytes+size>MAX_BYTES)return false;bytes+=size;return true;});}
export class ReviewedStore {
 constructor(factory=globalThis.indexedDB){this.factory=factory;this.queue=Promise.resolve();this.writes=0;this.ready=this.open();}
 open(){if(!this.factory)return Promise.resolve(null);return new Promise(resolve=>{let request;try{request=this.factory.open('tsuyaku-reviewed-translations',1);}catch{return resolve(null);}request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('translations'))db.createObjectStore('translations',{keyPath:'key'});};request.onsuccess=()=>{const db=request.result;db.onversionchange=()=>db.close();resolve(db);};request.onerror=request.onblocked=()=>resolve(null);});}
 async get(key){const db=await this.ready;if(!db)return null;return new Promise(resolve=>{try{const tx=db.transaction('translations','readonly'),r=tx.objectStore('translations').get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>resolve(null);tx.onabort=()=>resolve(null);}catch{resolve(null);}});}
 put(row){this.queue=this.queue.then(async()=>{const db=await this.ready;if(!db)return false;const ok=await new Promise(resolve=>{try{const tx=db.transaction('translations','readwrite');tx.objectStore('translations').put({...row,key:memoryKey(row.source,row.text,row.unit)});tx.oncomplete=()=>resolve(true);tx.onerror=tx.onabort=()=>resolve(false);}catch{resolve(false);}});if(ok&&++this.writes%50===0)await this.prune(db);return ok;}).catch(()=>false);return this.queue;}
 async prune(db){const rows=await new Promise(resolve=>{try{const tx=db.transaction('translations','readonly'),r=tx.objectStore('translations').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>resolve([]);tx.onabort=()=>resolve([]);}catch{resolve([]);}});const keep=new Set(retainedRows(rows).map(r=>r.key));if(keep.size===rows.length)return;await new Promise(resolve=>{try{const tx=db.transaction('translations','readwrite'),store=tx.objectStore('translations');for(const r of rows)if(!keep.has(r.key))store.delete(r.key);tx.oncomplete=tx.onabort=tx.onerror=()=>resolve();}catch{resolve();}});}
}
