import {resourceSnapshot} from './resource-usage.js?v=20261008-safety-2';
export const BUILD_ID='20261009-diagnostics-1';
// Device-local operational history. No names, room keys, tokens or speech are stored here.
export const PRICES={checkedAt:'2026-10-06',inputPerMillion:.10,outputPerMillion:.30,streamPerMinute:.0092,whisperPerMinute:.000513,turnPerGB:.05};
export function percentile(values,p){const a=values.filter(Number.isFinite).sort((a,b)=>a-b);return a.length?a[Math.max(0,Math.ceil(a.length*p)-1)]:null;}
export function costOf(s,p=PRICES){const translation=(s.inputTokens||0)/1e6*p.inputPerMillion+(s.outputTokens||0)/1e6*p.outputPerMillion,recognition=(s.streamSeconds||0)/60*p.streamPerMinute+(s.whisperSeconds||0)/60*p.whisperPerMinute,turn=(s.relayBytes||0)/1e9*p.turnPerGB;return {translation,recognition,turn,total:translation+recognition+turn};}
export class UsageLedger{
 constructor(storage,now=()=>Date.now()){this.storage=storage;this.now=now;this.current=null;this.attempts=new Set();this.captions=new Map();this.reuse=new Map();this.rtcPrevious=new Map();this.micAt=null;this.timingIds=new Set();this.storageError=false;}
 list(){try{return JSON.parse(this.storage.getItem('tsuyaku-usage-v1')||'[]').filter(s=>s&&typeof s.id==='string').slice(0,200);}catch{return [];}}
 begin(mode,languages){this.end();this.attempts.clear();this.captions.clear();this.reuse.clear();this.rtcPrevious.clear();this.timingIds.clear();this.current={id:crypto.randomUUID(),build:BUILD_ID,mode,languages:[...new Set(languages)],startedAt:this.now(),updatedAt:this.now(),durationSeconds:0,micSeconds:0,streamSeconds:0,whisperSeconds:0,inputTokens:0,outputTokens:0,estimatedTokenCalls:0,unmeasuredCalls:0,attemptCount:0,captionCount:0,failedCaptions:0,failedAttempts:0,cacheHits:0,reuseCounts:{spreadsheet:0,reviewed:0,session:0,ai:0,unmeasured:0},latencies:[],speechLatencies:[],recognitionLatencies:[],pipelineLatencies:[],firstDisplayLatencies:[],relayBytes:0,packetsLost:0,maxJitterMs:0,rttMs:[],events:[],ended:false,priceSnapshot:{...PRICES}};this.save();}
 save(){if(!this.current)return;const snapshotAt=this.now();if(this.micAt!==null){this.current.micSeconds+=Math.max(0,(snapshotAt-this.micAt)/1000);this.micAt=snapshotAt;}this.current.updatedAt=snapshotAt;this.current.durationSeconds=Math.max(0,(this.now()-this.current.startedAt)/1000);const rows=this.list().filter(s=>s.id!==this.current.id);try{this.storage.setItem('tsuyaku-usage-v1',JSON.stringify([this.current,...rows].slice(0,200)));this.storageError=false;}catch{this.storageError=true;}}
 end(){if(!this.current)return;this.microphone(false);this.current.ended=true;this.save();this.current=null;}
 event(type,details={}){if(!this.current)return;this.current.events.push({seconds:Math.round((this.now()-this.current.startedAt)/1000),type,...Object.fromEntries(Object.entries(details).filter(([k,v])=>['code','wasClean','openSeconds','recoverySeconds','attempt','retryMs','visibility','online','recognitionCode'].includes(k)&&(['number','boolean'].includes(typeof v)||['visible','hidden','network','auth','quota','billing','input','model','service','timeout','overloaded','interrupted','audio-capture','unknown'].includes(v))))});this.current.events=this.current.events.slice(-100);this.save();}
 microphone(on){if(on&&this.micAt===null)this.micAt=this.now();if(!on&&this.micAt!==null){if(this.current)this.current.micSeconds+=(this.now()-this.micAt)/1000;this.micAt=null;this.save();}}
 audio(seconds,kind){if(!this.current||!Number.isFinite(seconds)||seconds<0)return;this.current[kind==='stream'?'streamSeconds':'whisperSeconds']+=seconds;if(!this.audioSavedAt||this.now()-this.audioSavedAt>=1000){this.audioSavedAt=this.now();this.save();}}
 reuseLookup(diagnostic){if(!this.current||!diagnostic)return;const s=this.current;s.reuseLookupCounts??={complete:0,missing_languages:0,no_match:0};if(Object.hasOwn(s.reuseLookupCounts,diagnostic.reason))s.reuseLookupCounts[diagnostic.reason]++;s.missingTranslationLanguages??={};for(const code of diagnostic.missing||[])if(/^[a-z]{2}(?:-[A-Za-z]+)?$/.test(code))s.missingTranslationLanguages[code]=(s.missingTranslationLanguages[code]||0)+1;this.save();}
 caption(r){if(!this.current||!r.final)return;const signature=r.usageId||r.id+':'+r.at;if(this.attempts.has(signature))return;this.attempts.add(signature);this.captions.set(r.id,r.status);const s=this.current;s.languages=[...new Set([...s.languages,...Object.keys(r.translations||{}).filter(code=>/^[a-z]{2}(?:-[A-Za-z]+)?$/.test(code))])];s.captionCount=this.captions.size;s.failedCaptions=[...this.captions.values()].filter(x=>x==='failed').length;s.attemptCount++;if(r.status==='failed')s.failedAttempts++;if(r.status==='ready'&&Number.isFinite(r.latencyMs))s.latencies.push(r.latencyMs);s.latencies=s.latencies.slice(-600);const u=r.usage;if(u?.translationTiming){const t=u.translationTiming;s.translationTimings??=[];s.translationTimings.push({status:r.status==='ready'?'ready':'failed',...Object.fromEntries(['dictionaryMs','aiTotalMs','providerMs','queueMs'].map(k=>[k,Number.isFinite(t[k])&&t[k]>=0?t[k]:null])),...(typeof t.serverBuild==='string'&&/^[a-z0-9-]{1,80}$/.test(t.serverBuild)?{serverBuild:t.serverBuild}:{})});s.translationTimings=s.translationTimings.slice(-600);}if(r.status==='ready'){const kind=u?.cacheHit?(r.memorySource==='spreadsheet'||u.cacheSource==='spreadsheet'?'spreadsheet':r.memorySource==='reviewed'?'reviewed':'session'):u&&!u.unknown?'ai':'unmeasured';this.reuse.set(r.id,kind);s.reuseCounts={spreadsheet:0,reviewed:0,session:0,ai:0,unmeasured:0};for(const value of this.reuse.values())s.reuseCounts[value]++;}if(u){s.inputTokens+=u.inputTokens||0;s.outputTokens+=u.outputTokens||0;if(u.estimated)s.estimatedTokenCalls++;if(u.unknown)s.unmeasuredCalls++;if(u.cacheHit)s.cacheHits++;}else s.unmeasuredCalls++;if(r.status==='failed')this.event('translation_failed');this.save();}
 timing(id,metrics){if(!this.current||!metrics||this.timingIds.has(id))return;this.timingIds.add(id);for(const [field,value]of [['speechLatencies',metrics.totalMs],['recognitionLatencies',metrics.recognitionMs],['pipelineLatencies',metrics.pipelineMs],['firstDisplayLatencies',metrics.firstDisplayMs]]){if(Number.isFinite(value)&&value>=0){this.current[field]??=[];this.current[field].push(value);this.current[field]=this.current[field].slice(-600);}}this.save();}
 rtc(id,data){if(!this.current)return;const prev=this.rtcPrevious.get(id)||{bytes:0,lost:0};const bytes=Math.max(0,data.bytes||0),lost=Math.max(0,data.lost||0);if(data.relay)this.current.relayBytes+=Math.max(0,bytes-prev.bytes);this.current.packetsLost+=Math.max(0,lost-prev.lost);this.current.maxJitterMs=Math.max(this.current.maxJitterMs,data.jitterMs||0);if(Number.isFinite(data.rttMs))this.current.rttMs.push(data.rttMs);this.current.rttMs=this.current.rttMs.slice(-1000);this.rtcPrevious.set(id,{bytes,lost});this.save();}
}
export function analysisReport(sessions,{exchange=150,transcripts=[]}={}){const attempts=sessions.reduce((n,s)=>n+s.attemptCount,0),failed=sessions.reduce((n,s)=>n+s.failedCaptions,0),captions=sessions.reduce((n,s)=>n+s.captionCount,0),latencies=sessions.flatMap(s=>s.latencies||[]),total=sessions.reduce((n,s)=>n+costOf(s,s.priceSnapshot||PRICES).total,0);return JSON.stringify({app:'通訳君',schema:'tsuyaku-analysis-v1',version:'0.6.9',build:BUILD_ID,exportedAt:new Date().toISOString(),scope:'この端末で記録した利用のみ。複数端末の同一ルームの値を合算しない。翻訳費用はルームの観測分、音声認識とTURNはこの端末の観測分。',billing:'無料枠適用前の変動費推定。固定費・Workers/DO・Firestore・Google Apps Script・他端末の音声認識は含まない。未計測呼び出しは0円と断定しない。',resourceConsumption:{...resourceSnapshot(),scope:'この端末の当日UTCの呼び出し試行のみ。サーバーのalarm・ストレージ操作・他端末は未計測。Cloudflare請求値ではありません。'},exchangeSetting:exchange,reuse:reuseSummary(sessions),summary:{sessions:sessions.length,activeSessions:sessions.filter(s=>s.micSeconds>0||s.attemptCount>0||s.relayBytes>0).length,preparationOnlySessions:sessions.filter(s=>!(s.micSeconds>0||s.attemptCount>0||s.relayBytes>0)).length,captions,attempts,failedCaptions:failed,p50TranslationMs:percentile(latencies,.5),p95TranslationMs:percentile(latencies,.95),p95FirstDisplayMs:percentile(sessions.flatMap(s=>s.firstDisplayLatencies||[]),.95),firstDisplaySamples:sessions.reduce((n,s)=>n+(s.firstDisplayLatencies||[]).length,0),p95SpeechToDisplayMs:percentile(sessions.flatMap(s=>s.speechLatencies||[]),.95),p95RecognitionMs:percentile(sessions.flatMap(s=>s.recognitionLatencies||[]),.95),speechTimingSamples:sessions.reduce((n,s)=>n+(s.speechLatencies||[]).length,0),reconnectCount:sessions.reduce((n,s)=>n+(s.events||[]).filter(e=>e.type==='reconnect').length,0),observedVariableCostUSD:total,observedVariableCostJPY:total*exchange},sessions:sessions.map(s=>({...s,cost:costOf(s,s.priceSnapshot||PRICES)})),...(transcripts.length?{transcripts}:{}),timingNote:'firstDisplayLatenciesは最初の音声区間の発話開始から最初の訳の表示まで（PCM音量からの推定）。続きの更新は対象外。speechLatenciesとrecognitionLatenciesは送信端末のPCM音量から推定した発話末尾基準。相手端末・過去の字幕・無音・文字入力は対象外。pipelineLatenciesは送信から画面反映直前まで。翻訳latenciesはサーバー処理だけ。translationTimingsのaiTotalMsは費用制御・有効性確認とAI処理の合計、providerMsはAI.runの待ち時間（通信・AI側の待機を含む）。queueMsは未計測ならnull。旧履歴にはbuildや内訳がありません。nullは未計測。',request:'上の計測結果から、翻訳品質・反応速度・音声接続・費用の改善候補を整理してください。未計測値と観測事実を区別し、通訳君のコード改善に必要な確認項目を示してください。'},null,2);}

export function reuseSummary(sessions){const measured=sessions.filter(s=>s.reuseCounts),counts={spreadsheet:0,reviewed:0,session:0,ai:0,unmeasured:0};for(const s of measured)for(const k of Object.keys(counts))counts[k]+=s.reuseCounts[k]||0;const noAI=counts.spreadsheet+counts.reviewed+counts.session,known=noAI+counts.ai;return {counts,measuredSessions:measured.length,unmeasuredSessions:sessions.length-measured.length,measuredSuccessfulCaptions:known,withoutAI: noAI,withoutAIRate:known?noAI/known:null,recognitionCorrections:sessions.reduce((n,s)=>n+(s.events||[]).filter(e=>e.type==='recognition_correction').length,0),translationReviews:sessions.reduce((n,s)=>n+(s.events||[]).filter(e=>e.type==='translation_review').length,0),note:'字幕単位の直近成功結果。部分再利用でAIを呼んだ文はAIに分類。旧履歴と未計測は割合の分母から除外。修正・確認回数は利用者の操作であり誤訳率・認識精度を自動判定しません。'};}
